// Register NVDLA_CDMA_S_STATUS_0
#define NVDLA_CDMA_S_STATUS_0			_MK_ADDR_CONST(0x3000)
#define NVDLA_CDMA_S_STATUS_0_STATUS_0_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CDMA_S_STATUS_0_STATUS_0_FIELD			_MK_FIELD_CONST(0x3, NVDLA_CDMA_S_STATUS_0_STATUS_0_SHIFT)
#define NVDLA_CDMA_S_STATUS_0_STATUS_0_IDLE			_MK_ENUM_CONST(0x0)
#define NVDLA_CDMA_S_STATUS_0_STATUS_0_RUNNING			_MK_ENUM_CONST(0x1)
#define NVDLA_CDMA_S_STATUS_0_STATUS_0_PENDING			_MK_ENUM_CONST(0x2)
#define NVDLA_CDMA_S_STATUS_0_STATUS_1_SHIFT			_MK_SHIFT_CONST(16)
#define NVDLA_CDMA_S_STATUS_0_STATUS_1_FIELD			_MK_FIELD_CONST(0x3, NVDLA_CDMA_S_STATUS_0_STATUS_1_SHIFT)
#define NVDLA_CDMA_S_STATUS_0_STATUS_1_IDLE			_MK_ENUM_CONST(0x0)
#define NVDLA_CDMA_S_STATUS_0_STATUS_1_RUNNING			_MK_ENUM_CONST(0x1)
#define NVDLA_CDMA_S_STATUS_0_STATUS_1_PENDING			_MK_ENUM_CONST(0x2)


// Register NVDLA_CDMA_S_POINTER_0
#define NVDLA_CDMA_S_POINTER_0			_MK_ADDR_CONST(0x3004)
#define NVDLA_CDMA_S_POINTER_0_PRODUCER_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CDMA_S_POINTER_0_PRODUCER_FIELD			_MK_FIELD_CONST(0x1, NVDLA_CDMA_S_POINTER_0_PRODUCER_SHIFT)
#define NVDLA_CDMA_S_POINTER_0_PRODUCER_GROUP_0			_MK_ENUM_CONST(0x0)
#define NVDLA_CDMA_S_POINTER_0_PRODUCER_GROUP_1			_MK_ENUM_CONST(0x1)
#define NVDLA_CDMA_S_POINTER_0_CONSUMER_SHIFT			_MK_SHIFT_CONST(16)
#define NVDLA_CDMA_S_POINTER_0_CONSUMER_FIELD			_MK_FIELD_CONST(0x1, NVDLA_CDMA_S_POINTER_0_CONSUMER_SHIFT)
#define NVDLA_CDMA_S_POINTER_0_CONSUMER_GROUP_0			_MK_ENUM_CONST(0x0)
#define NVDLA_CDMA_S_POINTER_0_CONSUMER_GROUP_1			_MK_ENUM_CONST(0x1)


// Register NVDLA_CDMA_S_ARBITER_0
#define NVDLA_CDMA_S_ARBITER_0			_MK_ADDR_CONST(0x3008)
#define NVDLA_CDMA_S_ARBITER_0_ARB_WEIGHT_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CDMA_S_ARBITER_0_ARB_WEIGHT_FIELD			_MK_FIELD_CONST(0xf, NVDLA_CDMA_S_ARBITER_0_ARB_WEIGHT_SHIFT)
#define NVDLA_CDMA_S_ARBITER_0_ARB_WMB_SHIFT			_MK_SHIFT_CONST(16)
#define NVDLA_CDMA_S_ARBITER_0_ARB_WMB_FIELD			_MK_FIELD_CONST(0xf, NVDLA_CDMA_S_ARBITER_0_ARB_WMB_SHIFT)


// Register NVDLA_CDMA_S_CBUF_FLUSH_STATUS_0
#define NVDLA_CDMA_S_CBUF_FLUSH_STATUS_0			_MK_ADDR_CONST(0x300c)
#define NVDLA_CDMA_S_CBUF_FLUSH_STATUS_0_FLUSH_DONE_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CDMA_S_CBUF_FLUSH_STATUS_0_FLUSH_DONE_FIELD			_MK_FIELD_CONST(0x1, NVDLA_CDMA_S_CBUF_FLUSH_STATUS_0_FLUSH_DONE_SHIFT)


// Register NVDLA_CDMA_D_OP_ENABLE_0
#define NVDLA_CDMA_D_OP_ENABLE_0			_MK_ADDR_CONST(0x3010)
#define NVDLA_CDMA_D_OP_ENABLE_0_OP_EN_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CDMA_D_OP_ENABLE_0_OP_EN_FIELD			_MK_FIELD_CONST(0x1, NVDLA_CDMA_D_OP_ENABLE_0_OP_EN_SHIFT)
#define NVDLA_CDMA_D_OP_ENABLE_0_OP_EN_DISABLE			_MK_ENUM_CONST(0x0)
#define NVDLA_CDMA_D_OP_ENABLE_0_OP_EN_ENABLE			_MK_ENUM_CONST(0x1)


// Register NVDLA_CDMA_D_MISC_CFG_0
#define NVDLA_CDMA_D_MISC_CFG_0			_MK_ADDR_CONST(0x3014)
#define NVDLA_CDMA_D_MISC_CFG_0_CONV_MODE_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CDMA_D_MISC_CFG_0_CONV_MODE_FIELD			_MK_FIELD_CONST(0x1, NVDLA_CDMA_D_MISC_CFG_0_CONV_MODE_SHIFT)
#define NVDLA_CDMA_D_MISC_CFG_0_CONV_MODE_DIRECT			_MK_ENUM_CONST(0x0)
#define NVDLA_CDMA_D_MISC_CFG_0_CONV_MODE_WINOGRAD			_MK_ENUM_CONST(0x1)
#define NVDLA_CDMA_D_MISC_CFG_0_IN_PRECISION_SHIFT			_MK_SHIFT_CONST(8)
#define NVDLA_CDMA_D_MISC_CFG_0_IN_PRECISION_FIELD			_MK_FIELD_CONST(0x3, NVDLA_CDMA_D_MISC_CFG_0_IN_PRECISION_SHIFT)
#define NVDLA_CDMA_D_MISC_CFG_0_IN_PRECISION_INT8			_MK_ENUM_CONST(0x0)
#define NVDLA_CDMA_D_MISC_CFG_0_IN_PRECISION_INT16			_MK_ENUM_CONST(0x1)
#define NVDLA_CDMA_D_MISC_CFG_0_IN_PRECISION_FP16			_MK_ENUM_CONST(0x2)
#define NVDLA_CDMA_D_MISC_CFG_0_PROC_PRECISION_SHIFT			_MK_SHIFT_CONST(12)
#define NVDLA_CDMA_D_MISC_CFG_0_PROC_PRECISION_FIELD			_MK_FIELD_CONST(0x3, NVDLA_CDMA_D_MISC_CFG_0_PROC_PRECISION_SHIFT)
#define NVDLA_CDMA_D_MISC_CFG_0_PROC_PRECISION_INT8			_MK_ENUM_CONST(0x0)
#define NVDLA_CDMA_D_MISC_CFG_0_PROC_PRECISION_INT16			_MK_ENUM_CONST(0x1)
#define NVDLA_CDMA_D_MISC_CFG_0_PROC_PRECISION_FP16			_MK_ENUM_CONST(0x2)
#define NVDLA_CDMA_D_MISC_CFG_0_DATA_REUSE_SHIFT			_MK_SHIFT_CONST(16)
#define NVDLA_CDMA_D_MISC_CFG_0_DATA_REUSE_FIELD			_MK_FIELD_CONST(0x1, NVDLA_CDMA_D_MISC_CFG_0_DATA_REUSE_SHIFT)
#define NVDLA_CDMA_D_MISC_CFG_0_DATA_REUSE_DISABLE			_MK_ENUM_CONST(0x0)
#define NVDLA_CDMA_D_MISC_CFG_0_DATA_REUSE_ENABLE			_MK_ENUM_CONST(0x1)
#define NVDLA_CDMA_D_MISC_CFG_0_WEIGHT_REUSE_SHIFT			_MK_SHIFT_CONST(20)
#define NVDLA_CDMA_D_MISC_CFG_0_WEIGHT_REUSE_FIELD			_MK_FIELD_CONST(0x1, NVDLA_CDMA_D_MISC_CFG_0_WEIGHT_REUSE_SHIFT)
#define NVDLA_CDMA_D_MISC_CFG_0_WEIGHT_REUSE_DISABLE			_MK_ENUM_CONST(0x0)
#define NVDLA_CDMA_D_MISC_CFG_0_WEIGHT_REUSE_ENABLE			_MK_ENUM_CONST(0x1)
#define NVDLA_CDMA_D_MISC_CFG_0_SKIP_DATA_RLS_SHIFT			_MK_SHIFT_CONST(24)
#define NVDLA_CDMA_D_MISC_CFG_0_SKIP_DATA_RLS_FIELD			_MK_FIELD_CONST(0x1, NVDLA_CDMA_D_MISC_CFG_0_SKIP_DATA_RLS_SHIFT)
#define NVDLA_CDMA_D_MISC_CFG_0_SKIP_DATA_RLS_DISABLE			_MK_ENUM_CONST(0x0)
#define NVDLA_CDMA_D_MISC_CFG_0_SKIP_DATA_RLS_ENABLE			_MK_ENUM_CONST(0x1)
#define NVDLA_CDMA_D_MISC_CFG_0_SKIP_WEIGHT_RLS_SHIFT			_MK_SHIFT_CONST(28)
#define NVDLA_CDMA_D_MISC_CFG_0_SKIP_WEIGHT_RLS_FIELD			_MK_FIELD_CONST(0x1, NVDLA_CDMA_D_MISC_CFG_0_SKIP_WEIGHT_RLS_SHIFT)
#define NVDLA_CDMA_D_MISC_CFG_0_SKIP_WEIGHT_RLS_DISABLE			_MK_ENUM_CONST(0x0)
#define NVDLA_CDMA_D_MISC_CFG_0_SKIP_WEIGHT_RLS_ENABLE			_MK_ENUM_CONST(0x1)


// Register NVDLA_CDMA_D_DATAIN_FORMAT_0
#define NVDLA_CDMA_D_DATAIN_FORMAT_0			_MK_ADDR_CONST(0x3018)
#define NVDLA_CDMA_D_DATAIN_FORMAT_0_DATAIN_FORMAT_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CDMA_D_DATAIN_FORMAT_0_DATAIN_FORMAT_FIELD			_MK_FIELD_CONST(0x1, NVDLA_CDMA_D_DATAIN_FORMAT_0_DATAIN_FORMAT_SHIFT)
#define NVDLA_CDMA_D_DATAIN_FORMAT_0_DATAIN_FORMAT_FEATURE			_MK_ENUM_CONST(0x0)
#define NVDLA_CDMA_D_DATAIN_FORMAT_0_DATAIN_FORMAT_PIXEL			_MK_ENUM_CONST(0x1)
#define NVDLA_CDMA_D_DATAIN_FORMAT_0_PIXEL_FORMAT_SHIFT			_MK_SHIFT_CONST(8)
#define NVDLA_CDMA_D_DATAIN_FORMAT_0_PIXEL_FORMAT_FIELD			_MK_FIELD_CONST(0x3f, NVDLA_CDMA_D_DATAIN_FORMAT_0_PIXEL_FORMAT_SHIFT)
#define NVDLA_CDMA_D_DATAIN_FORMAT_0_PIXEL_FORMAT_T_R8			_MK_ENUM_CONST(0x0)
#define NVDLA_CDMA_D_DATAIN_FORMAT_0_PIXEL_FORMAT_T_R10			_MK_ENUM_CONST(0x1)
#define NVDLA_CDMA_D_DATAIN_FORMAT_0_PIXEL_FORMAT_T_R12			_MK_ENUM_CONST(0x2)
#define NVDLA_CDMA_D_DATAIN_FORMAT_0_PIXEL_FORMAT_T_R16			_MK_ENUM_CONST(0x3)
#define NVDLA_CDMA_D_DATAIN_FORMAT_0_PIXEL_FORMAT_T_R16_I			_MK_ENUM_CONST(0x4)
#define NVDLA_CDMA_D_DATAIN_FORMAT_0_PIXEL_FORMAT_T_R16_F			_MK_ENUM_CONST(0x5)
#define NVDLA_CDMA_D_DATAIN_FORMAT_0_PIXEL_FORMAT_T_A16B16G16R16			_MK_ENUM_CONST(0x6)
#define NVDLA_CDMA_D_DATAIN_FORMAT_0_PIXEL_FORMAT_T_X16B16G16R16			_MK_ENUM_CONST(0x7)
#define NVDLA_CDMA_D_DATAIN_FORMAT_0_PIXEL_FORMAT_T_A16B16G16R16_F			_MK_ENUM_CONST(0x8)
#define NVDLA_CDMA_D_DATAIN_FORMAT_0_PIXEL_FORMAT_T_A16Y16U16V16			_MK_ENUM_CONST(0x9)
#define NVDLA_CDMA_D_DATAIN_FORMAT_0_PIXEL_FORMAT_T_V16U16Y16A16			_MK_ENUM_CONST(0xa)
#define NVDLA_CDMA_D_DATAIN_FORMAT_0_PIXEL_FORMAT_T_A16Y16U16V16_F			_MK_ENUM_CONST(0xb)
#define NVDLA_CDMA_D_DATAIN_FORMAT_0_PIXEL_FORMAT_T_A8B8G8R8			_MK_ENUM_CONST(0xc)
#define NVDLA_CDMA_D_DATAIN_FORMAT_0_PIXEL_FORMAT_T_A8R8G8B8			_MK_ENUM_CONST(0xd)
#define NVDLA_CDMA_D_DATAIN_FORMAT_0_PIXEL_FORMAT_T_B8G8R8A8			_MK_ENUM_CONST(0xe)
#define NVDLA_CDMA_D_DATAIN_FORMAT_0_PIXEL_FORMAT_T_R8G8B8A8			_MK_ENUM_CONST(0xf)
#define NVDLA_CDMA_D_DATAIN_FORMAT_0_PIXEL_FORMAT_T_X8B8G8R8			_MK_ENUM_CONST(0x10)
#define NVDLA_CDMA_D_DATAIN_FORMAT_0_PIXEL_FORMAT_T_X8R8G8B8			_MK_ENUM_CONST(0x11)
#define NVDLA_CDMA_D_DATAIN_FORMAT_0_PIXEL_FORMAT_T_B8G8R8X8			_MK_ENUM_CONST(0x12)
#define NVDLA_CDMA_D_DATAIN_FORMAT_0_PIXEL_FORMAT_T_R8G8B8X8			_MK_ENUM_CONST(0x13)
#define NVDLA_CDMA_D_DATAIN_FORMAT_0_PIXEL_FORMAT_T_A2B10G10R10			_MK_ENUM_CONST(0x14)
#define NVDLA_CDMA_D_DATAIN_FORMAT_0_PIXEL_FORMAT_T_A2R10G10B10			_MK_ENUM_CONST(0x15)
#define NVDLA_CDMA_D_DATAIN_FORMAT_0_PIXEL_FORMAT_T_B10G10R10A2			_MK_ENUM_CONST(0x16)
#define NVDLA_CDMA_D_DATAIN_FORMAT_0_PIXEL_FORMAT_T_R10G10B10A2			_MK_ENUM_CONST(0x17)
#define NVDLA_CDMA_D_DATAIN_FORMAT_0_PIXEL_FORMAT_T_A2Y10U10V10			_MK_ENUM_CONST(0x18)
#define NVDLA_CDMA_D_DATAIN_FORMAT_0_PIXEL_FORMAT_T_V10U10Y10A2			_MK_ENUM_CONST(0x19)
#define NVDLA_CDMA_D_DATAIN_FORMAT_0_PIXEL_FORMAT_T_A8Y8U8V8			_MK_ENUM_CONST(0x1a)
#define NVDLA_CDMA_D_DATAIN_FORMAT_0_PIXEL_FORMAT_T_V8U8Y8A8			_MK_ENUM_CONST(0x1b)
#define NVDLA_CDMA_D_DATAIN_FORMAT_0_PIXEL_FORMAT_T_Y8___U8V8_N444			_MK_ENUM_CONST(0x1c)
#define NVDLA_CDMA_D_DATAIN_FORMAT_0_PIXEL_FORMAT_T_Y8___V8U8_N444			_MK_ENUM_CONST(0x1d)
#define NVDLA_CDMA_D_DATAIN_FORMAT_0_PIXEL_FORMAT_T_Y10___U10V10_N444			_MK_ENUM_CONST(0x1e)
#define NVDLA_CDMA_D_DATAIN_FORMAT_0_PIXEL_FORMAT_T_Y10___V10U10_N444			_MK_ENUM_CONST(0x1f)
#define NVDLA_CDMA_D_DATAIN_FORMAT_0_PIXEL_FORMAT_T_Y12___U12V12_N444			_MK_ENUM_CONST(0x20)
#define NVDLA_CDMA_D_DATAIN_FORMAT_0_PIXEL_FORMAT_T_Y12___V12U12_N444			_MK_ENUM_CONST(0x21)
#define NVDLA_CDMA_D_DATAIN_FORMAT_0_PIXEL_FORMAT_T_Y16___U16V16_N444			_MK_ENUM_CONST(0x22)
#define NVDLA_CDMA_D_DATAIN_FORMAT_0_PIXEL_FORMAT_T_Y16___V16U16_N444			_MK_ENUM_CONST(0x23)
#define NVDLA_CDMA_D_DATAIN_FORMAT_0_PIXEL_MAPPING_SHIFT			_MK_SHIFT_CONST(16)
#define NVDLA_CDMA_D_DATAIN_FORMAT_0_PIXEL_MAPPING_FIELD			_MK_FIELD_CONST(0x1, NVDLA_CDMA_D_DATAIN_FORMAT_0_PIXEL_MAPPING_SHIFT)
#define NVDLA_CDMA_D_DATAIN_FORMAT_0_PIXEL_MAPPING_PITCH_LINEAR			_MK_ENUM_CONST(0x0)
#define NVDLA_CDMA_D_DATAIN_FORMAT_0_PIXEL_MAPPING_RESERVED_LINEAR			_MK_ENUM_CONST(0x1)
#define NVDLA_CDMA_D_DATAIN_FORMAT_0_PIXEL_SIGN_OVERRIDE_SHIFT			_MK_SHIFT_CONST(20)
#define NVDLA_CDMA_D_DATAIN_FORMAT_0_PIXEL_SIGN_OVERRIDE_FIELD			_MK_FIELD_CONST(0x1, NVDLA_CDMA_D_DATAIN_FORMAT_0_PIXEL_SIGN_OVERRIDE_SHIFT)
#define NVDLA_CDMA_D_DATAIN_FORMAT_0_PIXEL_SIGN_OVERRIDE_UNSIGNED_INT			_MK_ENUM_CONST(0x0)
#define NVDLA_CDMA_D_DATAIN_FORMAT_0_PIXEL_SIGN_OVERRIDE_SIGNED_INT			_MK_ENUM_CONST(0x1)


// Register NVDLA_CDMA_D_DATAIN_SIZE_0_0
#define NVDLA_CDMA_D_DATAIN_SIZE_0_0			_MK_ADDR_CONST(0x301c)
#define NVDLA_CDMA_D_DATAIN_SIZE_0_0_DATAIN_WIDTH_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CDMA_D_DATAIN_SIZE_0_0_DATAIN_WIDTH_FIELD			_MK_FIELD_CONST(0x1fff, NVDLA_CDMA_D_DATAIN_SIZE_0_0_DATAIN_WIDTH_SHIFT)
#define NVDLA_CDMA_D_DATAIN_SIZE_0_0_DATAIN_HEIGHT_SHIFT			_MK_SHIFT_CONST(16)
#define NVDLA_CDMA_D_DATAIN_SIZE_0_0_DATAIN_HEIGHT_FIELD			_MK_FIELD_CONST(0x1fff, NVDLA_CDMA_D_DATAIN_SIZE_0_0_DATAIN_HEIGHT_SHIFT)


// Register NVDLA_CDMA_D_DATAIN_SIZE_1_0
#define NVDLA_CDMA_D_DATAIN_SIZE_1_0			_MK_ADDR_CONST(0x3020)
#define NVDLA_CDMA_D_DATAIN_SIZE_1_0_DATAIN_CHANNEL_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CDMA_D_DATAIN_SIZE_1_0_DATAIN_CHANNEL_FIELD			_MK_FIELD_CONST(0x1fff, NVDLA_CDMA_D_DATAIN_SIZE_1_0_DATAIN_CHANNEL_SHIFT)


// Register NVDLA_CDMA_D_DATAIN_SIZE_EXT_0_0
#define NVDLA_CDMA_D_DATAIN_SIZE_EXT_0_0			_MK_ADDR_CONST(0x3024)
#define NVDLA_CDMA_D_DATAIN_SIZE_EXT_0_0_DATAIN_WIDTH_EXT_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CDMA_D_DATAIN_SIZE_EXT_0_0_DATAIN_WIDTH_EXT_FIELD			_MK_FIELD_CONST(0x1fff, NVDLA_CDMA_D_DATAIN_SIZE_EXT_0_0_DATAIN_WIDTH_EXT_SHIFT)
#define NVDLA_CDMA_D_DATAIN_SIZE_EXT_0_0_DATAIN_HEIGHT_EXT_SHIFT			_MK_SHIFT_CONST(16)
#define NVDLA_CDMA_D_DATAIN_SIZE_EXT_0_0_DATAIN_HEIGHT_EXT_FIELD			_MK_FIELD_CONST(0x1fff, NVDLA_CDMA_D_DATAIN_SIZE_EXT_0_0_DATAIN_HEIGHT_EXT_SHIFT)


// Register NVDLA_CDMA_D_PIXEL_OFFSET_0
#define NVDLA_CDMA_D_PIXEL_OFFSET_0			_MK_ADDR_CONST(0x3028)
#define NVDLA_CDMA_D_PIXEL_OFFSET_0_PIXEL_X_OFFSET_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CDMA_D_PIXEL_OFFSET_0_PIXEL_X_OFFSET_FIELD			_MK_FIELD_CONST(0x1f, NVDLA_CDMA_D_PIXEL_OFFSET_0_PIXEL_X_OFFSET_SHIFT)
#define NVDLA_CDMA_D_PIXEL_OFFSET_0_PIXEL_Y_OFFSET_SHIFT			_MK_SHIFT_CONST(16)
#define NVDLA_CDMA_D_PIXEL_OFFSET_0_PIXEL_Y_OFFSET_FIELD			_MK_FIELD_CONST(0x7, NVDLA_CDMA_D_PIXEL_OFFSET_0_PIXEL_Y_OFFSET_SHIFT)


// Register NVDLA_CDMA_D_DAIN_RAM_TYPE_0
#define NVDLA_CDMA_D_DAIN_RAM_TYPE_0			_MK_ADDR_CONST(0x302c)
#define NVDLA_CDMA_D_DAIN_RAM_TYPE_0_DATAIN_RAM_TYPE_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CDMA_D_DAIN_RAM_TYPE_0_DATAIN_RAM_TYPE_FIELD			_MK_FIELD_CONST(0x1, NVDLA_CDMA_D_DAIN_RAM_TYPE_0_DATAIN_RAM_TYPE_SHIFT)
#define NVDLA_CDMA_D_DAIN_RAM_TYPE_0_DATAIN_RAM_TYPE_CVIF			_MK_ENUM_CONST(0x0)
#define NVDLA_CDMA_D_DAIN_RAM_TYPE_0_DATAIN_RAM_TYPE_MCIF			_MK_ENUM_CONST(0x1)


// Register NVDLA_CDMA_D_DAIN_ADDR_HIGH_0_0
#define NVDLA_CDMA_D_DAIN_ADDR_HIGH_0_0			_MK_ADDR_CONST(0x3030)
#define NVDLA_CDMA_D_DAIN_ADDR_HIGH_0_0_DATAIN_ADDR_HIGH_0_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CDMA_D_DAIN_ADDR_HIGH_0_0_DATAIN_ADDR_HIGH_0_FIELD			_MK_FIELD_CONST(0xffffffff, NVDLA_CDMA_D_DAIN_ADDR_HIGH_0_0_DATAIN_ADDR_HIGH_0_SHIFT)


// Register NVDLA_CDMA_D_DAIN_ADDR_LOW_0_0
#define NVDLA_CDMA_D_DAIN_ADDR_LOW_0_0			_MK_ADDR_CONST(0x3034)
#define NVDLA_CDMA_D_DAIN_ADDR_LOW_0_0_DATAIN_ADDR_LOW_0_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CDMA_D_DAIN_ADDR_LOW_0_0_DATAIN_ADDR_LOW_0_FIELD			_MK_FIELD_CONST(0xffffffff, NVDLA_CDMA_D_DAIN_ADDR_LOW_0_0_DATAIN_ADDR_LOW_0_SHIFT)


// Register NVDLA_CDMA_D_DAIN_ADDR_HIGH_1_0
#define NVDLA_CDMA_D_DAIN_ADDR_HIGH_1_0			_MK_ADDR_CONST(0x3038)
#define NVDLA_CDMA_D_DAIN_ADDR_HIGH_1_0_DATAIN_ADDR_HIGH_1_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CDMA_D_DAIN_ADDR_HIGH_1_0_DATAIN_ADDR_HIGH_1_FIELD			_MK_FIELD_CONST(0xffffffff, NVDLA_CDMA_D_DAIN_ADDR_HIGH_1_0_DATAIN_ADDR_HIGH_1_SHIFT)


// Register NVDLA_CDMA_D_DAIN_ADDR_LOW_1_0
#define NVDLA_CDMA_D_DAIN_ADDR_LOW_1_0			_MK_ADDR_CONST(0x303c)
#define NVDLA_CDMA_D_DAIN_ADDR_LOW_1_0_DATAIN_ADDR_LOW_1_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CDMA_D_DAIN_ADDR_LOW_1_0_DATAIN_ADDR_LOW_1_FIELD			_MK_FIELD_CONST(0xffffffff, NVDLA_CDMA_D_DAIN_ADDR_LOW_1_0_DATAIN_ADDR_LOW_1_SHIFT)


// Register NVDLA_CDMA_D_LINE_STRIDE_0
#define NVDLA_CDMA_D_LINE_STRIDE_0			_MK_ADDR_CONST(0x3040)
#define NVDLA_CDMA_D_LINE_STRIDE_0_LINE_STRIDE_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CDMA_D_LINE_STRIDE_0_LINE_STRIDE_FIELD			_MK_FIELD_CONST(0xffffffff, NVDLA_CDMA_D_LINE_STRIDE_0_LINE_STRIDE_SHIFT)


// Register NVDLA_CDMA_D_LINE_UV_STRIDE_0
#define NVDLA_CDMA_D_LINE_UV_STRIDE_0			_MK_ADDR_CONST(0x3044)
#define NVDLA_CDMA_D_LINE_UV_STRIDE_0_UV_LINE_STRIDE_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CDMA_D_LINE_UV_STRIDE_0_UV_LINE_STRIDE_FIELD			_MK_FIELD_CONST(0xffffffff, NVDLA_CDMA_D_LINE_UV_STRIDE_0_UV_LINE_STRIDE_SHIFT)


// Register NVDLA_CDMA_D_SURF_STRIDE_0
#define NVDLA_CDMA_D_SURF_STRIDE_0			_MK_ADDR_CONST(0x3048)
#define NVDLA_CDMA_D_SURF_STRIDE_0_SURF_STRIDE_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CDMA_D_SURF_STRIDE_0_SURF_STRIDE_FIELD			_MK_FIELD_CONST(0xffffffff, NVDLA_CDMA_D_SURF_STRIDE_0_SURF_STRIDE_SHIFT)


// Register NVDLA_CDMA_D_DAIN_MAP_0
#define NVDLA_CDMA_D_DAIN_MAP_0			_MK_ADDR_CONST(0x304c)
#define NVDLA_CDMA_D_DAIN_MAP_0_LINE_PACKED_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CDMA_D_DAIN_MAP_0_LINE_PACKED_FIELD			_MK_FIELD_CONST(0x1, NVDLA_CDMA_D_DAIN_MAP_0_LINE_PACKED_SHIFT)
#define NVDLA_CDMA_D_DAIN_MAP_0_LINE_PACKED_FALSE			_MK_ENUM_CONST(0x0)
#define NVDLA_CDMA_D_DAIN_MAP_0_LINE_PACKED_TRUE			_MK_ENUM_CONST(0x1)
#define NVDLA_CDMA_D_DAIN_MAP_0_SURF_PACKED_SHIFT			_MK_SHIFT_CONST(16)
#define NVDLA_CDMA_D_DAIN_MAP_0_SURF_PACKED_FIELD			_MK_FIELD_CONST(0x1, NVDLA_CDMA_D_DAIN_MAP_0_SURF_PACKED_SHIFT)
#define NVDLA_CDMA_D_DAIN_MAP_0_SURF_PACKED_FALSE			_MK_ENUM_CONST(0x0)
#define NVDLA_CDMA_D_DAIN_MAP_0_SURF_PACKED_TRUE			_MK_ENUM_CONST(0x1)


// Register NVDLA_CDMA_D_RESERVED_X_CFG_0
#define NVDLA_CDMA_D_RESERVED_X_CFG_0			_MK_ADDR_CONST(0x3050)
#define NVDLA_CDMA_D_RESERVED_X_CFG_0_RSV_PER_LINE_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CDMA_D_RESERVED_X_CFG_0_RSV_PER_LINE_FIELD			_MK_FIELD_CONST(0x3ff, NVDLA_CDMA_D_RESERVED_X_CFG_0_RSV_PER_LINE_SHIFT)
#define NVDLA_CDMA_D_RESERVED_X_CFG_0_RSV_PER_UV_LINE_SHIFT			_MK_SHIFT_CONST(16)
#define NVDLA_CDMA_D_RESERVED_X_CFG_0_RSV_PER_UV_LINE_FIELD			_MK_FIELD_CONST(0x3ff, NVDLA_CDMA_D_RESERVED_X_CFG_0_RSV_PER_UV_LINE_SHIFT)


// Register NVDLA_CDMA_D_RESERVED_Y_CFG_0
#define NVDLA_CDMA_D_RESERVED_Y_CFG_0			_MK_ADDR_CONST(0x3054)
#define NVDLA_CDMA_D_RESERVED_Y_CFG_0_RSV_HEIGHT_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CDMA_D_RESERVED_Y_CFG_0_RSV_HEIGHT_FIELD			_MK_FIELD_CONST(0x7, NVDLA_CDMA_D_RESERVED_Y_CFG_0_RSV_HEIGHT_SHIFT)
#define NVDLA_CDMA_D_RESERVED_Y_CFG_0_RSV_Y_INDEX_SHIFT			_MK_SHIFT_CONST(16)
#define NVDLA_CDMA_D_RESERVED_Y_CFG_0_RSV_Y_INDEX_FIELD			_MK_FIELD_CONST(0x1f, NVDLA_CDMA_D_RESERVED_Y_CFG_0_RSV_Y_INDEX_SHIFT)


// Register NVDLA_CDMA_D_BATCH_NUMBER_0
#define NVDLA_CDMA_D_BATCH_NUMBER_0			_MK_ADDR_CONST(0x3058)
#define NVDLA_CDMA_D_BATCH_NUMBER_0_BATCHES_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CDMA_D_BATCH_NUMBER_0_BATCHES_FIELD			_MK_FIELD_CONST(0x1f, NVDLA_CDMA_D_BATCH_NUMBER_0_BATCHES_SHIFT)


// Register NVDLA_CDMA_D_BATCH_STRIDE_0
#define NVDLA_CDMA_D_BATCH_STRIDE_0			_MK_ADDR_CONST(0x305c)
#define NVDLA_CDMA_D_BATCH_STRIDE_0_BATCH_STRIDE_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CDMA_D_BATCH_STRIDE_0_BATCH_STRIDE_FIELD			_MK_FIELD_CONST(0xffffffff, NVDLA_CDMA_D_BATCH_STRIDE_0_BATCH_STRIDE_SHIFT)


// Register NVDLA_CDMA_D_ENTRY_PER_SLICE_0
#define NVDLA_CDMA_D_ENTRY_PER_SLICE_0			_MK_ADDR_CONST(0x3060)
#define NVDLA_CDMA_D_ENTRY_PER_SLICE_0_ENTRIES_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CDMA_D_ENTRY_PER_SLICE_0_ENTRIES_FIELD			_MK_FIELD_CONST(0x3fff, NVDLA_CDMA_D_ENTRY_PER_SLICE_0_ENTRIES_SHIFT)


// Register NVDLA_CDMA_D_FETCH_GRAIN_0
#define NVDLA_CDMA_D_FETCH_GRAIN_0			_MK_ADDR_CONST(0x3064)
#define NVDLA_CDMA_D_FETCH_GRAIN_0_GRAINS_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CDMA_D_FETCH_GRAIN_0_GRAINS_FIELD			_MK_FIELD_CONST(0xfff, NVDLA_CDMA_D_FETCH_GRAIN_0_GRAINS_SHIFT)


// Register NVDLA_CDMA_D_WEIGHT_FORMAT_0
#define NVDLA_CDMA_D_WEIGHT_FORMAT_0			_MK_ADDR_CONST(0x3068)
#define NVDLA_CDMA_D_WEIGHT_FORMAT_0_WEIGHT_FORMAT_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CDMA_D_WEIGHT_FORMAT_0_WEIGHT_FORMAT_FIELD			_MK_FIELD_CONST(0x1, NVDLA_CDMA_D_WEIGHT_FORMAT_0_WEIGHT_FORMAT_SHIFT)
#define NVDLA_CDMA_D_WEIGHT_FORMAT_0_WEIGHT_FORMAT_UNCOMPRESSED			_MK_ENUM_CONST(0x0)
#define NVDLA_CDMA_D_WEIGHT_FORMAT_0_WEIGHT_FORMAT_COMPRESSED			_MK_ENUM_CONST(0x1)


// Register NVDLA_CDMA_D_WEIGHT_SIZE_0_0
#define NVDLA_CDMA_D_WEIGHT_SIZE_0_0			_MK_ADDR_CONST(0x306c)
#define NVDLA_CDMA_D_WEIGHT_SIZE_0_0_BYTE_PER_KERNEL_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CDMA_D_WEIGHT_SIZE_0_0_BYTE_PER_KERNEL_FIELD			_MK_FIELD_CONST(0x3ffff, NVDLA_CDMA_D_WEIGHT_SIZE_0_0_BYTE_PER_KERNEL_SHIFT)


// Register NVDLA_CDMA_D_WEIGHT_SIZE_1_0
#define NVDLA_CDMA_D_WEIGHT_SIZE_1_0			_MK_ADDR_CONST(0x3070)
#define NVDLA_CDMA_D_WEIGHT_SIZE_1_0_WEIGHT_KERNEL_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CDMA_D_WEIGHT_SIZE_1_0_WEIGHT_KERNEL_FIELD			_MK_FIELD_CONST(0x1fff, NVDLA_CDMA_D_WEIGHT_SIZE_1_0_WEIGHT_KERNEL_SHIFT)


// Register NVDLA_CDMA_D_WEIGHT_RAM_TYPE_0
#define NVDLA_CDMA_D_WEIGHT_RAM_TYPE_0			_MK_ADDR_CONST(0x3074)
#define NVDLA_CDMA_D_WEIGHT_RAM_TYPE_0_WEIGHT_RAM_TYPE_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CDMA_D_WEIGHT_RAM_TYPE_0_WEIGHT_RAM_TYPE_FIELD			_MK_FIELD_CONST(0x1, NVDLA_CDMA_D_WEIGHT_RAM_TYPE_0_WEIGHT_RAM_TYPE_SHIFT)
#define NVDLA_CDMA_D_WEIGHT_RAM_TYPE_0_WEIGHT_RAM_TYPE_CVIF			_MK_ENUM_CONST(0x0)
#define NVDLA_CDMA_D_WEIGHT_RAM_TYPE_0_WEIGHT_RAM_TYPE_MCIF			_MK_ENUM_CONST(0x1)


// Register NVDLA_CDMA_D_WEIGHT_ADDR_HIGH_0
#define NVDLA_CDMA_D_WEIGHT_ADDR_HIGH_0			_MK_ADDR_CONST(0x3078)
#define NVDLA_CDMA_D_WEIGHT_ADDR_HIGH_0_WEIGHT_ADDR_HIGH_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CDMA_D_WEIGHT_ADDR_HIGH_0_WEIGHT_ADDR_HIGH_FIELD			_MK_FIELD_CONST(0xffffffff, NVDLA_CDMA_D_WEIGHT_ADDR_HIGH_0_WEIGHT_ADDR_HIGH_SHIFT)


// Register NVDLA_CDMA_D_WEIGHT_ADDR_LOW_0
#define NVDLA_CDMA_D_WEIGHT_ADDR_LOW_0			_MK_ADDR_CONST(0x307c)
#define NVDLA_CDMA_D_WEIGHT_ADDR_LOW_0_WEIGHT_ADDR_LOW_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CDMA_D_WEIGHT_ADDR_LOW_0_WEIGHT_ADDR_LOW_FIELD			_MK_FIELD_CONST(0xffffffff, NVDLA_CDMA_D_WEIGHT_ADDR_LOW_0_WEIGHT_ADDR_LOW_SHIFT)


// Register NVDLA_CDMA_D_WEIGHT_BYTES_0
#define NVDLA_CDMA_D_WEIGHT_BYTES_0			_MK_ADDR_CONST(0x3080)
#define NVDLA_CDMA_D_WEIGHT_BYTES_0_WEIGHT_BYTES_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CDMA_D_WEIGHT_BYTES_0_WEIGHT_BYTES_FIELD			_MK_FIELD_CONST(0xffffffff, NVDLA_CDMA_D_WEIGHT_BYTES_0_WEIGHT_BYTES_SHIFT)


// Register NVDLA_CDMA_D_WGS_ADDR_HIGH_0
#define NVDLA_CDMA_D_WGS_ADDR_HIGH_0			_MK_ADDR_CONST(0x3084)
#define NVDLA_CDMA_D_WGS_ADDR_HIGH_0_WGS_ADDR_HIGH_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CDMA_D_WGS_ADDR_HIGH_0_WGS_ADDR_HIGH_FIELD			_MK_FIELD_CONST(0xffffffff, NVDLA_CDMA_D_WGS_ADDR_HIGH_0_WGS_ADDR_HIGH_SHIFT)


// Register NVDLA_CDMA_D_WGS_ADDR_LOW_0
#define NVDLA_CDMA_D_WGS_ADDR_LOW_0			_MK_ADDR_CONST(0x3088)
#define NVDLA_CDMA_D_WGS_ADDR_LOW_0_WGS_ADDR_LOW_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CDMA_D_WGS_ADDR_LOW_0_WGS_ADDR_LOW_FIELD			_MK_FIELD_CONST(0xffffffff, NVDLA_CDMA_D_WGS_ADDR_LOW_0_WGS_ADDR_LOW_SHIFT)


// Register NVDLA_CDMA_D_WMB_ADDR_HIGH_0
#define NVDLA_CDMA_D_WMB_ADDR_HIGH_0			_MK_ADDR_CONST(0x308c)
#define NVDLA_CDMA_D_WMB_ADDR_HIGH_0_WMB_ADDR_HIGH_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CDMA_D_WMB_ADDR_HIGH_0_WMB_ADDR_HIGH_FIELD			_MK_FIELD_CONST(0xffffffff, NVDLA_CDMA_D_WMB_ADDR_HIGH_0_WMB_ADDR_HIGH_SHIFT)


// Register NVDLA_CDMA_D_WMB_ADDR_LOW_0
#define NVDLA_CDMA_D_WMB_ADDR_LOW_0			_MK_ADDR_CONST(0x3090)
#define NVDLA_CDMA_D_WMB_ADDR_LOW_0_WMB_ADDR_LOW_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CDMA_D_WMB_ADDR_LOW_0_WMB_ADDR_LOW_FIELD			_MK_FIELD_CONST(0xffffffff, NVDLA_CDMA_D_WMB_ADDR_LOW_0_WMB_ADDR_LOW_SHIFT)


// Register NVDLA_CDMA_D_WMB_BYTES_0
#define NVDLA_CDMA_D_WMB_BYTES_0			_MK_ADDR_CONST(0x3094)
#define NVDLA_CDMA_D_WMB_BYTES_0_WMB_BYTES_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CDMA_D_WMB_BYTES_0_WMB_BYTES_FIELD			_MK_FIELD_CONST(0xfffffff, NVDLA_CDMA_D_WMB_BYTES_0_WMB_BYTES_SHIFT)


// Register NVDLA_CDMA_D_MEAN_FORMAT_0
#define NVDLA_CDMA_D_MEAN_FORMAT_0			_MK_ADDR_CONST(0x3098)
#define NVDLA_CDMA_D_MEAN_FORMAT_0_MEAN_FORMAT_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CDMA_D_MEAN_FORMAT_0_MEAN_FORMAT_FIELD			_MK_FIELD_CONST(0x1, NVDLA_CDMA_D_MEAN_FORMAT_0_MEAN_FORMAT_SHIFT)
#define NVDLA_CDMA_D_MEAN_FORMAT_0_MEAN_FORMAT_DISABLE			_MK_ENUM_CONST(0x0)
#define NVDLA_CDMA_D_MEAN_FORMAT_0_MEAN_FORMAT_ENABLE			_MK_ENUM_CONST(0x1)


// Register NVDLA_CDMA_D_MEAN_GLOBAL_0_0
#define NVDLA_CDMA_D_MEAN_GLOBAL_0_0			_MK_ADDR_CONST(0x309c)
#define NVDLA_CDMA_D_MEAN_GLOBAL_0_0_MEAN_RY_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CDMA_D_MEAN_GLOBAL_0_0_MEAN_RY_FIELD			_MK_FIELD_CONST(0xffff, NVDLA_CDMA_D_MEAN_GLOBAL_0_0_MEAN_RY_SHIFT)
#define NVDLA_CDMA_D_MEAN_GLOBAL_0_0_MEAN_GU_SHIFT			_MK_SHIFT_CONST(16)
#define NVDLA_CDMA_D_MEAN_GLOBAL_0_0_MEAN_GU_FIELD			_MK_FIELD_CONST(0xffff, NVDLA_CDMA_D_MEAN_GLOBAL_0_0_MEAN_GU_SHIFT)


// Register NVDLA_CDMA_D_MEAN_GLOBAL_1_0
#define NVDLA_CDMA_D_MEAN_GLOBAL_1_0			_MK_ADDR_CONST(0x30a0)
#define NVDLA_CDMA_D_MEAN_GLOBAL_1_0_MEAN_BV_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CDMA_D_MEAN_GLOBAL_1_0_MEAN_BV_FIELD			_MK_FIELD_CONST(0xffff, NVDLA_CDMA_D_MEAN_GLOBAL_1_0_MEAN_BV_SHIFT)
#define NVDLA_CDMA_D_MEAN_GLOBAL_1_0_MEAN_AX_SHIFT			_MK_SHIFT_CONST(16)
#define NVDLA_CDMA_D_MEAN_GLOBAL_1_0_MEAN_AX_FIELD			_MK_FIELD_CONST(0xffff, NVDLA_CDMA_D_MEAN_GLOBAL_1_0_MEAN_AX_SHIFT)


// Register NVDLA_CDMA_D_CVT_CFG_0
#define NVDLA_CDMA_D_CVT_CFG_0			_MK_ADDR_CONST(0x30a4)
#define NVDLA_CDMA_D_CVT_CFG_0_CVT_EN_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CDMA_D_CVT_CFG_0_CVT_EN_FIELD			_MK_FIELD_CONST(0x1, NVDLA_CDMA_D_CVT_CFG_0_CVT_EN_SHIFT)
#define NVDLA_CDMA_D_CVT_CFG_0_CVT_EN_DISABLE			_MK_ENUM_CONST(0x0)
#define NVDLA_CDMA_D_CVT_CFG_0_CVT_EN_ENABLE			_MK_ENUM_CONST(0x1)
#define NVDLA_CDMA_D_CVT_CFG_0_CVT_TRUNCATE_SHIFT			_MK_SHIFT_CONST(4)
#define NVDLA_CDMA_D_CVT_CFG_0_CVT_TRUNCATE_FIELD			_MK_FIELD_CONST(0x3f, NVDLA_CDMA_D_CVT_CFG_0_CVT_TRUNCATE_SHIFT)


// Register NVDLA_CDMA_D_CVT_OFFSET_0
#define NVDLA_CDMA_D_CVT_OFFSET_0			_MK_ADDR_CONST(0x30a8)
#define NVDLA_CDMA_D_CVT_OFFSET_0_CVT_OFFSET_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CDMA_D_CVT_OFFSET_0_CVT_OFFSET_FIELD			_MK_FIELD_CONST(0xffff, NVDLA_CDMA_D_CVT_OFFSET_0_CVT_OFFSET_SHIFT)


// Register NVDLA_CDMA_D_CVT_SCALE_0
#define NVDLA_CDMA_D_CVT_SCALE_0			_MK_ADDR_CONST(0x30ac)
#define NVDLA_CDMA_D_CVT_SCALE_0_CVT_SCALE_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CDMA_D_CVT_SCALE_0_CVT_SCALE_FIELD			_MK_FIELD_CONST(0xffff, NVDLA_CDMA_D_CVT_SCALE_0_CVT_SCALE_SHIFT)


// Register NVDLA_CDMA_D_CONV_STRIDE_0
#define NVDLA_CDMA_D_CONV_STRIDE_0			_MK_ADDR_CONST(0x30b0)
#define NVDLA_CDMA_D_CONV_STRIDE_0_CONV_X_STRIDE_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CDMA_D_CONV_STRIDE_0_CONV_X_STRIDE_FIELD			_MK_FIELD_CONST(0x7, NVDLA_CDMA_D_CONV_STRIDE_0_CONV_X_STRIDE_SHIFT)
#define NVDLA_CDMA_D_CONV_STRIDE_0_CONV_Y_STRIDE_SHIFT			_MK_SHIFT_CONST(16)
#define NVDLA_CDMA_D_CONV_STRIDE_0_CONV_Y_STRIDE_FIELD			_MK_FIELD_CONST(0x7, NVDLA_CDMA_D_CONV_STRIDE_0_CONV_Y_STRIDE_SHIFT)


// Register NVDLA_CDMA_D_ZERO_PADDING_0
#define NVDLA_CDMA_D_ZERO_PADDING_0			_MK_ADDR_CONST(0x30b4)
#define NVDLA_CDMA_D_ZERO_PADDING_0_PAD_LEFT_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CDMA_D_ZERO_PADDING_0_PAD_LEFT_FIELD			_MK_FIELD_CONST(0x1f, NVDLA_CDMA_D_ZERO_PADDING_0_PAD_LEFT_SHIFT)
#define NVDLA_CDMA_D_ZERO_PADDING_0_PAD_RIGHT_SHIFT			_MK_SHIFT_CONST(8)
#define NVDLA_CDMA_D_ZERO_PADDING_0_PAD_RIGHT_FIELD			_MK_FIELD_CONST(0x3f, NVDLA_CDMA_D_ZERO_PADDING_0_PAD_RIGHT_SHIFT)
#define NVDLA_CDMA_D_ZERO_PADDING_0_PAD_TOP_SHIFT			_MK_SHIFT_CONST(16)
#define NVDLA_CDMA_D_ZERO_PADDING_0_PAD_TOP_FIELD			_MK_FIELD_CONST(0x1f, NVDLA_CDMA_D_ZERO_PADDING_0_PAD_TOP_SHIFT)
#define NVDLA_CDMA_D_ZERO_PADDING_0_PAD_BOTTOM_SHIFT			_MK_SHIFT_CONST(24)
#define NVDLA_CDMA_D_ZERO_PADDING_0_PAD_BOTTOM_FIELD			_MK_FIELD_CONST(0x3f, NVDLA_CDMA_D_ZERO_PADDING_0_PAD_BOTTOM_SHIFT)


// Register NVDLA_CDMA_D_ZERO_PADDING_VALUE_0
#define NVDLA_CDMA_D_ZERO_PADDING_VALUE_0			_MK_ADDR_CONST(0x30b8)
#define NVDLA_CDMA_D_ZERO_PADDING_VALUE_0_PAD_VALUE_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CDMA_D_ZERO_PADDING_VALUE_0_PAD_VALUE_FIELD			_MK_FIELD_CONST(0xffff, NVDLA_CDMA_D_ZERO_PADDING_VALUE_0_PAD_VALUE_SHIFT)


// Register NVDLA_CDMA_D_BANK_0
#define NVDLA_CDMA_D_BANK_0			_MK_ADDR_CONST(0x30bc)
#define NVDLA_CDMA_D_BANK_0_DATA_BANK_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CDMA_D_BANK_0_DATA_BANK_FIELD			_MK_FIELD_CONST(0x1f, NVDLA_CDMA_D_BANK_0_DATA_BANK_SHIFT)
#define NVDLA_CDMA_D_BANK_0_WEIGHT_BANK_SHIFT			_MK_SHIFT_CONST(16)
#define NVDLA_CDMA_D_BANK_0_WEIGHT_BANK_FIELD			_MK_FIELD_CONST(0x1f, NVDLA_CDMA_D_BANK_0_WEIGHT_BANK_SHIFT)


// Register NVDLA_CDMA_D_NAN_FLUSH_TO_ZERO_0
#define NVDLA_CDMA_D_NAN_FLUSH_TO_ZERO_0			_MK_ADDR_CONST(0x30c0)
#define NVDLA_CDMA_D_NAN_FLUSH_TO_ZERO_0_NAN_TO_ZERO_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CDMA_D_NAN_FLUSH_TO_ZERO_0_NAN_TO_ZERO_FIELD			_MK_FIELD_CONST(0x1, NVDLA_CDMA_D_NAN_FLUSH_TO_ZERO_0_NAN_TO_ZERO_SHIFT)
#define NVDLA_CDMA_D_NAN_FLUSH_TO_ZERO_0_NAN_TO_ZERO_DISABLE			_MK_ENUM_CONST(0x0)
#define NVDLA_CDMA_D_NAN_FLUSH_TO_ZERO_0_NAN_TO_ZERO_ENABLE			_MK_ENUM_CONST(0x1)


// Register NVDLA_CDMA_D_NAN_INPUT_DATA_NUM_0
#define NVDLA_CDMA_D_NAN_INPUT_DATA_NUM_0			_MK_ADDR_CONST(0x30c4)
#define NVDLA_CDMA_D_NAN_INPUT_DATA_NUM_0_NAN_DATA_NUM_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CDMA_D_NAN_INPUT_DATA_NUM_0_NAN_DATA_NUM_FIELD			_MK_FIELD_CONST(0xffffffff, NVDLA_CDMA_D_NAN_INPUT_DATA_NUM_0_NAN_DATA_NUM_SHIFT)


// Register NVDLA_CDMA_D_NAN_INPUT_WEIGHT_NUM_0
#define NVDLA_CDMA_D_NAN_INPUT_WEIGHT_NUM_0			_MK_ADDR_CONST(0x30c8)
#define NVDLA_CDMA_D_NAN_INPUT_WEIGHT_NUM_0_NAN_WEIGHT_NUM_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CDMA_D_NAN_INPUT_WEIGHT_NUM_0_NAN_WEIGHT_NUM_FIELD			_MK_FIELD_CONST(0xffffffff, NVDLA_CDMA_D_NAN_INPUT_WEIGHT_NUM_0_NAN_WEIGHT_NUM_SHIFT)


// Register NVDLA_CDMA_D_INF_INPUT_DATA_NUM_0
#define NVDLA_CDMA_D_INF_INPUT_DATA_NUM_0			_MK_ADDR_CONST(0x30cc)
#define NVDLA_CDMA_D_INF_INPUT_DATA_NUM_0_INF_DATA_NUM_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CDMA_D_INF_INPUT_DATA_NUM_0_INF_DATA_NUM_FIELD			_MK_FIELD_CONST(0xffffffff, NVDLA_CDMA_D_INF_INPUT_DATA_NUM_0_INF_DATA_NUM_SHIFT)


// Register NVDLA_CDMA_D_INF_INPUT_WEIGHT_NUM_0
#define NVDLA_CDMA_D_INF_INPUT_WEIGHT_NUM_0			_MK_ADDR_CONST(0x30d0)
#define NVDLA_CDMA_D_INF_INPUT_WEIGHT_NUM_0_INF_WEIGHT_NUM_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CDMA_D_INF_INPUT_WEIGHT_NUM_0_INF_WEIGHT_NUM_FIELD			_MK_FIELD_CONST(0xffffffff, NVDLA_CDMA_D_INF_INPUT_WEIGHT_NUM_0_INF_WEIGHT_NUM_SHIFT)


// Register NVDLA_CDMA_D_PERF_ENABLE_0
#define NVDLA_CDMA_D_PERF_ENABLE_0			_MK_ADDR_CONST(0x30d4)
#define NVDLA_CDMA_D_PERF_ENABLE_0_DMA_EN_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CDMA_D_PERF_ENABLE_0_DMA_EN_FIELD			_MK_FIELD_CONST(0x1, NVDLA_CDMA_D_PERF_ENABLE_0_DMA_EN_SHIFT)


// Register NVDLA_CDMA_D_PERF_DAT_READ_STALL_0
#define NVDLA_CDMA_D_PERF_DAT_READ_STALL_0			_MK_ADDR_CONST(0x30d8)
#define NVDLA_CDMA_D_PERF_DAT_READ_STALL_0_DAT_RD_STALL_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CDMA_D_PERF_DAT_READ_STALL_0_DAT_RD_STALL_FIELD			_MK_FIELD_CONST(0xffffffff, NVDLA_CDMA_D_PERF_DAT_READ_STALL_0_DAT_RD_STALL_SHIFT)


// Register NVDLA_CDMA_D_PERF_WT_READ_STALL_0
#define NVDLA_CDMA_D_PERF_WT_READ_STALL_0			_MK_ADDR_CONST(0x30dc)
#define NVDLA_CDMA_D_PERF_WT_READ_STALL_0_WT_RD_STALL_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CDMA_D_PERF_WT_READ_STALL_0_WT_RD_STALL_FIELD			_MK_FIELD_CONST(0xffffffff, NVDLA_CDMA_D_PERF_WT_READ_STALL_0_WT_RD_STALL_SHIFT)


// Register NVDLA_CDMA_D_PERF_DAT_READ_LATENCY_0
#define NVDLA_CDMA_D_PERF_DAT_READ_LATENCY_0			_MK_ADDR_CONST(0x30e0)
#define NVDLA_CDMA_D_PERF_DAT_READ_LATENCY_0_DAT_RD_LATENCY_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CDMA_D_PERF_DAT_READ_LATENCY_0_DAT_RD_LATENCY_FIELD			_MK_FIELD_CONST(0xffffffff, NVDLA_CDMA_D_PERF_DAT_READ_LATENCY_0_DAT_RD_LATENCY_SHIFT)


// Register NVDLA_CDMA_D_PERF_WT_READ_LATENCY_0
#define NVDLA_CDMA_D_PERF_WT_READ_LATENCY_0			_MK_ADDR_CONST(0x30e4)
#define NVDLA_CDMA_D_PERF_WT_READ_LATENCY_0_WT_RD_LATENCY_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CDMA_D_PERF_WT_READ_LATENCY_0_WT_RD_LATENCY_FIELD			_MK_FIELD_CONST(0xffffffff, NVDLA_CDMA_D_PERF_WT_READ_LATENCY_0_WT_RD_LATENCY_SHIFT)


// Register NVDLA_CDMA_D_CYA_0
#define NVDLA_CDMA_D_CYA_0			_MK_ADDR_CONST(0x30e8)
#define NVDLA_CDMA_D_CYA_0_CYA_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CDMA_D_CYA_0_CYA_FIELD			_MK_FIELD_CONST(0xffffffff, NVDLA_CDMA_D_CYA_0_CYA_SHIFT)



// To satisfy various compilers and platforms,
// we let users control the types and syntax of certain constants, using macros.
#ifndef _MK_SHIFT_CONST
  #define _MK_SHIFT_CONST(_constant_) _constant_
#endif
#ifndef _MK_MASK_CONST
  #define _MK_MASK_CONST(_constant_) _constant_
#endif
#ifndef _MK_ENUM_CONST
  #define _MK_ENUM_CONST(_constant_) (_constant_ ## UL)
#endif
#ifndef _MK_ADDR_CONST
  #define _MK_ADDR_CONST(_constant_) _constant_
#endif
#ifndef _MK_FIELD_CONST
  #define _MK_FIELD_CONST(_mask_, _shift_) (_MK_MASK_CONST(_mask_) << _MK_SHIFT_CONST(_shift_))
#endif



//
// ADDRESS SPACES
//

#define BASE_ADDRESS_NVDLA_CDMA	0x3000
