// Register NVDLA_SDP_S_STATUS_0
#define NVDLA_SDP_S_STATUS_0			_MK_ADDR_CONST(0x9000)
#define NVDLA_SDP_S_STATUS_0_STATUS_0_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_SDP_S_STATUS_0_STATUS_0_FIELD			_MK_FIELD_CONST(0x3, NVDLA_SDP_S_STATUS_0_STATUS_0_SHIFT)
#define NVDLA_SDP_S_STATUS_0_STATUS_0_IDLE			_MK_ENUM_CONST(0x0)
#define NVDLA_SDP_S_STATUS_0_STATUS_0_RUNNING			_MK_ENUM_CONST(0x1)
#define NVDLA_SDP_S_STATUS_0_STATUS_0_PENDING			_MK_ENUM_CONST(0x2)
#define NVDLA_SDP_S_STATUS_0_STATUS_1_SHIFT			_MK_SHIFT_CONST(16)
#define NVDLA_SDP_S_STATUS_0_STATUS_1_FIELD			_MK_FIELD_CONST(0x3, NVDLA_SDP_S_STATUS_0_STATUS_1_SHIFT)
#define NVDLA_SDP_S_STATUS_0_STATUS_1_IDLE			_MK_ENUM_CONST(0x0)
#define NVDLA_SDP_S_STATUS_0_STATUS_1_RUNNING			_MK_ENUM_CONST(0x1)
#define NVDLA_SDP_S_STATUS_0_STATUS_1_PENDING			_MK_ENUM_CONST(0x2)


// Register NVDLA_SDP_S_POINTER_0
#define NVDLA_SDP_S_POINTER_0			_MK_ADDR_CONST(0x9004)
#define NVDLA_SDP_S_POINTER_0_PRODUCER_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_SDP_S_POINTER_0_PRODUCER_FIELD			_MK_FIELD_CONST(0x1, NVDLA_SDP_S_POINTER_0_PRODUCER_SHIFT)
#define NVDLA_SDP_S_POINTER_0_PRODUCER_GROUP_0			_MK_ENUM_CONST(0x0)
#define NVDLA_SDP_S_POINTER_0_PRODUCER_GROUP_1			_MK_ENUM_CONST(0x1)
#define NVDLA_SDP_S_POINTER_0_CONSUMER_SHIFT			_MK_SHIFT_CONST(16)
#define NVDLA_SDP_S_POINTER_0_CONSUMER_FIELD			_MK_FIELD_CONST(0x1, NVDLA_SDP_S_POINTER_0_CONSUMER_SHIFT)
#define NVDLA_SDP_S_POINTER_0_CONSUMER_GROUP_0			_MK_ENUM_CONST(0x0)
#define NVDLA_SDP_S_POINTER_0_CONSUMER_GROUP_1			_MK_ENUM_CONST(0x1)


// Register NVDLA_SDP_S_LUT_ACCESS_CFG_0
#define NVDLA_SDP_S_LUT_ACCESS_CFG_0			_MK_ADDR_CONST(0x9008)
#define NVDLA_SDP_S_LUT_ACCESS_CFG_0_LUT_ADDR_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_SDP_S_LUT_ACCESS_CFG_0_LUT_ADDR_FIELD			_MK_FIELD_CONST(0x3ff, NVDLA_SDP_S_LUT_ACCESS_CFG_0_LUT_ADDR_SHIFT)
#define NVDLA_SDP_S_LUT_ACCESS_CFG_0_LUT_TABLE_ID_SHIFT			_MK_SHIFT_CONST(16)
#define NVDLA_SDP_S_LUT_ACCESS_CFG_0_LUT_TABLE_ID_FIELD			_MK_FIELD_CONST(0x1, NVDLA_SDP_S_LUT_ACCESS_CFG_0_LUT_TABLE_ID_SHIFT)
#define NVDLA_SDP_S_LUT_ACCESS_CFG_0_LUT_TABLE_ID_LE			_MK_ENUM_CONST(0x0)
#define NVDLA_SDP_S_LUT_ACCESS_CFG_0_LUT_TABLE_ID_LO			_MK_ENUM_CONST(0x1)
#define NVDLA_SDP_S_LUT_ACCESS_CFG_0_LUT_ACCESS_TYPE_SHIFT			_MK_SHIFT_CONST(17)
#define NVDLA_SDP_S_LUT_ACCESS_CFG_0_LUT_ACCESS_TYPE_FIELD			_MK_FIELD_CONST(0x1, NVDLA_SDP_S_LUT_ACCESS_CFG_0_LUT_ACCESS_TYPE_SHIFT)
#define NVDLA_SDP_S_LUT_ACCESS_CFG_0_LUT_ACCESS_TYPE_READ			_MK_ENUM_CONST(0x0)
#define NVDLA_SDP_S_LUT_ACCESS_CFG_0_LUT_ACCESS_TYPE_WRITE			_MK_ENUM_CONST(0x1)


// Register NVDLA_SDP_S_LUT_ACCESS_DATA_0
#define NVDLA_SDP_S_LUT_ACCESS_DATA_0			_MK_ADDR_CONST(0x900c)
#define NVDLA_SDP_S_LUT_ACCESS_DATA_0_LUT_DATA_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_SDP_S_LUT_ACCESS_DATA_0_LUT_DATA_FIELD			_MK_FIELD_CONST(0xffff, NVDLA_SDP_S_LUT_ACCESS_DATA_0_LUT_DATA_SHIFT)


// Register NVDLA_SDP_S_LUT_CFG_0
#define NVDLA_SDP_S_LUT_CFG_0			_MK_ADDR_CONST(0x9010)
#define NVDLA_SDP_S_LUT_CFG_0_LUT_LE_FUNCTION_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_SDP_S_LUT_CFG_0_LUT_LE_FUNCTION_FIELD			_MK_FIELD_CONST(0x1, NVDLA_SDP_S_LUT_CFG_0_LUT_LE_FUNCTION_SHIFT)
#define NVDLA_SDP_S_LUT_CFG_0_LUT_LE_FUNCTION_EXPONENT			_MK_ENUM_CONST(0x0)
#define NVDLA_SDP_S_LUT_CFG_0_LUT_LE_FUNCTION_LINEAR			_MK_ENUM_CONST(0x1)
#define NVDLA_SDP_S_LUT_CFG_0_LUT_UFLOW_PRIORITY_SHIFT			_MK_SHIFT_CONST(4)
#define NVDLA_SDP_S_LUT_CFG_0_LUT_UFLOW_PRIORITY_FIELD			_MK_FIELD_CONST(0x1, NVDLA_SDP_S_LUT_CFG_0_LUT_UFLOW_PRIORITY_SHIFT)
#define NVDLA_SDP_S_LUT_CFG_0_LUT_UFLOW_PRIORITY_LE			_MK_ENUM_CONST(0x0)
#define NVDLA_SDP_S_LUT_CFG_0_LUT_UFLOW_PRIORITY_LO			_MK_ENUM_CONST(0x1)
#define NVDLA_SDP_S_LUT_CFG_0_LUT_OFLOW_PRIORITY_SHIFT			_MK_SHIFT_CONST(5)
#define NVDLA_SDP_S_LUT_CFG_0_LUT_OFLOW_PRIORITY_FIELD			_MK_FIELD_CONST(0x1, NVDLA_SDP_S_LUT_CFG_0_LUT_OFLOW_PRIORITY_SHIFT)
#define NVDLA_SDP_S_LUT_CFG_0_LUT_OFLOW_PRIORITY_LE			_MK_ENUM_CONST(0x0)
#define NVDLA_SDP_S_LUT_CFG_0_LUT_OFLOW_PRIORITY_LO			_MK_ENUM_CONST(0x1)
#define NVDLA_SDP_S_LUT_CFG_0_LUT_HYBRID_PRIORITY_SHIFT			_MK_SHIFT_CONST(6)
#define NVDLA_SDP_S_LUT_CFG_0_LUT_HYBRID_PRIORITY_FIELD			_MK_FIELD_CONST(0x1, NVDLA_SDP_S_LUT_CFG_0_LUT_HYBRID_PRIORITY_SHIFT)
#define NVDLA_SDP_S_LUT_CFG_0_LUT_HYBRID_PRIORITY_LE			_MK_ENUM_CONST(0x0)
#define NVDLA_SDP_S_LUT_CFG_0_LUT_HYBRID_PRIORITY_LO			_MK_ENUM_CONST(0x1)


// Register NVDLA_SDP_S_LUT_INFO_0
#define NVDLA_SDP_S_LUT_INFO_0			_MK_ADDR_CONST(0x9014)
#define NVDLA_SDP_S_LUT_INFO_0_LUT_LE_INDEX_OFFSET_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_SDP_S_LUT_INFO_0_LUT_LE_INDEX_OFFSET_FIELD			_MK_FIELD_CONST(0xff, NVDLA_SDP_S_LUT_INFO_0_LUT_LE_INDEX_OFFSET_SHIFT)
#define NVDLA_SDP_S_LUT_INFO_0_LUT_LE_INDEX_SELECT_SHIFT			_MK_SHIFT_CONST(8)
#define NVDLA_SDP_S_LUT_INFO_0_LUT_LE_INDEX_SELECT_FIELD			_MK_FIELD_CONST(0xff, NVDLA_SDP_S_LUT_INFO_0_LUT_LE_INDEX_SELECT_SHIFT)
#define NVDLA_SDP_S_LUT_INFO_0_LUT_LO_INDEX_SELECT_SHIFT			_MK_SHIFT_CONST(16)
#define NVDLA_SDP_S_LUT_INFO_0_LUT_LO_INDEX_SELECT_FIELD			_MK_FIELD_CONST(0xff, NVDLA_SDP_S_LUT_INFO_0_LUT_LO_INDEX_SELECT_SHIFT)


// Register NVDLA_SDP_S_LUT_LE_START_0
#define NVDLA_SDP_S_LUT_LE_START_0			_MK_ADDR_CONST(0x9018)
#define NVDLA_SDP_S_LUT_LE_START_0_LUT_LE_START_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_SDP_S_LUT_LE_START_0_LUT_LE_START_FIELD			_MK_FIELD_CONST(0xffffffff, NVDLA_SDP_S_LUT_LE_START_0_LUT_LE_START_SHIFT)


// Register NVDLA_SDP_S_LUT_LE_END_0
#define NVDLA_SDP_S_LUT_LE_END_0			_MK_ADDR_CONST(0x901c)
#define NVDLA_SDP_S_LUT_LE_END_0_LUT_LE_END_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_SDP_S_LUT_LE_END_0_LUT_LE_END_FIELD			_MK_FIELD_CONST(0xffffffff, NVDLA_SDP_S_LUT_LE_END_0_LUT_LE_END_SHIFT)


// Register NVDLA_SDP_S_LUT_LO_START_0
#define NVDLA_SDP_S_LUT_LO_START_0			_MK_ADDR_CONST(0x9020)
#define NVDLA_SDP_S_LUT_LO_START_0_LUT_LO_START_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_SDP_S_LUT_LO_START_0_LUT_LO_START_FIELD			_MK_FIELD_CONST(0xffffffff, NVDLA_SDP_S_LUT_LO_START_0_LUT_LO_START_SHIFT)


// Register NVDLA_SDP_S_LUT_LO_END_0
#define NVDLA_SDP_S_LUT_LO_END_0			_MK_ADDR_CONST(0x9024)
#define NVDLA_SDP_S_LUT_LO_END_0_LUT_LO_END_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_SDP_S_LUT_LO_END_0_LUT_LO_END_FIELD			_MK_FIELD_CONST(0xffffffff, NVDLA_SDP_S_LUT_LO_END_0_LUT_LO_END_SHIFT)


// Register NVDLA_SDP_S_LUT_LE_SLOPE_SCALE_0
#define NVDLA_SDP_S_LUT_LE_SLOPE_SCALE_0			_MK_ADDR_CONST(0x9028)
#define NVDLA_SDP_S_LUT_LE_SLOPE_SCALE_0_LUT_LE_SLOPE_UFLOW_SCALE_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_SDP_S_LUT_LE_SLOPE_SCALE_0_LUT_LE_SLOPE_UFLOW_SCALE_FIELD			_MK_FIELD_CONST(0xffff, NVDLA_SDP_S_LUT_LE_SLOPE_SCALE_0_LUT_LE_SLOPE_UFLOW_SCALE_SHIFT)
#define NVDLA_SDP_S_LUT_LE_SLOPE_SCALE_0_LUT_LE_SLOPE_OFLOW_SCALE_SHIFT			_MK_SHIFT_CONST(16)
#define NVDLA_SDP_S_LUT_LE_SLOPE_SCALE_0_LUT_LE_SLOPE_OFLOW_SCALE_FIELD			_MK_FIELD_CONST(0xffff, NVDLA_SDP_S_LUT_LE_SLOPE_SCALE_0_LUT_LE_SLOPE_OFLOW_SCALE_SHIFT)


// Register NVDLA_SDP_S_LUT_LE_SLOPE_SHIFT_0
#define NVDLA_SDP_S_LUT_LE_SLOPE_SHIFT_0			_MK_ADDR_CONST(0x902c)
#define NVDLA_SDP_S_LUT_LE_SLOPE_SHIFT_0_LUT_LE_SLOPE_UFLOW_SHIFT_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_SDP_S_LUT_LE_SLOPE_SHIFT_0_LUT_LE_SLOPE_UFLOW_SHIFT_FIELD			_MK_FIELD_CONST(0x1f, NVDLA_SDP_S_LUT_LE_SLOPE_SHIFT_0_LUT_LE_SLOPE_UFLOW_SHIFT_SHIFT)
#define NVDLA_SDP_S_LUT_LE_SLOPE_SHIFT_0_LUT_LE_SLOPE_OFLOW_SHIFT_SHIFT			_MK_SHIFT_CONST(5)
#define NVDLA_SDP_S_LUT_LE_SLOPE_SHIFT_0_LUT_LE_SLOPE_OFLOW_SHIFT_FIELD			_MK_FIELD_CONST(0x1f, NVDLA_SDP_S_LUT_LE_SLOPE_SHIFT_0_LUT_LE_SLOPE_OFLOW_SHIFT_SHIFT)


// Register NVDLA_SDP_S_LUT_LO_SLOPE_SCALE_0
#define NVDLA_SDP_S_LUT_LO_SLOPE_SCALE_0			_MK_ADDR_CONST(0x9030)
#define NVDLA_SDP_S_LUT_LO_SLOPE_SCALE_0_LUT_LO_SLOPE_UFLOW_SCALE_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_SDP_S_LUT_LO_SLOPE_SCALE_0_LUT_LO_SLOPE_UFLOW_SCALE_FIELD			_MK_FIELD_CONST(0xffff, NVDLA_SDP_S_LUT_LO_SLOPE_SCALE_0_LUT_LO_SLOPE_UFLOW_SCALE_SHIFT)
#define NVDLA_SDP_S_LUT_LO_SLOPE_SCALE_0_LUT_LO_SLOPE_OFLOW_SCALE_SHIFT			_MK_SHIFT_CONST(16)
#define NVDLA_SDP_S_LUT_LO_SLOPE_SCALE_0_LUT_LO_SLOPE_OFLOW_SCALE_FIELD			_MK_FIELD_CONST(0xffff, NVDLA_SDP_S_LUT_LO_SLOPE_SCALE_0_LUT_LO_SLOPE_OFLOW_SCALE_SHIFT)


// Register NVDLA_SDP_S_LUT_LO_SLOPE_SHIFT_0
#define NVDLA_SDP_S_LUT_LO_SLOPE_SHIFT_0			_MK_ADDR_CONST(0x9034)
#define NVDLA_SDP_S_LUT_LO_SLOPE_SHIFT_0_LUT_LO_SLOPE_UFLOW_SHIFT_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_SDP_S_LUT_LO_SLOPE_SHIFT_0_LUT_LO_SLOPE_UFLOW_SHIFT_FIELD			_MK_FIELD_CONST(0x1f, NVDLA_SDP_S_LUT_LO_SLOPE_SHIFT_0_LUT_LO_SLOPE_UFLOW_SHIFT_SHIFT)
#define NVDLA_SDP_S_LUT_LO_SLOPE_SHIFT_0_LUT_LO_SLOPE_OFLOW_SHIFT_SHIFT			_MK_SHIFT_CONST(5)
#define NVDLA_SDP_S_LUT_LO_SLOPE_SHIFT_0_LUT_LO_SLOPE_OFLOW_SHIFT_FIELD			_MK_FIELD_CONST(0x1f, NVDLA_SDP_S_LUT_LO_SLOPE_SHIFT_0_LUT_LO_SLOPE_OFLOW_SHIFT_SHIFT)


// Register NVDLA_SDP_D_OP_ENABLE_0
#define NVDLA_SDP_D_OP_ENABLE_0			_MK_ADDR_CONST(0x9038)
#define NVDLA_SDP_D_OP_ENABLE_0_OP_EN_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_SDP_D_OP_ENABLE_0_OP_EN_FIELD			_MK_FIELD_CONST(0x1, NVDLA_SDP_D_OP_ENABLE_0_OP_EN_SHIFT)
#define NVDLA_SDP_D_OP_ENABLE_0_OP_EN_DISABLE			_MK_ENUM_CONST(0x0)
#define NVDLA_SDP_D_OP_ENABLE_0_OP_EN_ENABLE			_MK_ENUM_CONST(0x1)


// Register NVDLA_SDP_D_DATA_CUBE_WIDTH_0
#define NVDLA_SDP_D_DATA_CUBE_WIDTH_0			_MK_ADDR_CONST(0x903c)
#define NVDLA_SDP_D_DATA_CUBE_WIDTH_0_WIDTH_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_SDP_D_DATA_CUBE_WIDTH_0_WIDTH_FIELD			_MK_FIELD_CONST(0x1fff, NVDLA_SDP_D_DATA_CUBE_WIDTH_0_WIDTH_SHIFT)


// Register NVDLA_SDP_D_DATA_CUBE_HEIGHT_0
#define NVDLA_SDP_D_DATA_CUBE_HEIGHT_0			_MK_ADDR_CONST(0x9040)
#define NVDLA_SDP_D_DATA_CUBE_HEIGHT_0_HEIGHT_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_SDP_D_DATA_CUBE_HEIGHT_0_HEIGHT_FIELD			_MK_FIELD_CONST(0x1fff, NVDLA_SDP_D_DATA_CUBE_HEIGHT_0_HEIGHT_SHIFT)


// Register NVDLA_SDP_D_DATA_CUBE_CHANNEL_0
#define NVDLA_SDP_D_DATA_CUBE_CHANNEL_0			_MK_ADDR_CONST(0x9044)
#define NVDLA_SDP_D_DATA_CUBE_CHANNEL_0_CHANNEL_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_SDP_D_DATA_CUBE_CHANNEL_0_CHANNEL_FIELD			_MK_FIELD_CONST(0x1fff, NVDLA_SDP_D_DATA_CUBE_CHANNEL_0_CHANNEL_SHIFT)


// Register NVDLA_SDP_D_DST_BASE_ADDR_LOW_0
#define NVDLA_SDP_D_DST_BASE_ADDR_LOW_0			_MK_ADDR_CONST(0x9048)
#define NVDLA_SDP_D_DST_BASE_ADDR_LOW_0_DST_BASE_ADDR_LOW_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_SDP_D_DST_BASE_ADDR_LOW_0_DST_BASE_ADDR_LOW_FIELD			_MK_FIELD_CONST(0xffffffff, NVDLA_SDP_D_DST_BASE_ADDR_LOW_0_DST_BASE_ADDR_LOW_SHIFT)


// Register NVDLA_SDP_D_DST_BASE_ADDR_HIGH_0
#define NVDLA_SDP_D_DST_BASE_ADDR_HIGH_0			_MK_ADDR_CONST(0x904c)
#define NVDLA_SDP_D_DST_BASE_ADDR_HIGH_0_DST_BASE_ADDR_HIGH_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_SDP_D_DST_BASE_ADDR_HIGH_0_DST_BASE_ADDR_HIGH_FIELD			_MK_FIELD_CONST(0xffffffff, NVDLA_SDP_D_DST_BASE_ADDR_HIGH_0_DST_BASE_ADDR_HIGH_SHIFT)


// Register NVDLA_SDP_D_DST_LINE_STRIDE_0
#define NVDLA_SDP_D_DST_LINE_STRIDE_0			_MK_ADDR_CONST(0x9050)
#define NVDLA_SDP_D_DST_LINE_STRIDE_0_DST_LINE_STRIDE_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_SDP_D_DST_LINE_STRIDE_0_DST_LINE_STRIDE_FIELD			_MK_FIELD_CONST(0xffffffff, NVDLA_SDP_D_DST_LINE_STRIDE_0_DST_LINE_STRIDE_SHIFT)


// Register NVDLA_SDP_D_DST_SURFACE_STRIDE_0
#define NVDLA_SDP_D_DST_SURFACE_STRIDE_0			_MK_ADDR_CONST(0x9054)
#define NVDLA_SDP_D_DST_SURFACE_STRIDE_0_DST_SURFACE_STRIDE_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_SDP_D_DST_SURFACE_STRIDE_0_DST_SURFACE_STRIDE_FIELD			_MK_FIELD_CONST(0xffffffff, NVDLA_SDP_D_DST_SURFACE_STRIDE_0_DST_SURFACE_STRIDE_SHIFT)


// Register NVDLA_SDP_D_DP_BS_CFG_0
#define NVDLA_SDP_D_DP_BS_CFG_0			_MK_ADDR_CONST(0x9058)
#define NVDLA_SDP_D_DP_BS_CFG_0_BS_BYPASS_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_SDP_D_DP_BS_CFG_0_BS_BYPASS_FIELD			_MK_FIELD_CONST(0x1, NVDLA_SDP_D_DP_BS_CFG_0_BS_BYPASS_SHIFT)
#define NVDLA_SDP_D_DP_BS_CFG_0_BS_BYPASS_NO			_MK_ENUM_CONST(0x0)
#define NVDLA_SDP_D_DP_BS_CFG_0_BS_BYPASS_YES			_MK_ENUM_CONST(0x1)
#define NVDLA_SDP_D_DP_BS_CFG_0_BS_ALU_BYPASS_SHIFT			_MK_SHIFT_CONST(1)
#define NVDLA_SDP_D_DP_BS_CFG_0_BS_ALU_BYPASS_FIELD			_MK_FIELD_CONST(0x1, NVDLA_SDP_D_DP_BS_CFG_0_BS_ALU_BYPASS_SHIFT)
#define NVDLA_SDP_D_DP_BS_CFG_0_BS_ALU_BYPASS_NO			_MK_ENUM_CONST(0x0)
#define NVDLA_SDP_D_DP_BS_CFG_0_BS_ALU_BYPASS_YES			_MK_ENUM_CONST(0x1)
#define NVDLA_SDP_D_DP_BS_CFG_0_BS_ALU_ALGO_SHIFT			_MK_SHIFT_CONST(2)
#define NVDLA_SDP_D_DP_BS_CFG_0_BS_ALU_ALGO_FIELD			_MK_FIELD_CONST(0x3, NVDLA_SDP_D_DP_BS_CFG_0_BS_ALU_ALGO_SHIFT)
#define NVDLA_SDP_D_DP_BS_CFG_0_BS_ALU_ALGO_MAX			_MK_ENUM_CONST(0x0)
#define NVDLA_SDP_D_DP_BS_CFG_0_BS_ALU_ALGO_MIN			_MK_ENUM_CONST(0x1)
#define NVDLA_SDP_D_DP_BS_CFG_0_BS_ALU_ALGO_SUM			_MK_ENUM_CONST(0x2)
#define NVDLA_SDP_D_DP_BS_CFG_0_BS_MUL_BYPASS_SHIFT			_MK_SHIFT_CONST(4)
#define NVDLA_SDP_D_DP_BS_CFG_0_BS_MUL_BYPASS_FIELD			_MK_FIELD_CONST(0x1, NVDLA_SDP_D_DP_BS_CFG_0_BS_MUL_BYPASS_SHIFT)
#define NVDLA_SDP_D_DP_BS_CFG_0_BS_MUL_BYPASS_NO			_MK_ENUM_CONST(0x0)
#define NVDLA_SDP_D_DP_BS_CFG_0_BS_MUL_BYPASS_YES			_MK_ENUM_CONST(0x1)
#define NVDLA_SDP_D_DP_BS_CFG_0_BS_MUL_PRELU_SHIFT			_MK_SHIFT_CONST(5)
#define NVDLA_SDP_D_DP_BS_CFG_0_BS_MUL_PRELU_FIELD			_MK_FIELD_CONST(0x1, NVDLA_SDP_D_DP_BS_CFG_0_BS_MUL_PRELU_SHIFT)
#define NVDLA_SDP_D_DP_BS_CFG_0_BS_MUL_PRELU_NO			_MK_ENUM_CONST(0x0)
#define NVDLA_SDP_D_DP_BS_CFG_0_BS_MUL_PRELU_YES			_MK_ENUM_CONST(0x1)
#define NVDLA_SDP_D_DP_BS_CFG_0_BS_RELU_BYPASS_SHIFT			_MK_SHIFT_CONST(6)
#define NVDLA_SDP_D_DP_BS_CFG_0_BS_RELU_BYPASS_FIELD			_MK_FIELD_CONST(0x1, NVDLA_SDP_D_DP_BS_CFG_0_BS_RELU_BYPASS_SHIFT)
#define NVDLA_SDP_D_DP_BS_CFG_0_BS_RELU_BYPASS_NO			_MK_ENUM_CONST(0x0)
#define NVDLA_SDP_D_DP_BS_CFG_0_BS_RELU_BYPASS_YES			_MK_ENUM_CONST(0x1)


// Register NVDLA_SDP_D_DP_BS_ALU_CFG_0
#define NVDLA_SDP_D_DP_BS_ALU_CFG_0			_MK_ADDR_CONST(0x905c)
#define NVDLA_SDP_D_DP_BS_ALU_CFG_0_BS_ALU_SRC_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_SDP_D_DP_BS_ALU_CFG_0_BS_ALU_SRC_FIELD			_MK_FIELD_CONST(0x1, NVDLA_SDP_D_DP_BS_ALU_CFG_0_BS_ALU_SRC_SHIFT)
#define NVDLA_SDP_D_DP_BS_ALU_CFG_0_BS_ALU_SRC_REG			_MK_ENUM_CONST(0x0)
#define NVDLA_SDP_D_DP_BS_ALU_CFG_0_BS_ALU_SRC_MEM			_MK_ENUM_CONST(0x1)
#define NVDLA_SDP_D_DP_BS_ALU_CFG_0_BS_ALU_SHIFT_VALUE_SHIFT			_MK_SHIFT_CONST(8)
#define NVDLA_SDP_D_DP_BS_ALU_CFG_0_BS_ALU_SHIFT_VALUE_FIELD			_MK_FIELD_CONST(0x3f, NVDLA_SDP_D_DP_BS_ALU_CFG_0_BS_ALU_SHIFT_VALUE_SHIFT)


// Register NVDLA_SDP_D_DP_BS_ALU_SRC_VALUE_0
#define NVDLA_SDP_D_DP_BS_ALU_SRC_VALUE_0			_MK_ADDR_CONST(0x9060)
#define NVDLA_SDP_D_DP_BS_ALU_SRC_VALUE_0_BS_ALU_OPERAND_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_SDP_D_DP_BS_ALU_SRC_VALUE_0_BS_ALU_OPERAND_FIELD			_MK_FIELD_CONST(0xffff, NVDLA_SDP_D_DP_BS_ALU_SRC_VALUE_0_BS_ALU_OPERAND_SHIFT)


// Register NVDLA_SDP_D_DP_BS_MUL_CFG_0
#define NVDLA_SDP_D_DP_BS_MUL_CFG_0			_MK_ADDR_CONST(0x9064)
#define NVDLA_SDP_D_DP_BS_MUL_CFG_0_BS_MUL_SRC_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_SDP_D_DP_BS_MUL_CFG_0_BS_MUL_SRC_FIELD			_MK_FIELD_CONST(0x1, NVDLA_SDP_D_DP_BS_MUL_CFG_0_BS_MUL_SRC_SHIFT)
#define NVDLA_SDP_D_DP_BS_MUL_CFG_0_BS_MUL_SRC_REG			_MK_ENUM_CONST(0x0)
#define NVDLA_SDP_D_DP_BS_MUL_CFG_0_BS_MUL_SRC_MEM			_MK_ENUM_CONST(0x1)
#define NVDLA_SDP_D_DP_BS_MUL_CFG_0_BS_MUL_SHIFT_VALUE_SHIFT			_MK_SHIFT_CONST(8)
#define NVDLA_SDP_D_DP_BS_MUL_CFG_0_BS_MUL_SHIFT_VALUE_FIELD			_MK_FIELD_CONST(0xff, NVDLA_SDP_D_DP_BS_MUL_CFG_0_BS_MUL_SHIFT_VALUE_SHIFT)


// Register NVDLA_SDP_D_DP_BS_MUL_SRC_VALUE_0
#define NVDLA_SDP_D_DP_BS_MUL_SRC_VALUE_0			_MK_ADDR_CONST(0x9068)
#define NVDLA_SDP_D_DP_BS_MUL_SRC_VALUE_0_BS_MUL_OPERAND_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_SDP_D_DP_BS_MUL_SRC_VALUE_0_BS_MUL_OPERAND_FIELD			_MK_FIELD_CONST(0xffff, NVDLA_SDP_D_DP_BS_MUL_SRC_VALUE_0_BS_MUL_OPERAND_SHIFT)


// Register NVDLA_SDP_D_DP_BN_CFG_0
#define NVDLA_SDP_D_DP_BN_CFG_0			_MK_ADDR_CONST(0x906c)
#define NVDLA_SDP_D_DP_BN_CFG_0_BN_BYPASS_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_SDP_D_DP_BN_CFG_0_BN_BYPASS_FIELD			_MK_FIELD_CONST(0x1, NVDLA_SDP_D_DP_BN_CFG_0_BN_BYPASS_SHIFT)
#define NVDLA_SDP_D_DP_BN_CFG_0_BN_BYPASS_NO			_MK_ENUM_CONST(0x0)
#define NVDLA_SDP_D_DP_BN_CFG_0_BN_BYPASS_YES			_MK_ENUM_CONST(0x1)
#define NVDLA_SDP_D_DP_BN_CFG_0_BN_ALU_BYPASS_SHIFT			_MK_SHIFT_CONST(1)
#define NVDLA_SDP_D_DP_BN_CFG_0_BN_ALU_BYPASS_FIELD			_MK_FIELD_CONST(0x1, NVDLA_SDP_D_DP_BN_CFG_0_BN_ALU_BYPASS_SHIFT)
#define NVDLA_SDP_D_DP_BN_CFG_0_BN_ALU_BYPASS_NO			_MK_ENUM_CONST(0x0)
#define NVDLA_SDP_D_DP_BN_CFG_0_BN_ALU_BYPASS_YES			_MK_ENUM_CONST(0x1)
#define NVDLA_SDP_D_DP_BN_CFG_0_BN_ALU_ALGO_SHIFT			_MK_SHIFT_CONST(2)
#define NVDLA_SDP_D_DP_BN_CFG_0_BN_ALU_ALGO_FIELD			_MK_FIELD_CONST(0x3, NVDLA_SDP_D_DP_BN_CFG_0_BN_ALU_ALGO_SHIFT)
#define NVDLA_SDP_D_DP_BN_CFG_0_BN_ALU_ALGO_MAX			_MK_ENUM_CONST(0x0)
#define NVDLA_SDP_D_DP_BN_CFG_0_BN_ALU_ALGO_MIN			_MK_ENUM_CONST(0x1)
#define NVDLA_SDP_D_DP_BN_CFG_0_BN_ALU_ALGO_SUM			_MK_ENUM_CONST(0x2)
#define NVDLA_SDP_D_DP_BN_CFG_0_BN_MUL_BYPASS_SHIFT			_MK_SHIFT_CONST(4)
#define NVDLA_SDP_D_DP_BN_CFG_0_BN_MUL_BYPASS_FIELD			_MK_FIELD_CONST(0x1, NVDLA_SDP_D_DP_BN_CFG_0_BN_MUL_BYPASS_SHIFT)
#define NVDLA_SDP_D_DP_BN_CFG_0_BN_MUL_BYPASS_NO			_MK_ENUM_CONST(0x0)
#define NVDLA_SDP_D_DP_BN_CFG_0_BN_MUL_BYPASS_YES			_MK_ENUM_CONST(0x1)
#define NVDLA_SDP_D_DP_BN_CFG_0_BN_MUL_PRELU_SHIFT			_MK_SHIFT_CONST(5)
#define NVDLA_SDP_D_DP_BN_CFG_0_BN_MUL_PRELU_FIELD			_MK_FIELD_CONST(0x1, NVDLA_SDP_D_DP_BN_CFG_0_BN_MUL_PRELU_SHIFT)
#define NVDLA_SDP_D_DP_BN_CFG_0_BN_MUL_PRELU_NO			_MK_ENUM_CONST(0x0)
#define NVDLA_SDP_D_DP_BN_CFG_0_BN_MUL_PRELU_YES			_MK_ENUM_CONST(0x1)
#define NVDLA_SDP_D_DP_BN_CFG_0_BN_RELU_BYPASS_SHIFT			_MK_SHIFT_CONST(6)
#define NVDLA_SDP_D_DP_BN_CFG_0_BN_RELU_BYPASS_FIELD			_MK_FIELD_CONST(0x1, NVDLA_SDP_D_DP_BN_CFG_0_BN_RELU_BYPASS_SHIFT)
#define NVDLA_SDP_D_DP_BN_CFG_0_BN_RELU_BYPASS_NO			_MK_ENUM_CONST(0x0)
#define NVDLA_SDP_D_DP_BN_CFG_0_BN_RELU_BYPASS_YES			_MK_ENUM_CONST(0x1)


// Register NVDLA_SDP_D_DP_BN_ALU_CFG_0
#define NVDLA_SDP_D_DP_BN_ALU_CFG_0			_MK_ADDR_CONST(0x9070)
#define NVDLA_SDP_D_DP_BN_ALU_CFG_0_BN_ALU_SRC_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_SDP_D_DP_BN_ALU_CFG_0_BN_ALU_SRC_FIELD			_MK_FIELD_CONST(0x1, NVDLA_SDP_D_DP_BN_ALU_CFG_0_BN_ALU_SRC_SHIFT)
#define NVDLA_SDP_D_DP_BN_ALU_CFG_0_BN_ALU_SRC_REG			_MK_ENUM_CONST(0x0)
#define NVDLA_SDP_D_DP_BN_ALU_CFG_0_BN_ALU_SRC_MEM			_MK_ENUM_CONST(0x1)
#define NVDLA_SDP_D_DP_BN_ALU_CFG_0_BN_ALU_SHIFT_VALUE_SHIFT			_MK_SHIFT_CONST(8)
#define NVDLA_SDP_D_DP_BN_ALU_CFG_0_BN_ALU_SHIFT_VALUE_FIELD			_MK_FIELD_CONST(0x3f, NVDLA_SDP_D_DP_BN_ALU_CFG_0_BN_ALU_SHIFT_VALUE_SHIFT)


// Register NVDLA_SDP_D_DP_BN_ALU_SRC_VALUE_0
#define NVDLA_SDP_D_DP_BN_ALU_SRC_VALUE_0			_MK_ADDR_CONST(0x9074)
#define NVDLA_SDP_D_DP_BN_ALU_SRC_VALUE_0_BN_ALU_OPERAND_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_SDP_D_DP_BN_ALU_SRC_VALUE_0_BN_ALU_OPERAND_FIELD			_MK_FIELD_CONST(0xffff, NVDLA_SDP_D_DP_BN_ALU_SRC_VALUE_0_BN_ALU_OPERAND_SHIFT)


// Register NVDLA_SDP_D_DP_BN_MUL_CFG_0
#define NVDLA_SDP_D_DP_BN_MUL_CFG_0			_MK_ADDR_CONST(0x9078)
#define NVDLA_SDP_D_DP_BN_MUL_CFG_0_BN_MUL_SRC_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_SDP_D_DP_BN_MUL_CFG_0_BN_MUL_SRC_FIELD			_MK_FIELD_CONST(0x1, NVDLA_SDP_D_DP_BN_MUL_CFG_0_BN_MUL_SRC_SHIFT)
#define NVDLA_SDP_D_DP_BN_MUL_CFG_0_BN_MUL_SRC_REG			_MK_ENUM_CONST(0x0)
#define NVDLA_SDP_D_DP_BN_MUL_CFG_0_BN_MUL_SRC_MEM			_MK_ENUM_CONST(0x1)
#define NVDLA_SDP_D_DP_BN_MUL_CFG_0_BN_MUL_SHIFT_VALUE_SHIFT			_MK_SHIFT_CONST(8)
#define NVDLA_SDP_D_DP_BN_MUL_CFG_0_BN_MUL_SHIFT_VALUE_FIELD			_MK_FIELD_CONST(0xff, NVDLA_SDP_D_DP_BN_MUL_CFG_0_BN_MUL_SHIFT_VALUE_SHIFT)


// Register NVDLA_SDP_D_DP_BN_MUL_SRC_VALUE_0
#define NVDLA_SDP_D_DP_BN_MUL_SRC_VALUE_0			_MK_ADDR_CONST(0x907c)
#define NVDLA_SDP_D_DP_BN_MUL_SRC_VALUE_0_BN_MUL_OPERAND_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_SDP_D_DP_BN_MUL_SRC_VALUE_0_BN_MUL_OPERAND_FIELD			_MK_FIELD_CONST(0xffff, NVDLA_SDP_D_DP_BN_MUL_SRC_VALUE_0_BN_MUL_OPERAND_SHIFT)


// Register NVDLA_SDP_D_DP_EW_CFG_0
#define NVDLA_SDP_D_DP_EW_CFG_0			_MK_ADDR_CONST(0x9080)
#define NVDLA_SDP_D_DP_EW_CFG_0_EW_BYPASS_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_SDP_D_DP_EW_CFG_0_EW_BYPASS_FIELD			_MK_FIELD_CONST(0x1, NVDLA_SDP_D_DP_EW_CFG_0_EW_BYPASS_SHIFT)
#define NVDLA_SDP_D_DP_EW_CFG_0_EW_BYPASS_NO			_MK_ENUM_CONST(0x0)
#define NVDLA_SDP_D_DP_EW_CFG_0_EW_BYPASS_YES			_MK_ENUM_CONST(0x1)
#define NVDLA_SDP_D_DP_EW_CFG_0_EW_ALU_BYPASS_SHIFT			_MK_SHIFT_CONST(1)
#define NVDLA_SDP_D_DP_EW_CFG_0_EW_ALU_BYPASS_FIELD			_MK_FIELD_CONST(0x1, NVDLA_SDP_D_DP_EW_CFG_0_EW_ALU_BYPASS_SHIFT)
#define NVDLA_SDP_D_DP_EW_CFG_0_EW_ALU_BYPASS_NO			_MK_ENUM_CONST(0x0)
#define NVDLA_SDP_D_DP_EW_CFG_0_EW_ALU_BYPASS_YES			_MK_ENUM_CONST(0x1)
#define NVDLA_SDP_D_DP_EW_CFG_0_EW_ALU_ALGO_SHIFT			_MK_SHIFT_CONST(2)
#define NVDLA_SDP_D_DP_EW_CFG_0_EW_ALU_ALGO_FIELD			_MK_FIELD_CONST(0x3, NVDLA_SDP_D_DP_EW_CFG_0_EW_ALU_ALGO_SHIFT)
#define NVDLA_SDP_D_DP_EW_CFG_0_EW_ALU_ALGO_MAX			_MK_ENUM_CONST(0x0)
#define NVDLA_SDP_D_DP_EW_CFG_0_EW_ALU_ALGO_MIN			_MK_ENUM_CONST(0x1)
#define NVDLA_SDP_D_DP_EW_CFG_0_EW_ALU_ALGO_SUM			_MK_ENUM_CONST(0x2)
#define NVDLA_SDP_D_DP_EW_CFG_0_EW_ALU_ALGO_EQL			_MK_ENUM_CONST(0x3)
#define NVDLA_SDP_D_DP_EW_CFG_0_EW_MUL_BYPASS_SHIFT			_MK_SHIFT_CONST(4)
#define NVDLA_SDP_D_DP_EW_CFG_0_EW_MUL_BYPASS_FIELD			_MK_FIELD_CONST(0x1, NVDLA_SDP_D_DP_EW_CFG_0_EW_MUL_BYPASS_SHIFT)
#define NVDLA_SDP_D_DP_EW_CFG_0_EW_MUL_BYPASS_NO			_MK_ENUM_CONST(0x0)
#define NVDLA_SDP_D_DP_EW_CFG_0_EW_MUL_BYPASS_YES			_MK_ENUM_CONST(0x1)
#define NVDLA_SDP_D_DP_EW_CFG_0_EW_MUL_PRELU_SHIFT			_MK_SHIFT_CONST(5)
#define NVDLA_SDP_D_DP_EW_CFG_0_EW_MUL_PRELU_FIELD			_MK_FIELD_CONST(0x1, NVDLA_SDP_D_DP_EW_CFG_0_EW_MUL_PRELU_SHIFT)
#define NVDLA_SDP_D_DP_EW_CFG_0_EW_MUL_PRELU_NO			_MK_ENUM_CONST(0x0)
#define NVDLA_SDP_D_DP_EW_CFG_0_EW_MUL_PRELU_YES			_MK_ENUM_CONST(0x1)
#define NVDLA_SDP_D_DP_EW_CFG_0_EW_LUT_BYPASS_SHIFT			_MK_SHIFT_CONST(6)
#define NVDLA_SDP_D_DP_EW_CFG_0_EW_LUT_BYPASS_FIELD			_MK_FIELD_CONST(0x1, NVDLA_SDP_D_DP_EW_CFG_0_EW_LUT_BYPASS_SHIFT)
#define NVDLA_SDP_D_DP_EW_CFG_0_EW_LUT_BYPASS_NO			_MK_ENUM_CONST(0x0)
#define NVDLA_SDP_D_DP_EW_CFG_0_EW_LUT_BYPASS_YES			_MK_ENUM_CONST(0x1)


// Register NVDLA_SDP_D_DP_EW_ALU_CFG_0
#define NVDLA_SDP_D_DP_EW_ALU_CFG_0			_MK_ADDR_CONST(0x9084)
#define NVDLA_SDP_D_DP_EW_ALU_CFG_0_EW_ALU_SRC_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_SDP_D_DP_EW_ALU_CFG_0_EW_ALU_SRC_FIELD			_MK_FIELD_CONST(0x1, NVDLA_SDP_D_DP_EW_ALU_CFG_0_EW_ALU_SRC_SHIFT)
#define NVDLA_SDP_D_DP_EW_ALU_CFG_0_EW_ALU_SRC_REG			_MK_ENUM_CONST(0x0)
#define NVDLA_SDP_D_DP_EW_ALU_CFG_0_EW_ALU_SRC_MEM			_MK_ENUM_CONST(0x1)
#define NVDLA_SDP_D_DP_EW_ALU_CFG_0_EW_ALU_CVT_BYPASS_SHIFT			_MK_SHIFT_CONST(1)
#define NVDLA_SDP_D_DP_EW_ALU_CFG_0_EW_ALU_CVT_BYPASS_FIELD			_MK_FIELD_CONST(0x1, NVDLA_SDP_D_DP_EW_ALU_CFG_0_EW_ALU_CVT_BYPASS_SHIFT)
#define NVDLA_SDP_D_DP_EW_ALU_CFG_0_EW_ALU_CVT_BYPASS_NO			_MK_ENUM_CONST(0x0)
#define NVDLA_SDP_D_DP_EW_ALU_CFG_0_EW_ALU_CVT_BYPASS_YES			_MK_ENUM_CONST(0x1)


// Register NVDLA_SDP_D_DP_EW_ALU_SRC_VALUE_0
#define NVDLA_SDP_D_DP_EW_ALU_SRC_VALUE_0			_MK_ADDR_CONST(0x9088)
#define NVDLA_SDP_D_DP_EW_ALU_SRC_VALUE_0_EW_ALU_OPERAND_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_SDP_D_DP_EW_ALU_SRC_VALUE_0_EW_ALU_OPERAND_FIELD			_MK_FIELD_CONST(0xffffffff, NVDLA_SDP_D_DP_EW_ALU_SRC_VALUE_0_EW_ALU_OPERAND_SHIFT)


// Register NVDLA_SDP_D_DP_EW_ALU_CVT_OFFSET_VALUE_0
#define NVDLA_SDP_D_DP_EW_ALU_CVT_OFFSET_VALUE_0			_MK_ADDR_CONST(0x908c)
#define NVDLA_SDP_D_DP_EW_ALU_CVT_OFFSET_VALUE_0_EW_ALU_CVT_OFFSET_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_SDP_D_DP_EW_ALU_CVT_OFFSET_VALUE_0_EW_ALU_CVT_OFFSET_FIELD			_MK_FIELD_CONST(0xffffffff, NVDLA_SDP_D_DP_EW_ALU_CVT_OFFSET_VALUE_0_EW_ALU_CVT_OFFSET_SHIFT)


// Register NVDLA_SDP_D_DP_EW_ALU_CVT_SCALE_VALUE_0
#define NVDLA_SDP_D_DP_EW_ALU_CVT_SCALE_VALUE_0			_MK_ADDR_CONST(0x9090)
#define NVDLA_SDP_D_DP_EW_ALU_CVT_SCALE_VALUE_0_EW_ALU_CVT_SCALE_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_SDP_D_DP_EW_ALU_CVT_SCALE_VALUE_0_EW_ALU_CVT_SCALE_FIELD			_MK_FIELD_CONST(0xffff, NVDLA_SDP_D_DP_EW_ALU_CVT_SCALE_VALUE_0_EW_ALU_CVT_SCALE_SHIFT)


// Register NVDLA_SDP_D_DP_EW_ALU_CVT_TRUNCATE_VALUE_0
#define NVDLA_SDP_D_DP_EW_ALU_CVT_TRUNCATE_VALUE_0			_MK_ADDR_CONST(0x9094)
#define NVDLA_SDP_D_DP_EW_ALU_CVT_TRUNCATE_VALUE_0_EW_ALU_CVT_TRUNCATE_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_SDP_D_DP_EW_ALU_CVT_TRUNCATE_VALUE_0_EW_ALU_CVT_TRUNCATE_FIELD			_MK_FIELD_CONST(0x3f, NVDLA_SDP_D_DP_EW_ALU_CVT_TRUNCATE_VALUE_0_EW_ALU_CVT_TRUNCATE_SHIFT)


// Register NVDLA_SDP_D_DP_EW_MUL_CFG_0
#define NVDLA_SDP_D_DP_EW_MUL_CFG_0			_MK_ADDR_CONST(0x9098)
#define NVDLA_SDP_D_DP_EW_MUL_CFG_0_EW_MUL_SRC_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_SDP_D_DP_EW_MUL_CFG_0_EW_MUL_SRC_FIELD			_MK_FIELD_CONST(0x1, NVDLA_SDP_D_DP_EW_MUL_CFG_0_EW_MUL_SRC_SHIFT)
#define NVDLA_SDP_D_DP_EW_MUL_CFG_0_EW_MUL_SRC_REG			_MK_ENUM_CONST(0x0)
#define NVDLA_SDP_D_DP_EW_MUL_CFG_0_EW_MUL_SRC_MEM			_MK_ENUM_CONST(0x1)
#define NVDLA_SDP_D_DP_EW_MUL_CFG_0_EW_MUL_CVT_BYPASS_SHIFT			_MK_SHIFT_CONST(1)
#define NVDLA_SDP_D_DP_EW_MUL_CFG_0_EW_MUL_CVT_BYPASS_FIELD			_MK_FIELD_CONST(0x1, NVDLA_SDP_D_DP_EW_MUL_CFG_0_EW_MUL_CVT_BYPASS_SHIFT)
#define NVDLA_SDP_D_DP_EW_MUL_CFG_0_EW_MUL_CVT_BYPASS_NO			_MK_ENUM_CONST(0x0)
#define NVDLA_SDP_D_DP_EW_MUL_CFG_0_EW_MUL_CVT_BYPASS_YES			_MK_ENUM_CONST(0x1)


// Register NVDLA_SDP_D_DP_EW_MUL_SRC_VALUE_0
#define NVDLA_SDP_D_DP_EW_MUL_SRC_VALUE_0			_MK_ADDR_CONST(0x909c)
#define NVDLA_SDP_D_DP_EW_MUL_SRC_VALUE_0_EW_MUL_OPERAND_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_SDP_D_DP_EW_MUL_SRC_VALUE_0_EW_MUL_OPERAND_FIELD			_MK_FIELD_CONST(0xffffffff, NVDLA_SDP_D_DP_EW_MUL_SRC_VALUE_0_EW_MUL_OPERAND_SHIFT)


// Register NVDLA_SDP_D_DP_EW_MUL_CVT_OFFSET_VALUE_0
#define NVDLA_SDP_D_DP_EW_MUL_CVT_OFFSET_VALUE_0			_MK_ADDR_CONST(0x90a0)
#define NVDLA_SDP_D_DP_EW_MUL_CVT_OFFSET_VALUE_0_EW_MUL_CVT_OFFSET_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_SDP_D_DP_EW_MUL_CVT_OFFSET_VALUE_0_EW_MUL_CVT_OFFSET_FIELD			_MK_FIELD_CONST(0xffffffff, NVDLA_SDP_D_DP_EW_MUL_CVT_OFFSET_VALUE_0_EW_MUL_CVT_OFFSET_SHIFT)


// Register NVDLA_SDP_D_DP_EW_MUL_CVT_SCALE_VALUE_0
#define NVDLA_SDP_D_DP_EW_MUL_CVT_SCALE_VALUE_0			_MK_ADDR_CONST(0x90a4)
#define NVDLA_SDP_D_DP_EW_MUL_CVT_SCALE_VALUE_0_EW_MUL_CVT_SCALE_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_SDP_D_DP_EW_MUL_CVT_SCALE_VALUE_0_EW_MUL_CVT_SCALE_FIELD			_MK_FIELD_CONST(0xffff, NVDLA_SDP_D_DP_EW_MUL_CVT_SCALE_VALUE_0_EW_MUL_CVT_SCALE_SHIFT)


// Register NVDLA_SDP_D_DP_EW_MUL_CVT_TRUNCATE_VALUE_0
#define NVDLA_SDP_D_DP_EW_MUL_CVT_TRUNCATE_VALUE_0			_MK_ADDR_CONST(0x90a8)
#define NVDLA_SDP_D_DP_EW_MUL_CVT_TRUNCATE_VALUE_0_EW_MUL_CVT_TRUNCATE_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_SDP_D_DP_EW_MUL_CVT_TRUNCATE_VALUE_0_EW_MUL_CVT_TRUNCATE_FIELD			_MK_FIELD_CONST(0x3f, NVDLA_SDP_D_DP_EW_MUL_CVT_TRUNCATE_VALUE_0_EW_MUL_CVT_TRUNCATE_SHIFT)


// Register NVDLA_SDP_D_DP_EW_TRUNCATE_VALUE_0
#define NVDLA_SDP_D_DP_EW_TRUNCATE_VALUE_0			_MK_ADDR_CONST(0x90ac)
#define NVDLA_SDP_D_DP_EW_TRUNCATE_VALUE_0_EW_TRUNCATE_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_SDP_D_DP_EW_TRUNCATE_VALUE_0_EW_TRUNCATE_FIELD			_MK_FIELD_CONST(0x3ff, NVDLA_SDP_D_DP_EW_TRUNCATE_VALUE_0_EW_TRUNCATE_SHIFT)


// Register NVDLA_SDP_D_FEATURE_MODE_CFG_0
#define NVDLA_SDP_D_FEATURE_MODE_CFG_0			_MK_ADDR_CONST(0x90b0)
#define NVDLA_SDP_D_FEATURE_MODE_CFG_0_FLYING_MODE_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_SDP_D_FEATURE_MODE_CFG_0_FLYING_MODE_FIELD			_MK_FIELD_CONST(0x1, NVDLA_SDP_D_FEATURE_MODE_CFG_0_FLYING_MODE_SHIFT)
#define NVDLA_SDP_D_FEATURE_MODE_CFG_0_FLYING_MODE_OFF			_MK_ENUM_CONST(0x0)
#define NVDLA_SDP_D_FEATURE_MODE_CFG_0_FLYING_MODE_ON			_MK_ENUM_CONST(0x1)
#define NVDLA_SDP_D_FEATURE_MODE_CFG_0_OUTPUT_DST_SHIFT			_MK_SHIFT_CONST(1)
#define NVDLA_SDP_D_FEATURE_MODE_CFG_0_OUTPUT_DST_FIELD			_MK_FIELD_CONST(0x1, NVDLA_SDP_D_FEATURE_MODE_CFG_0_OUTPUT_DST_SHIFT)
#define NVDLA_SDP_D_FEATURE_MODE_CFG_0_OUTPUT_DST_MEM			_MK_ENUM_CONST(0x0)
#define NVDLA_SDP_D_FEATURE_MODE_CFG_0_OUTPUT_DST_PDP			_MK_ENUM_CONST(0x1)
#define NVDLA_SDP_D_FEATURE_MODE_CFG_0_WINOGRAD_SHIFT			_MK_SHIFT_CONST(2)
#define NVDLA_SDP_D_FEATURE_MODE_CFG_0_WINOGRAD_FIELD			_MK_FIELD_CONST(0x1, NVDLA_SDP_D_FEATURE_MODE_CFG_0_WINOGRAD_SHIFT)
#define NVDLA_SDP_D_FEATURE_MODE_CFG_0_WINOGRAD_OFF			_MK_ENUM_CONST(0x0)
#define NVDLA_SDP_D_FEATURE_MODE_CFG_0_WINOGRAD_ON			_MK_ENUM_CONST(0x1)
#define NVDLA_SDP_D_FEATURE_MODE_CFG_0_NAN_TO_ZERO_SHIFT			_MK_SHIFT_CONST(3)
#define NVDLA_SDP_D_FEATURE_MODE_CFG_0_NAN_TO_ZERO_FIELD			_MK_FIELD_CONST(0x1, NVDLA_SDP_D_FEATURE_MODE_CFG_0_NAN_TO_ZERO_SHIFT)
#define NVDLA_SDP_D_FEATURE_MODE_CFG_0_NAN_TO_ZERO_DISABLE			_MK_ENUM_CONST(0x0)
#define NVDLA_SDP_D_FEATURE_MODE_CFG_0_NAN_TO_ZERO_ENABLE			_MK_ENUM_CONST(0x1)
#define NVDLA_SDP_D_FEATURE_MODE_CFG_0_BATCH_NUMBER_SHIFT			_MK_SHIFT_CONST(8)
#define NVDLA_SDP_D_FEATURE_MODE_CFG_0_BATCH_NUMBER_FIELD			_MK_FIELD_CONST(0x1f, NVDLA_SDP_D_FEATURE_MODE_CFG_0_BATCH_NUMBER_SHIFT)


// Register NVDLA_SDP_D_DST_DMA_CFG_0
#define NVDLA_SDP_D_DST_DMA_CFG_0			_MK_ADDR_CONST(0x90b4)
#define NVDLA_SDP_D_DST_DMA_CFG_0_DST_RAM_TYPE_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_SDP_D_DST_DMA_CFG_0_DST_RAM_TYPE_FIELD			_MK_FIELD_CONST(0x1, NVDLA_SDP_D_DST_DMA_CFG_0_DST_RAM_TYPE_SHIFT)
#define NVDLA_SDP_D_DST_DMA_CFG_0_DST_RAM_TYPE_CV			_MK_ENUM_CONST(0x0)
#define NVDLA_SDP_D_DST_DMA_CFG_0_DST_RAM_TYPE_MC			_MK_ENUM_CONST(0x1)


// Register NVDLA_SDP_D_DST_BATCH_STRIDE_0
#define NVDLA_SDP_D_DST_BATCH_STRIDE_0			_MK_ADDR_CONST(0x90b8)
#define NVDLA_SDP_D_DST_BATCH_STRIDE_0_DST_BATCH_STRIDE_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_SDP_D_DST_BATCH_STRIDE_0_DST_BATCH_STRIDE_FIELD			_MK_FIELD_CONST(0xffffffff, NVDLA_SDP_D_DST_BATCH_STRIDE_0_DST_BATCH_STRIDE_SHIFT)


// Register NVDLA_SDP_D_DATA_FORMAT_0
#define NVDLA_SDP_D_DATA_FORMAT_0			_MK_ADDR_CONST(0x90bc)
#define NVDLA_SDP_D_DATA_FORMAT_0_PROC_PRECISION_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_SDP_D_DATA_FORMAT_0_PROC_PRECISION_FIELD			_MK_FIELD_CONST(0x3, NVDLA_SDP_D_DATA_FORMAT_0_PROC_PRECISION_SHIFT)
#define NVDLA_SDP_D_DATA_FORMAT_0_PROC_PRECISION_INT8			_MK_ENUM_CONST(0x0)
#define NVDLA_SDP_D_DATA_FORMAT_0_PROC_PRECISION_INT16			_MK_ENUM_CONST(0x1)
#define NVDLA_SDP_D_DATA_FORMAT_0_PROC_PRECISION_FP16			_MK_ENUM_CONST(0x2)
#define NVDLA_SDP_D_DATA_FORMAT_0_OUT_PRECISION_SHIFT			_MK_SHIFT_CONST(2)
#define NVDLA_SDP_D_DATA_FORMAT_0_OUT_PRECISION_FIELD			_MK_FIELD_CONST(0x3, NVDLA_SDP_D_DATA_FORMAT_0_OUT_PRECISION_SHIFT)
#define NVDLA_SDP_D_DATA_FORMAT_0_OUT_PRECISION_INT8			_MK_ENUM_CONST(0x0)
#define NVDLA_SDP_D_DATA_FORMAT_0_OUT_PRECISION_INT16			_MK_ENUM_CONST(0x1)
#define NVDLA_SDP_D_DATA_FORMAT_0_OUT_PRECISION_FP16			_MK_ENUM_CONST(0x2)


// Register NVDLA_SDP_D_CVT_OFFSET_0
#define NVDLA_SDP_D_CVT_OFFSET_0			_MK_ADDR_CONST(0x90c0)
#define NVDLA_SDP_D_CVT_OFFSET_0_CVT_OFFSET_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_SDP_D_CVT_OFFSET_0_CVT_OFFSET_FIELD			_MK_FIELD_CONST(0xffffffff, NVDLA_SDP_D_CVT_OFFSET_0_CVT_OFFSET_SHIFT)


// Register NVDLA_SDP_D_CVT_SCALE_0
#define NVDLA_SDP_D_CVT_SCALE_0			_MK_ADDR_CONST(0x90c4)
#define NVDLA_SDP_D_CVT_SCALE_0_CVT_SCALE_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_SDP_D_CVT_SCALE_0_CVT_SCALE_FIELD			_MK_FIELD_CONST(0xffff, NVDLA_SDP_D_CVT_SCALE_0_CVT_SCALE_SHIFT)


// Register NVDLA_SDP_D_CVT_SHIFT_0
#define NVDLA_SDP_D_CVT_SHIFT_0			_MK_ADDR_CONST(0x90c8)
#define NVDLA_SDP_D_CVT_SHIFT_0_CVT_SHIFT_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_SDP_D_CVT_SHIFT_0_CVT_SHIFT_FIELD			_MK_FIELD_CONST(0x3f, NVDLA_SDP_D_CVT_SHIFT_0_CVT_SHIFT_SHIFT)


// Register NVDLA_SDP_D_STATUS_0
#define NVDLA_SDP_D_STATUS_0			_MK_ADDR_CONST(0x90cc)
#define NVDLA_SDP_D_STATUS_0_STATUS_UNEQUAL_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_SDP_D_STATUS_0_STATUS_UNEQUAL_FIELD			_MK_FIELD_CONST(0x1, NVDLA_SDP_D_STATUS_0_STATUS_UNEQUAL_SHIFT)


// Register NVDLA_SDP_D_STATUS_NAN_INPUT_NUM_0
#define NVDLA_SDP_D_STATUS_NAN_INPUT_NUM_0			_MK_ADDR_CONST(0x90d0)
#define NVDLA_SDP_D_STATUS_NAN_INPUT_NUM_0_STATUS_NAN_INPUT_NUM_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_SDP_D_STATUS_NAN_INPUT_NUM_0_STATUS_NAN_INPUT_NUM_FIELD			_MK_FIELD_CONST(0xffffffff, NVDLA_SDP_D_STATUS_NAN_INPUT_NUM_0_STATUS_NAN_INPUT_NUM_SHIFT)


// Register NVDLA_SDP_D_STATUS_INF_INPUT_NUM_0
#define NVDLA_SDP_D_STATUS_INF_INPUT_NUM_0			_MK_ADDR_CONST(0x90d4)
#define NVDLA_SDP_D_STATUS_INF_INPUT_NUM_0_STATUS_INF_INPUT_NUM_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_SDP_D_STATUS_INF_INPUT_NUM_0_STATUS_INF_INPUT_NUM_FIELD			_MK_FIELD_CONST(0xffffffff, NVDLA_SDP_D_STATUS_INF_INPUT_NUM_0_STATUS_INF_INPUT_NUM_SHIFT)


// Register NVDLA_SDP_D_STATUS_NAN_OUTPUT_NUM_0
#define NVDLA_SDP_D_STATUS_NAN_OUTPUT_NUM_0			_MK_ADDR_CONST(0x90d8)
#define NVDLA_SDP_D_STATUS_NAN_OUTPUT_NUM_0_STATUS_NAN_OUTPUT_NUM_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_SDP_D_STATUS_NAN_OUTPUT_NUM_0_STATUS_NAN_OUTPUT_NUM_FIELD			_MK_FIELD_CONST(0xffffffff, NVDLA_SDP_D_STATUS_NAN_OUTPUT_NUM_0_STATUS_NAN_OUTPUT_NUM_SHIFT)


// Register NVDLA_SDP_D_PERF_ENABLE_0
#define NVDLA_SDP_D_PERF_ENABLE_0			_MK_ADDR_CONST(0x90dc)
#define NVDLA_SDP_D_PERF_ENABLE_0_PERF_DMA_EN_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_SDP_D_PERF_ENABLE_0_PERF_DMA_EN_FIELD			_MK_FIELD_CONST(0x1, NVDLA_SDP_D_PERF_ENABLE_0_PERF_DMA_EN_SHIFT)
#define NVDLA_SDP_D_PERF_ENABLE_0_PERF_DMA_EN_NO			_MK_ENUM_CONST(0x0)
#define NVDLA_SDP_D_PERF_ENABLE_0_PERF_DMA_EN_YES			_MK_ENUM_CONST(0x1)
#define NVDLA_SDP_D_PERF_ENABLE_0_PERF_LUT_EN_SHIFT			_MK_SHIFT_CONST(1)
#define NVDLA_SDP_D_PERF_ENABLE_0_PERF_LUT_EN_FIELD			_MK_FIELD_CONST(0x1, NVDLA_SDP_D_PERF_ENABLE_0_PERF_LUT_EN_SHIFT)
#define NVDLA_SDP_D_PERF_ENABLE_0_PERF_LUT_EN_NO			_MK_ENUM_CONST(0x0)
#define NVDLA_SDP_D_PERF_ENABLE_0_PERF_LUT_EN_YES			_MK_ENUM_CONST(0x1)
#define NVDLA_SDP_D_PERF_ENABLE_0_PERF_SAT_EN_SHIFT			_MK_SHIFT_CONST(2)
#define NVDLA_SDP_D_PERF_ENABLE_0_PERF_SAT_EN_FIELD			_MK_FIELD_CONST(0x1, NVDLA_SDP_D_PERF_ENABLE_0_PERF_SAT_EN_SHIFT)
#define NVDLA_SDP_D_PERF_ENABLE_0_PERF_SAT_EN_NO			_MK_ENUM_CONST(0x0)
#define NVDLA_SDP_D_PERF_ENABLE_0_PERF_SAT_EN_YES			_MK_ENUM_CONST(0x1)
#define NVDLA_SDP_D_PERF_ENABLE_0_PERF_NAN_INF_COUNT_EN_SHIFT			_MK_SHIFT_CONST(3)
#define NVDLA_SDP_D_PERF_ENABLE_0_PERF_NAN_INF_COUNT_EN_FIELD			_MK_FIELD_CONST(0x1, NVDLA_SDP_D_PERF_ENABLE_0_PERF_NAN_INF_COUNT_EN_SHIFT)
#define NVDLA_SDP_D_PERF_ENABLE_0_PERF_NAN_INF_COUNT_EN_NO			_MK_ENUM_CONST(0x0)
#define NVDLA_SDP_D_PERF_ENABLE_0_PERF_NAN_INF_COUNT_EN_YES			_MK_ENUM_CONST(0x1)


// Register NVDLA_SDP_D_PERF_WDMA_WRITE_STALL_0
#define NVDLA_SDP_D_PERF_WDMA_WRITE_STALL_0			_MK_ADDR_CONST(0x90e0)
#define NVDLA_SDP_D_PERF_WDMA_WRITE_STALL_0_WDMA_STALL_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_SDP_D_PERF_WDMA_WRITE_STALL_0_WDMA_STALL_FIELD			_MK_FIELD_CONST(0xffffffff, NVDLA_SDP_D_PERF_WDMA_WRITE_STALL_0_WDMA_STALL_SHIFT)


// Register NVDLA_SDP_D_PERF_LUT_UFLOW_0
#define NVDLA_SDP_D_PERF_LUT_UFLOW_0			_MK_ADDR_CONST(0x90e4)
#define NVDLA_SDP_D_PERF_LUT_UFLOW_0_LUT_UFLOW_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_SDP_D_PERF_LUT_UFLOW_0_LUT_UFLOW_FIELD			_MK_FIELD_CONST(0xffffffff, NVDLA_SDP_D_PERF_LUT_UFLOW_0_LUT_UFLOW_SHIFT)


// Register NVDLA_SDP_D_PERF_LUT_OFLOW_0
#define NVDLA_SDP_D_PERF_LUT_OFLOW_0			_MK_ADDR_CONST(0x90e8)
#define NVDLA_SDP_D_PERF_LUT_OFLOW_0_LUT_OFLOW_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_SDP_D_PERF_LUT_OFLOW_0_LUT_OFLOW_FIELD			_MK_FIELD_CONST(0xffffffff, NVDLA_SDP_D_PERF_LUT_OFLOW_0_LUT_OFLOW_SHIFT)


// Register NVDLA_SDP_D_PERF_OUT_SATURATION_0
#define NVDLA_SDP_D_PERF_OUT_SATURATION_0			_MK_ADDR_CONST(0x90ec)
#define NVDLA_SDP_D_PERF_OUT_SATURATION_0_OUT_SATURATION_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_SDP_D_PERF_OUT_SATURATION_0_OUT_SATURATION_FIELD			_MK_FIELD_CONST(0xffffffff, NVDLA_SDP_D_PERF_OUT_SATURATION_0_OUT_SATURATION_SHIFT)


// Register NVDLA_SDP_D_PERF_LUT_HYBRID_0
#define NVDLA_SDP_D_PERF_LUT_HYBRID_0			_MK_ADDR_CONST(0x90f0)
#define NVDLA_SDP_D_PERF_LUT_HYBRID_0_LUT_HYBRID_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_SDP_D_PERF_LUT_HYBRID_0_LUT_HYBRID_FIELD			_MK_FIELD_CONST(0xffffffff, NVDLA_SDP_D_PERF_LUT_HYBRID_0_LUT_HYBRID_SHIFT)


// Register NVDLA_SDP_D_PERF_LUT_LE_HIT_0
#define NVDLA_SDP_D_PERF_LUT_LE_HIT_0			_MK_ADDR_CONST(0x90f4)
#define NVDLA_SDP_D_PERF_LUT_LE_HIT_0_LUT_LE_HIT_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_SDP_D_PERF_LUT_LE_HIT_0_LUT_LE_HIT_FIELD			_MK_FIELD_CONST(0xffffffff, NVDLA_SDP_D_PERF_LUT_LE_HIT_0_LUT_LE_HIT_SHIFT)


// Register NVDLA_SDP_D_PERF_LUT_LO_HIT_0
#define NVDLA_SDP_D_PERF_LUT_LO_HIT_0			_MK_ADDR_CONST(0x90f8)
#define NVDLA_SDP_D_PERF_LUT_LO_HIT_0_LUT_LO_HIT_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_SDP_D_PERF_LUT_LO_HIT_0_LUT_LO_HIT_FIELD			_MK_FIELD_CONST(0xffffffff, NVDLA_SDP_D_PERF_LUT_LO_HIT_0_LUT_LO_HIT_SHIFT)



// To satisfy various compilers and platforms,
// we let users control the types and syntax of certain constants, using macros.
#ifndef _MK_SHIFT_CONST
  #define _MK_SHIFT_CONST(_constant_) _constant_
#endif
#ifndef _MK_MASK_CONST
  #define _MK_MASK_CONST(_constant_) _constant_
#endif
#ifndef _MK_ENUM_CONST
  #define _MK_ENUM_CONST(_constant_) (_constant_ ## UL)
#endif
#ifndef _MK_ADDR_CONST
  #define _MK_ADDR_CONST(_constant_) _constant_
#endif
#ifndef _MK_FIELD_CONST
  #define _MK_FIELD_CONST(_mask_, _shift_) (_MK_MASK_CONST(_mask_) << _MK_SHIFT_CONST(_shift_))
#endif



//
// ADDRESS SPACES
//

#define BASE_ADDRESS_NVDLA_SDP	0x9000
