#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sat Apr 18 19:25:02 CEST 2020
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim tb_dtpu_time_impl -key {Post-Implementation:sim_1:Timing:tb_dtpu} -tclbatch tb_dtpu.tcl -protoinst "protoinst_files/bd_7d7d.protoinst" -protoinst "protoinst_files/pynqz2.protoinst" -log simulate.log"
xsim tb_dtpu_time_impl -key {Post-Implementation:sim_1:Timing:tb_dtpu} -tclbatch tb_dtpu.tcl -protoinst "protoinst_files/bd_7d7d.protoinst" -protoinst "protoinst_files/pynqz2.protoinst" -log simulate.log

