// Register NVDLA_CACC_S_STATUS_0
#define NVDLA_CACC_S_STATUS_0			_MK_ADDR_CONST(0x7000)
#define NVDLA_CACC_S_STATUS_0_STATUS_0_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CACC_S_STATUS_0_STATUS_0_FIELD			_MK_FIELD_CONST(0x3, NVDLA_CACC_S_STATUS_0_STATUS_0_SHIFT)
#define NVDLA_CACC_S_STATUS_0_STATUS_0_IDLE			_MK_ENUM_CONST(0x0)
#define NVDLA_CACC_S_STATUS_0_STATUS_0_RUNNING			_MK_ENUM_CONST(0x1)
#define NVDLA_CACC_S_STATUS_0_STATUS_0_PENDING			_MK_ENUM_CONST(0x2)
#define NVDLA_CACC_S_STATUS_0_STATUS_1_SHIFT			_MK_SHIFT_CONST(16)
#define NVDLA_CACC_S_STATUS_0_STATUS_1_FIELD			_MK_FIELD_CONST(0x3, NVDLA_CACC_S_STATUS_0_STATUS_1_SHIFT)
#define NVDLA_CACC_S_STATUS_0_STATUS_1_IDLE			_MK_ENUM_CONST(0x0)
#define NVDLA_CACC_S_STATUS_0_STATUS_1_RUNNING			_MK_ENUM_CONST(0x1)
#define NVDLA_CACC_S_STATUS_0_STATUS_1_PENDING			_MK_ENUM_CONST(0x2)


// Register NVDLA_CACC_S_POINTER_0
#define NVDLA_CACC_S_POINTER_0			_MK_ADDR_CONST(0x7004)
#define NVDLA_CACC_S_POINTER_0_PRODUCER_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CACC_S_POINTER_0_PRODUCER_FIELD			_MK_FIELD_CONST(0x1, NVDLA_CACC_S_POINTER_0_PRODUCER_SHIFT)
#define NVDLA_CACC_S_POINTER_0_PRODUCER_GROUP_0			_MK_ENUM_CONST(0x0)
#define NVDLA_CACC_S_POINTER_0_PRODUCER_GROUP_1			_MK_ENUM_CONST(0x1)
#define NVDLA_CACC_S_POINTER_0_CONSUMER_SHIFT			_MK_SHIFT_CONST(16)
#define NVDLA_CACC_S_POINTER_0_CONSUMER_FIELD			_MK_FIELD_CONST(0x1, NVDLA_CACC_S_POINTER_0_CONSUMER_SHIFT)
#define NVDLA_CACC_S_POINTER_0_CONSUMER_GROUP_0			_MK_ENUM_CONST(0x0)
#define NVDLA_CACC_S_POINTER_0_CONSUMER_GROUP_1			_MK_ENUM_CONST(0x1)


// Register NVDLA_CACC_D_OP_ENABLE_0
#define NVDLA_CACC_D_OP_ENABLE_0			_MK_ADDR_CONST(0x7008)
#define NVDLA_CACC_D_OP_ENABLE_0_OP_EN_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CACC_D_OP_ENABLE_0_OP_EN_FIELD			_MK_FIELD_CONST(0x1, NVDLA_CACC_D_OP_ENABLE_0_OP_EN_SHIFT)
#define NVDLA_CACC_D_OP_ENABLE_0_OP_EN_DISABLE			_MK_ENUM_CONST(0x0)
#define NVDLA_CACC_D_OP_ENABLE_0_OP_EN_ENABLE			_MK_ENUM_CONST(0x1)


// Register NVDLA_CACC_D_MISC_CFG_0
#define NVDLA_CACC_D_MISC_CFG_0			_MK_ADDR_CONST(0x700c)
#define NVDLA_CACC_D_MISC_CFG_0_CONV_MODE_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CACC_D_MISC_CFG_0_CONV_MODE_FIELD			_MK_FIELD_CONST(0x1, NVDLA_CACC_D_MISC_CFG_0_CONV_MODE_SHIFT)
#define NVDLA_CACC_D_MISC_CFG_0_CONV_MODE_DIRECT			_MK_ENUM_CONST(0x0)
#define NVDLA_CACC_D_MISC_CFG_0_CONV_MODE_WINOGRAD			_MK_ENUM_CONST(0x1)
#define NVDLA_CACC_D_MISC_CFG_0_PROC_PRECISION_SHIFT			_MK_SHIFT_CONST(12)
#define NVDLA_CACC_D_MISC_CFG_0_PROC_PRECISION_FIELD			_MK_FIELD_CONST(0x3, NVDLA_CACC_D_MISC_CFG_0_PROC_PRECISION_SHIFT)
#define NVDLA_CACC_D_MISC_CFG_0_PROC_PRECISION_INT8			_MK_ENUM_CONST(0x0)
#define NVDLA_CACC_D_MISC_CFG_0_PROC_PRECISION_INT16			_MK_ENUM_CONST(0x1)
#define NVDLA_CACC_D_MISC_CFG_0_PROC_PRECISION_FP16			_MK_ENUM_CONST(0x2)


// Register NVDLA_CACC_D_DATAOUT_SIZE_0_0
#define NVDLA_CACC_D_DATAOUT_SIZE_0_0			_MK_ADDR_CONST(0x7010)
#define NVDLA_CACC_D_DATAOUT_SIZE_0_0_DATAOUT_WIDTH_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CACC_D_DATAOUT_SIZE_0_0_DATAOUT_WIDTH_FIELD			_MK_FIELD_CONST(0x1fff, NVDLA_CACC_D_DATAOUT_SIZE_0_0_DATAOUT_WIDTH_SHIFT)
#define NVDLA_CACC_D_DATAOUT_SIZE_0_0_DATAOUT_HEIGHT_SHIFT			_MK_SHIFT_CONST(16)
#define NVDLA_CACC_D_DATAOUT_SIZE_0_0_DATAOUT_HEIGHT_FIELD			_MK_FIELD_CONST(0x1fff, NVDLA_CACC_D_DATAOUT_SIZE_0_0_DATAOUT_HEIGHT_SHIFT)


// Register NVDLA_CACC_D_DATAOUT_SIZE_1_0
#define NVDLA_CACC_D_DATAOUT_SIZE_1_0			_MK_ADDR_CONST(0x7014)
#define NVDLA_CACC_D_DATAOUT_SIZE_1_0_DATAOUT_CHANNEL_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CACC_D_DATAOUT_SIZE_1_0_DATAOUT_CHANNEL_FIELD			_MK_FIELD_CONST(0x1fff, NVDLA_CACC_D_DATAOUT_SIZE_1_0_DATAOUT_CHANNEL_SHIFT)


// Register NVDLA_CACC_D_DATAOUT_ADDR_0
#define NVDLA_CACC_D_DATAOUT_ADDR_0			_MK_ADDR_CONST(0x7018)
#define NVDLA_CACC_D_DATAOUT_ADDR_0_DATAOUT_ADDR_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CACC_D_DATAOUT_ADDR_0_DATAOUT_ADDR_FIELD			_MK_FIELD_CONST(0xffffffff, NVDLA_CACC_D_DATAOUT_ADDR_0_DATAOUT_ADDR_SHIFT)


// Register NVDLA_CACC_D_BATCH_NUMBER_0
#define NVDLA_CACC_D_BATCH_NUMBER_0			_MK_ADDR_CONST(0x701c)
#define NVDLA_CACC_D_BATCH_NUMBER_0_BATCHES_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CACC_D_BATCH_NUMBER_0_BATCHES_FIELD			_MK_FIELD_CONST(0x1f, NVDLA_CACC_D_BATCH_NUMBER_0_BATCHES_SHIFT)


// Register NVDLA_CACC_D_LINE_STRIDE_0
#define NVDLA_CACC_D_LINE_STRIDE_0			_MK_ADDR_CONST(0x7020)
#define NVDLA_CACC_D_LINE_STRIDE_0_LINE_STRIDE_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CACC_D_LINE_STRIDE_0_LINE_STRIDE_FIELD			_MK_FIELD_CONST(0xffffff, NVDLA_CACC_D_LINE_STRIDE_0_LINE_STRIDE_SHIFT)


// Register NVDLA_CACC_D_SURF_STRIDE_0
#define NVDLA_CACC_D_SURF_STRIDE_0			_MK_ADDR_CONST(0x7024)
#define NVDLA_CACC_D_SURF_STRIDE_0_SURF_STRIDE_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CACC_D_SURF_STRIDE_0_SURF_STRIDE_FIELD			_MK_FIELD_CONST(0xffffff, NVDLA_CACC_D_SURF_STRIDE_0_SURF_STRIDE_SHIFT)


// Register NVDLA_CACC_D_DATAOUT_MAP_0
#define NVDLA_CACC_D_DATAOUT_MAP_0			_MK_ADDR_CONST(0x7028)
#define NVDLA_CACC_D_DATAOUT_MAP_0_LINE_PACKED_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CACC_D_DATAOUT_MAP_0_LINE_PACKED_FIELD			_MK_FIELD_CONST(0x1, NVDLA_CACC_D_DATAOUT_MAP_0_LINE_PACKED_SHIFT)
#define NVDLA_CACC_D_DATAOUT_MAP_0_LINE_PACKED_FALSE			_MK_ENUM_CONST(0x0)
#define NVDLA_CACC_D_DATAOUT_MAP_0_LINE_PACKED_TRUE			_MK_ENUM_CONST(0x1)
#define NVDLA_CACC_D_DATAOUT_MAP_0_SURF_PACKED_SHIFT			_MK_SHIFT_CONST(16)
#define NVDLA_CACC_D_DATAOUT_MAP_0_SURF_PACKED_FIELD			_MK_FIELD_CONST(0x1, NVDLA_CACC_D_DATAOUT_MAP_0_SURF_PACKED_SHIFT)
#define NVDLA_CACC_D_DATAOUT_MAP_0_SURF_PACKED_FALSE			_MK_ENUM_CONST(0x0)
#define NVDLA_CACC_D_DATAOUT_MAP_0_SURF_PACKED_TRUE			_MK_ENUM_CONST(0x1)


// Register NVDLA_CACC_D_CLIP_CFG_0
#define NVDLA_CACC_D_CLIP_CFG_0			_MK_ADDR_CONST(0x702c)
#define NVDLA_CACC_D_CLIP_CFG_0_CLIP_TRUNCATE_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CACC_D_CLIP_CFG_0_CLIP_TRUNCATE_FIELD			_MK_FIELD_CONST(0x1f, NVDLA_CACC_D_CLIP_CFG_0_CLIP_TRUNCATE_SHIFT)


// Register NVDLA_CACC_D_OUT_SATURATION_0
#define NVDLA_CACC_D_OUT_SATURATION_0			_MK_ADDR_CONST(0x7030)
#define NVDLA_CACC_D_OUT_SATURATION_0_SAT_COUNT_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CACC_D_OUT_SATURATION_0_SAT_COUNT_FIELD			_MK_FIELD_CONST(0xffffffff, NVDLA_CACC_D_OUT_SATURATION_0_SAT_COUNT_SHIFT)


// Register NVDLA_CACC_D_CYA_0
#define NVDLA_CACC_D_CYA_0			_MK_ADDR_CONST(0x7034)
#define NVDLA_CACC_D_CYA_0_CYA_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CACC_D_CYA_0_CYA_FIELD			_MK_FIELD_CONST(0xffffffff, NVDLA_CACC_D_CYA_0_CYA_SHIFT)



// To satisfy various compilers and platforms,
// we let users control the types and syntax of certain constants, using macros.
#ifndef _MK_SHIFT_CONST
  #define _MK_SHIFT_CONST(_constant_) _constant_
#endif
#ifndef _MK_MASK_CONST
  #define _MK_MASK_CONST(_constant_) _constant_
#endif
#ifndef _MK_ENUM_CONST
  #define _MK_ENUM_CONST(_constant_) (_constant_ ## UL)
#endif
#ifndef _MK_ADDR_CONST
  #define _MK_ADDR_CONST(_constant_) _constant_
#endif
#ifndef _MK_FIELD_CONST
  #define _MK_FIELD_CONST(_mask_, _shift_) (_MK_MASK_CONST(_mask_) << _MK_SHIFT_CONST(_shift_))
#endif



//
// ADDRESS SPACES
//

#define BASE_ADDRESS_NVDLA_CACC	0x7000
