#if !defined(_csc2cmac_data_if_IFACE)
#define _csc2cmac_data_if_IFACE

#define FLOW_csc2cmac_data_if valid

#define SIG_csc2cmac_data_if_batch_index_WIDTH 5
#define SIG_csc2cmac_data_if_batch_index_FIELD 4:0
#define SIG_csc2cmac_data_if_stripe_st_WIDTH 1
#define SIG_csc2cmac_data_if_stripe_st_FIELD 0:0
#define SIG_csc2cmac_data_if_stripe_end_WIDTH 1
#define SIG_csc2cmac_data_if_stripe_end_FIELD 0:0
#define SIG_csc2cmac_data_if_channel_end_WIDTH 1
#define SIG_csc2cmac_data_if_channel_end_FIELD 0:0
#define SIG_csc2cmac_data_if_layer_end_WIDTH 1
#define SIG_csc2cmac_data_if_layer_end_FIELD 0:0
#define SIG_csc2cmac_data_if_mask_WIDTH 64
#define SIG_csc2cmac_data_if_mask_FIELD 63:0
#define SIG_csc2cmac_data_if_data0_WIDTH 8
#define SIG_csc2cmac_data_if_data0_FIELD 7:0
#define SIG_csc2cmac_data_if_data1_WIDTH 8
#define SIG_csc2cmac_data_if_data1_FIELD 7:0
#define SIG_csc2cmac_data_if_data2_WIDTH 8
#define SIG_csc2cmac_data_if_data2_FIELD 7:0
#define SIG_csc2cmac_data_if_data3_WIDTH 8
#define SIG_csc2cmac_data_if_data3_FIELD 7:0
#define SIG_csc2cmac_data_if_data4_WIDTH 8
#define SIG_csc2cmac_data_if_data4_FIELD 7:0
#define SIG_csc2cmac_data_if_data5_WIDTH 8
#define SIG_csc2cmac_data_if_data5_FIELD 7:0
#define SIG_csc2cmac_data_if_data6_WIDTH 8
#define SIG_csc2cmac_data_if_data6_FIELD 7:0
#define SIG_csc2cmac_data_if_data7_WIDTH 8
#define SIG_csc2cmac_data_if_data7_FIELD 7:0
#define SIG_csc2cmac_data_if_data8_WIDTH 8
#define SIG_csc2cmac_data_if_data8_FIELD 7:0
#define SIG_csc2cmac_data_if_data9_WIDTH 8
#define SIG_csc2cmac_data_if_data9_FIELD 7:0
#define SIG_csc2cmac_data_if_data10_WIDTH 8
#define SIG_csc2cmac_data_if_data10_FIELD 7:0
#define SIG_csc2cmac_data_if_data11_WIDTH 8
#define SIG_csc2cmac_data_if_data11_FIELD 7:0
#define SIG_csc2cmac_data_if_data12_WIDTH 8
#define SIG_csc2cmac_data_if_data12_FIELD 7:0
#define SIG_csc2cmac_data_if_data13_WIDTH 8
#define SIG_csc2cmac_data_if_data13_FIELD 7:0
#define SIG_csc2cmac_data_if_data14_WIDTH 8
#define SIG_csc2cmac_data_if_data14_FIELD 7:0
#define SIG_csc2cmac_data_if_data15_WIDTH 8
#define SIG_csc2cmac_data_if_data15_FIELD 7:0
#define SIG_csc2cmac_data_if_data16_WIDTH 8
#define SIG_csc2cmac_data_if_data16_FIELD 7:0
#define SIG_csc2cmac_data_if_data17_WIDTH 8
#define SIG_csc2cmac_data_if_data17_FIELD 7:0
#define SIG_csc2cmac_data_if_data18_WIDTH 8
#define SIG_csc2cmac_data_if_data18_FIELD 7:0
#define SIG_csc2cmac_data_if_data19_WIDTH 8
#define SIG_csc2cmac_data_if_data19_FIELD 7:0
#define SIG_csc2cmac_data_if_data20_WIDTH 8
#define SIG_csc2cmac_data_if_data20_FIELD 7:0
#define SIG_csc2cmac_data_if_data21_WIDTH 8
#define SIG_csc2cmac_data_if_data21_FIELD 7:0
#define SIG_csc2cmac_data_if_data22_WIDTH 8
#define SIG_csc2cmac_data_if_data22_FIELD 7:0
#define SIG_csc2cmac_data_if_data23_WIDTH 8
#define SIG_csc2cmac_data_if_data23_FIELD 7:0
#define SIG_csc2cmac_data_if_data24_WIDTH 8
#define SIG_csc2cmac_data_if_data24_FIELD 7:0
#define SIG_csc2cmac_data_if_data25_WIDTH 8
#define SIG_csc2cmac_data_if_data25_FIELD 7:0
#define SIG_csc2cmac_data_if_data26_WIDTH 8
#define SIG_csc2cmac_data_if_data26_FIELD 7:0
#define SIG_csc2cmac_data_if_data27_WIDTH 8
#define SIG_csc2cmac_data_if_data27_FIELD 7:0
#define SIG_csc2cmac_data_if_data28_WIDTH 8
#define SIG_csc2cmac_data_if_data28_FIELD 7:0
#define SIG_csc2cmac_data_if_data29_WIDTH 8
#define SIG_csc2cmac_data_if_data29_FIELD 7:0
#define SIG_csc2cmac_data_if_data30_WIDTH 8
#define SIG_csc2cmac_data_if_data30_FIELD 7:0
#define SIG_csc2cmac_data_if_data31_WIDTH 8
#define SIG_csc2cmac_data_if_data31_FIELD 7:0
#define SIG_csc2cmac_data_if_data32_WIDTH 8
#define SIG_csc2cmac_data_if_data32_FIELD 7:0
#define SIG_csc2cmac_data_if_data33_WIDTH 8
#define SIG_csc2cmac_data_if_data33_FIELD 7:0
#define SIG_csc2cmac_data_if_data34_WIDTH 8
#define SIG_csc2cmac_data_if_data34_FIELD 7:0
#define SIG_csc2cmac_data_if_data35_WIDTH 8
#define SIG_csc2cmac_data_if_data35_FIELD 7:0
#define SIG_csc2cmac_data_if_data36_WIDTH 8
#define SIG_csc2cmac_data_if_data36_FIELD 7:0
#define SIG_csc2cmac_data_if_data37_WIDTH 8
#define SIG_csc2cmac_data_if_data37_FIELD 7:0
#define SIG_csc2cmac_data_if_data38_WIDTH 8
#define SIG_csc2cmac_data_if_data38_FIELD 7:0
#define SIG_csc2cmac_data_if_data39_WIDTH 8
#define SIG_csc2cmac_data_if_data39_FIELD 7:0
#define SIG_csc2cmac_data_if_data40_WIDTH 8
#define SIG_csc2cmac_data_if_data40_FIELD 7:0
#define SIG_csc2cmac_data_if_data41_WIDTH 8
#define SIG_csc2cmac_data_if_data41_FIELD 7:0
#define SIG_csc2cmac_data_if_data42_WIDTH 8
#define SIG_csc2cmac_data_if_data42_FIELD 7:0
#define SIG_csc2cmac_data_if_data43_WIDTH 8
#define SIG_csc2cmac_data_if_data43_FIELD 7:0
#define SIG_csc2cmac_data_if_data44_WIDTH 8
#define SIG_csc2cmac_data_if_data44_FIELD 7:0
#define SIG_csc2cmac_data_if_data45_WIDTH 8
#define SIG_csc2cmac_data_if_data45_FIELD 7:0
#define SIG_csc2cmac_data_if_data46_WIDTH 8
#define SIG_csc2cmac_data_if_data46_FIELD 7:0
#define SIG_csc2cmac_data_if_data47_WIDTH 8
#define SIG_csc2cmac_data_if_data47_FIELD 7:0
#define SIG_csc2cmac_data_if_data48_WIDTH 8
#define SIG_csc2cmac_data_if_data48_FIELD 7:0
#define SIG_csc2cmac_data_if_data49_WIDTH 8
#define SIG_csc2cmac_data_if_data49_FIELD 7:0
#define SIG_csc2cmac_data_if_data50_WIDTH 8
#define SIG_csc2cmac_data_if_data50_FIELD 7:0
#define SIG_csc2cmac_data_if_data51_WIDTH 8
#define SIG_csc2cmac_data_if_data51_FIELD 7:0
#define SIG_csc2cmac_data_if_data52_WIDTH 8
#define SIG_csc2cmac_data_if_data52_FIELD 7:0
#define SIG_csc2cmac_data_if_data53_WIDTH 8
#define SIG_csc2cmac_data_if_data53_FIELD 7:0
#define SIG_csc2cmac_data_if_data54_WIDTH 8
#define SIG_csc2cmac_data_if_data54_FIELD 7:0
#define SIG_csc2cmac_data_if_data55_WIDTH 8
#define SIG_csc2cmac_data_if_data55_FIELD 7:0
#define SIG_csc2cmac_data_if_data56_WIDTH 8
#define SIG_csc2cmac_data_if_data56_FIELD 7:0
#define SIG_csc2cmac_data_if_data57_WIDTH 8
#define SIG_csc2cmac_data_if_data57_FIELD 7:0
#define SIG_csc2cmac_data_if_data58_WIDTH 8
#define SIG_csc2cmac_data_if_data58_FIELD 7:0
#define SIG_csc2cmac_data_if_data59_WIDTH 8
#define SIG_csc2cmac_data_if_data59_FIELD 7:0
#define SIG_csc2cmac_data_if_data60_WIDTH 8
#define SIG_csc2cmac_data_if_data60_FIELD 7:0
#define SIG_csc2cmac_data_if_data61_WIDTH 8
#define SIG_csc2cmac_data_if_data61_FIELD 7:0
#define SIG_csc2cmac_data_if_data62_WIDTH 8
#define SIG_csc2cmac_data_if_data62_FIELD 7:0
#define SIG_csc2cmac_data_if_data63_WIDTH 8
#define SIG_csc2cmac_data_if_data63_FIELD 7:0

#endif // !defined(_csc2cmac_data_if_IFACE)