# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /media/fra/DATA/uni/2019-2020/thesis/cogitantium/board_documentation/pynq-z2_v1.0.xdc

# IP: ip/vivado_mac/vivado_mac.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vivado_mac || ORIG_REF_NAME==vivado_mac} -quiet] -quiet

# IP: ip/mult_gen_0/mult_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_gen_0 || ORIG_REF_NAME==mult_gen_0} -quiet] -quiet

# Block Designs: bd/pynqz2/pynqz2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynqz2 || ORIG_REF_NAME==pynqz2} -quiet] -quiet

# IP: bd/pynqz2/ip/pynqz2_ps7_0/pynqz2_ps7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynqz2_ps7_0 || ORIG_REF_NAME==pynqz2_ps7_0} -quiet] -quiet

# IP: bd/pynqz2/ip/pynqz2_rst_ps7_30M_0/pynqz2_rst_ps7_30M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynqz2_rst_ps7_30M_0 || ORIG_REF_NAME==pynqz2_rst_ps7_30M_0} -quiet] -quiet

# IP: bd/pynqz2/ip/pynqz2_xlconstant_0_1/pynqz2_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynqz2_xlconstant_0_1 || ORIG_REF_NAME==pynqz2_xlconstant_0_1} -quiet] -quiet

# IP: bd/pynqz2/ip/pynqz2_util_vector_logic_0_0/pynqz2_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynqz2_util_vector_logic_0_0 || ORIG_REF_NAME==pynqz2_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/pynqz2/ip/pynqz2_dtpu_core_0_0/pynqz2_dtpu_core_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynqz2_dtpu_core_0_0 || ORIG_REF_NAME==pynqz2_dtpu_core_0_0} -quiet] -quiet

# IP: ip/vivado_mac/vivado_mac.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vivado_mac || ORIG_REF_NAME==vivado_mac} -quiet] -quiet

# IP: ip/mult_gen_0/mult_gen_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_gen_0 || ORIG_REF_NAME==mult_gen_0} -quiet] -quiet

# IP: bd/pynqz2/ip/pynqz2_axis_accelerator_ada_0_0/pynqz2_axis_accelerator_ada_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynqz2_axis_accelerator_ada_0_0 || ORIG_REF_NAME==pynqz2_axis_accelerator_ada_0_0} -quiet] -quiet

# IP: bd/pynqz2/ip/pynqz2_axi_dma_0_1/pynqz2_axi_dma_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynqz2_axi_dma_0_1 || ORIG_REF_NAME==pynqz2_axi_dma_0_1} -quiet] -quiet

# IP: bd/pynqz2/ip/pynqz2_xlconcat_0_1/pynqz2_xlconcat_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynqz2_xlconcat_0_1 || ORIG_REF_NAME==pynqz2_xlconcat_0_1} -quiet] -quiet

# IP: bd/pynqz2/ip/pynqz2_axi_dma_0_2/pynqz2_axi_dma_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynqz2_axi_dma_0_2 || ORIG_REF_NAME==pynqz2_axi_dma_0_2} -quiet] -quiet

# IP: bd/pynqz2/ip/pynqz2_axi_intc_0_0/pynqz2_axi_intc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynqz2_axi_intc_0_0 || ORIG_REF_NAME==pynqz2_axi_intc_0_0} -quiet] -quiet

# IP: bd/pynqz2/ip/pynqz2_axi_dma_0_3/pynqz2_axi_dma_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynqz2_axi_dma_0_3 || ORIG_REF_NAME==pynqz2_axi_dma_0_3} -quiet] -quiet

# IP: bd/pynqz2/ip/pynqz2_util_vector_logic_1_2/pynqz2_util_vector_logic_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynqz2_util_vector_logic_1_2 || ORIG_REF_NAME==pynqz2_util_vector_logic_1_2} -quiet] -quiet

# IP: bd/pynqz2/ip/pynqz2_xbar_14/pynqz2_xbar_14.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynqz2_xbar_14 || ORIG_REF_NAME==pynqz2_xbar_14} -quiet] -quiet

# IP: bd/pynqz2/ip/pynqz2_ps7_axi_periph_5/pynqz2_ps7_axi_periph_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynqz2_ps7_axi_periph_5 || ORIG_REF_NAME==pynqz2_ps7_axi_periph_5} -quiet] -quiet

# IP: bd/pynqz2/ip/pynqz2_smartconnect_0_0/pynqz2_smartconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynqz2_smartconnect_0_0 || ORIG_REF_NAME==pynqz2_smartconnect_0_0} -quiet] -quiet

# Block Designs: bd/pynqz2/ip/pynqz2_smartconnect_0_0/bd_0/bd_7d7d.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/pynqz2/ip/pynqz2_smartconnect_0_0/bd_0/ip/ip_0/bd_7d7d_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/pynqz2/ip/pynqz2_smartconnect_0_0/bd_0/ip/ip_1/bd_7d7d_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/pynqz2/ip/pynqz2_smartconnect_0_0/bd_0/ip/ip_2/bd_7d7d_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/pynqz2/ip/pynqz2_smartconnect_0_0/bd_0/ip/ip_3/bd_7d7d_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/pynqz2/ip/pynqz2_smartconnect_0_0/bd_0/ip/ip_4/bd_7d7d_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/pynqz2/ip/pynqz2_smartconnect_0_0/bd_0/ip/ip_5/bd_7d7d_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/pynqz2/ip/pynqz2_smartconnect_0_0/bd_0/ip/ip_6/bd_7d7d_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/pynqz2/ip/pynqz2_smartconnect_0_0/bd_0/ip/ip_7/bd_7d7d_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/pynqz2/ip/pynqz2_smartconnect_0_0/bd_0/ip/ip_8/bd_7d7d_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/pynqz2/ip/pynqz2_smartconnect_0_0/bd_0/ip/ip_9/bd_7d7d_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/pynqz2/ip/pynqz2_smartconnect_0_0/bd_0/ip/ip_10/bd_7d7d_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/pynqz2/ip/pynqz2_smartconnect_0_0/bd_0/ip/ip_11/bd_7d7d_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/pynqz2/ip/pynqz2_smartconnect_0_0/bd_0/ip/ip_12/bd_7d7d_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/pynqz2/ip/pynqz2_smartconnect_0_0/bd_0/ip/ip_13/bd_7d7d_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/pynqz2/ip/pynqz2_smartconnect_0_0/bd_0/ip/ip_14/bd_7d7d_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/pynqz2/ip/pynqz2_smartconnect_0_0/bd_0/ip/ip_15/bd_7d7d_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/pynqz2/ip/pynqz2_smartconnect_0_0/bd_0/ip/ip_16/bd_7d7d_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/pynqz2/ip/pynqz2_smartconnect_0_0/bd_0/ip/ip_17/bd_7d7d_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/pynqz2/ip/pynqz2_smartconnect_0_0/bd_0/ip/ip_18/bd_7d7d_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/pynqz2/ip/pynqz2_smartconnect_0_0/bd_0/ip/ip_19/bd_7d7d_s02mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/pynqz2/ip/pynqz2_smartconnect_0_0/bd_0/ip/ip_20/bd_7d7d_s02tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/pynqz2/ip/pynqz2_smartconnect_0_0/bd_0/ip/ip_21/bd_7d7d_s02sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/pynqz2/ip/pynqz2_smartconnect_0_0/bd_0/ip/ip_22/bd_7d7d_s02a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/pynqz2/ip/pynqz2_smartconnect_0_0/bd_0/ip/ip_23/bd_7d7d_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/pynqz2/ip/pynqz2_smartconnect_0_0/bd_0/ip/ip_24/bd_7d7d_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/pynqz2/ip/pynqz2_smartconnect_0_0/bd_0/ip/ip_25/bd_7d7d_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/pynqz2/ip/pynqz2_smartconnect_0_0/bd_0/ip/ip_26/bd_7d7d_s03mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/pynqz2/ip/pynqz2_smartconnect_0_0/bd_0/ip/ip_27/bd_7d7d_s03tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/pynqz2/ip/pynqz2_smartconnect_0_0/bd_0/ip/ip_28/bd_7d7d_s03sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/pynqz2/ip/pynqz2_smartconnect_0_0/bd_0/ip/ip_29/bd_7d7d_s03a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/pynqz2/ip/pynqz2_smartconnect_0_0/bd_0/ip/ip_30/bd_7d7d_sarn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/pynqz2/ip/pynqz2_smartconnect_0_0/bd_0/ip/ip_31/bd_7d7d_srn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/pynqz2/ip/pynqz2_smartconnect_0_0/bd_0/ip/ip_32/bd_7d7d_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/pynqz2/ip/pynqz2_smartconnect_0_0/bd_0/ip/ip_33/bd_7d7d_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/pynqz2/ip/pynqz2_smartconnect_0_0/bd_0/ip/ip_34/bd_7d7d_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/pynqz2/ip/pynqz2_smartconnect_0_0/bd_0/ip/ip_35/bd_7d7d_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/pynqz2/ip/pynqz2_smartconnect_0_0/bd_0/ip/ip_36/bd_7d7d_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/pynqz2/ip/pynqz2_smartconnect_0_0/bd_0/ip/ip_37/bd_7d7d_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/pynqz2/ip/pynqz2_smartconnect_0_0/bd_0/ip/ip_38/bd_7d7d_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/pynqz2/ip/pynqz2_xlconstant_1_0/pynqz2_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynqz2_xlconstant_1_0 || ORIG_REF_NAME==pynqz2_xlconstant_1_0} -quiet] -quiet

# IP: bd/pynqz2/ip/pynqz2_axi_dma_0_4/pynqz2_axi_dma_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynqz2_axi_dma_0_4 || ORIG_REF_NAME==pynqz2_axi_dma_0_4} -quiet] -quiet

# IP: bd/pynqz2/ip/pynqz2_monitor_0_27/pynqz2_monitor_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynqz2_monitor_0 || ORIG_REF_NAME==pynqz2_monitor_0} -quiet] -quiet

# IP: bd/pynqz2/ip/pynqz2_auto_pc_0/pynqz2_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynqz2_auto_pc_0 || ORIG_REF_NAME==pynqz2_auto_pc_0} -quiet] -quiet

# XDC: bd/pynqz2/ip/pynqz2_ps7_0/pynqz2_ps7_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pynqz2_ps7_0 || ORIG_REF_NAME==pynqz2_ps7_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/pynqz2/ip/pynqz2_rst_ps7_30M_0/pynqz2_rst_ps7_30M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pynqz2_rst_ps7_30M_0 || ORIG_REF_NAME==pynqz2_rst_ps7_30M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/pynqz2/ip/pynqz2_rst_ps7_30M_0/pynqz2_rst_ps7_30M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pynqz2_rst_ps7_30M_0 || ORIG_REF_NAME==pynqz2_rst_ps7_30M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/pynqz2/ip/pynqz2_axis_accelerator_ada_0_0/pynqz2_axis_accelerator_ada_0_0_ooc.xdc

# XDC: bd/pynqz2/ip/pynqz2_axis_accelerator_ada_0_0/pynqz2_axis_accelerator_ada_0_0_xdc_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pynqz2_axis_accelerator_ada_0_0 || ORIG_REF_NAME==pynqz2_axis_accelerator_ada_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/pynqz2/ip/pynqz2_axis_accelerator_ada_0_0/pynqz2_axis_accelerator_ada_0_0_xdc.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pynqz2_axis_accelerator_ada_0_0 || ORIG_REF_NAME==pynqz2_axis_accelerator_ada_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/pynqz2/ip/pynqz2_axi_dma_0_1/pynqz2_axi_dma_0_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pynqz2_axi_dma_0_1 || ORIG_REF_NAME==pynqz2_axi_dma_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/pynqz2/ip/pynqz2_axi_dma_0_1/pynqz2_axi_dma_0_1_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pynqz2_axi_dma_0_1 || ORIG_REF_NAME==pynqz2_axi_dma_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/pynqz2/ip/pynqz2_axi_dma_0_2/pynqz2_axi_dma_0_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pynqz2_axi_dma_0_2 || ORIG_REF_NAME==pynqz2_axi_dma_0_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/pynqz2/ip/pynqz2_axi_dma_0_2/pynqz2_axi_dma_0_2_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pynqz2_axi_dma_0_2 || ORIG_REF_NAME==pynqz2_axi_dma_0_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/pynqz2/ip/pynqz2_axi_intc_0_0/pynqz2_axi_intc_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pynqz2_axi_intc_0_0 || ORIG_REF_NAME==pynqz2_axi_intc_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/pynqz2/ip/pynqz2_axi_intc_0_0/pynqz2_axi_intc_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pynqz2_axi_intc_0_0 || ORIG_REF_NAME==pynqz2_axi_intc_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/pynqz2/ip/pynqz2_axi_intc_0_0/pynqz2_axi_intc_0_0_ooc.xdc

# XDC: bd/pynqz2/ip/pynqz2_axi_dma_0_3/pynqz2_axi_dma_0_3.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pynqz2_axi_dma_0_3 || ORIG_REF_NAME==pynqz2_axi_dma_0_3} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/pynqz2/ip/pynqz2_axi_dma_0_3/pynqz2_axi_dma_0_3_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pynqz2_axi_dma_0_3 || ORIG_REF_NAME==pynqz2_axi_dma_0_3} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/pynqz2/ip/pynqz2_smartconnect_0_0/bd_0/ip/ip_1/bd_7d7d_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/pynqz2/ip/pynqz2_smartconnect_0_0/bd_0/ip/ip_1/bd_7d7d_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/pynqz2/ip/pynqz2_smartconnect_0_0/bd_0/ip/ip_2/bd_7d7d_arsw_0_ooc.xdc

# XDC: bd/pynqz2/ip/pynqz2_smartconnect_0_0/bd_0/ip/ip_3/bd_7d7d_rsw_0_ooc.xdc

# XDC: bd/pynqz2/ip/pynqz2_smartconnect_0_0/bd_0/ip/ip_4/bd_7d7d_awsw_0_ooc.xdc

# XDC: bd/pynqz2/ip/pynqz2_smartconnect_0_0/bd_0/ip/ip_5/bd_7d7d_wsw_0_ooc.xdc

# XDC: bd/pynqz2/ip/pynqz2_smartconnect_0_0/bd_0/ip/ip_6/bd_7d7d_bsw_0_ooc.xdc

# XDC: bd/pynqz2/ip/pynqz2_smartconnect_0_0/bd_0/ip/ip_10/bd_7d7d_s00a2s_0_ooc.xdc

# XDC: bd/pynqz2/ip/pynqz2_smartconnect_0_0/bd_0/ip/ip_11/bd_7d7d_sarn_0_ooc.xdc

# XDC: bd/pynqz2/ip/pynqz2_smartconnect_0_0/bd_0/ip/ip_12/bd_7d7d_srn_0_ooc.xdc

# XDC: bd/pynqz2/ip/pynqz2_smartconnect_0_0/bd_0/ip/ip_16/bd_7d7d_s01a2s_0_ooc.xdc

# XDC: bd/pynqz2/ip/pynqz2_smartconnect_0_0/bd_0/ip/ip_17/bd_7d7d_sarn_1_ooc.xdc

# XDC: bd/pynqz2/ip/pynqz2_smartconnect_0_0/bd_0/ip/ip_18/bd_7d7d_srn_1_ooc.xdc

# XDC: bd/pynqz2/ip/pynqz2_smartconnect_0_0/bd_0/ip/ip_22/bd_7d7d_s02a2s_0_ooc.xdc

# XDC: bd/pynqz2/ip/pynqz2_smartconnect_0_0/bd_0/ip/ip_23/bd_7d7d_sawn_0_ooc.xdc

# XDC: bd/pynqz2/ip/pynqz2_smartconnect_0_0/bd_0/ip/ip_24/bd_7d7d_swn_0_ooc.xdc

# XDC: bd/pynqz2/ip/pynqz2_smartconnect_0_0/bd_0/ip/ip_25/bd_7d7d_sbn_0_ooc.xdc

# XDC: bd/pynqz2/ip/pynqz2_smartconnect_0_0/bd_0/ip/ip_29/bd_7d7d_s03a2s_0_ooc.xdc

# XDC: bd/pynqz2/ip/pynqz2_smartconnect_0_0/bd_0/ip/ip_30/bd_7d7d_sarn_2_ooc.xdc

# XDC: bd/pynqz2/ip/pynqz2_smartconnect_0_0/bd_0/ip/ip_31/bd_7d7d_srn_2_ooc.xdc

# XDC: bd/pynqz2/ip/pynqz2_smartconnect_0_0/bd_0/ip/ip_32/bd_7d7d_m00s2a_0_ooc.xdc

# XDC: bd/pynqz2/ip/pynqz2_smartconnect_0_0/bd_0/ip/ip_33/bd_7d7d_m00arn_0_ooc.xdc

# XDC: bd/pynqz2/ip/pynqz2_smartconnect_0_0/bd_0/ip/ip_34/bd_7d7d_m00rn_0_ooc.xdc

# XDC: bd/pynqz2/ip/pynqz2_smartconnect_0_0/bd_0/ip/ip_35/bd_7d7d_m00awn_0_ooc.xdc

# XDC: bd/pynqz2/ip/pynqz2_smartconnect_0_0/bd_0/ip/ip_36/bd_7d7d_m00wn_0_ooc.xdc

# XDC: bd/pynqz2/ip/pynqz2_smartconnect_0_0/bd_0/ip/ip_37/bd_7d7d_m00bn_0_ooc.xdc

# XDC: bd/pynqz2/ip/pynqz2_smartconnect_0_0/ooc.xdc

# XDC: bd/pynqz2/ip/pynqz2_axi_dma_0_4/pynqz2_axi_dma_0_4.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pynqz2_axi_dma_0_4 || ORIG_REF_NAME==pynqz2_axi_dma_0_4} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/pynqz2/ip/pynqz2_axi_dma_0_4/pynqz2_axi_dma_0_4_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pynqz2_axi_dma_0_4 || ORIG_REF_NAME==pynqz2_axi_dma_0_4} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/pynqz2/ip/pynqz2_axi_dma_0_4/pynqz2_axi_dma_0_4_ooc.xdc

# XDC: bd/pynqz2/ip/pynqz2_monitor_0_27/pynqz2_monitor_0_ooc.xdc

# XDC: bd/pynqz2/ip/pynqz2_monitor_0_27/pynqz2_monitor_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pynqz2_monitor_0 || ORIG_REF_NAME==pynqz2_monitor_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/pynqz2/ip/pynqz2_auto_pc_0/pynqz2_auto_pc_0_ooc.xdc

# XDC: bd/pynqz2/pynqz2_ooc.xdc
