webtalk_init -webtalk_dir /media/fra/DATA/uni/2019-2020/thesis/cogitantium/nvdla/nv_small_512_32_16_8_int8/pynqz2.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2020-02-25 19:19:41" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2019.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2019.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211614688_0_0_264" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "96jikmbijepv5fp8g6tbm3s1e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2019.1_1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 16.04.6 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2845.375 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16,682 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1582654717000" -context "sdk\\\\hardware/1582654717000"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1582654717000"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1582654717000"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1582654717000"
webtalk_add_data -client sdk -key VivadoVersion -value "2019.1" -context "sdk\\\\hardware/1582654717000"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1582654717000"
webtalk_add_data -client sdk -key Device -value "7z020" -context "sdk\\\\hardware/1582654717000"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1582654717000"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1582654717000"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1582654717000"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1582654717000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1582654771321"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1582654771321"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1582654771321"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1582654771321"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1582654771321"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1582654771321"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1582654771321"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1582654771321"
webtalk_transmit -clientid 3016586097 -regid "211614688_0_0_264" -xml /media/fra/DATA/uni/2019-2020/thesis/cogitantium/nvdla/nv_small_512_32_16_8_int8/pynqz2.sdk/webtalk/usage_statistics_ext_sdk.xml -html /media/fra/DATA/uni/2019-2020/thesis/cogitantium/nvdla/nv_small_512_32_16_8_int8/pynqz2.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /media/fra/DATA/uni/2019-2020/thesis/cogitantium/nvdla/nv_small_512_32_16_8_int8/pynqz2.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
