# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/avoid_trimmer.xdc

# Block Designs: bd/pynqz2/pynqz2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynqz2 || ORIG_REF_NAME==pynqz2} -quiet] -quiet

# IP: bd/pynqz2/ip/pynqz2_ps7_0/pynqz2_ps7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynqz2_ps7_0 || ORIG_REF_NAME==pynqz2_ps7_0} -quiet] -quiet

# IP: bd/pynqz2/ip/pynqz2_rst_ps7_30M_0/pynqz2_rst_ps7_30M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynqz2_rst_ps7_30M_0 || ORIG_REF_NAME==pynqz2_rst_ps7_30M_0} -quiet] -quiet

# IP: bd/pynqz2/ip/pynqz2_axi_mem_intercon_0/pynqz2_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynqz2_axi_mem_intercon_0 || ORIG_REF_NAME==pynqz2_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/pynqz2/ip/pynqz2_xlconstant_0_1/pynqz2_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynqz2_xlconstant_0_1 || ORIG_REF_NAME==pynqz2_xlconstant_0_1} -quiet] -quiet

# IP: bd/pynqz2/ip/pynqz2_nv_nvdla_wrapper_0_3/pynqz2_nv_nvdla_wrapper_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynqz2_nv_nvdla_wrapper_0_3 || ORIG_REF_NAME==pynqz2_nv_nvdla_wrapper_0_3} -quiet] -quiet

# IP: bd/pynqz2/ip/pynqz2_axi_smc_4/pynqz2_axi_smc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynqz2_axi_smc_4 || ORIG_REF_NAME==pynqz2_axi_smc_4} -quiet] -quiet

# Block Designs: bd/pynqz2/ip/pynqz2_axi_smc_4/bd_0/bd_9057.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/pynqz2/ip/pynqz2_axi_smc_4/bd_0/ip/ip_0/bd_9057_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/pynqz2/ip/pynqz2_axi_smc_4/bd_0/ip/ip_1/bd_9057_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/pynqz2/ip/pynqz2_axi_smc_4/bd_0/ip/ip_2/bd_9057_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/pynqz2/ip/pynqz2_axi_smc_4/bd_0/ip/ip_3/bd_9057_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/pynqz2/ip/pynqz2_axi_smc_4/bd_0/ip/ip_4/bd_9057_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/pynqz2/ip/pynqz2_axi_smc_4/bd_0/ip/ip_5/bd_9057_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/pynqz2/ip/pynqz2_axi_smc_4/bd_0/ip/ip_6/bd_9057_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/pynqz2/ip/pynqz2_axi_smc_4/bd_0/ip/ip_7/bd_9057_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/pynqz2/ip/pynqz2_axi_smc_4/bd_0/ip/ip_8/bd_9057_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/pynqz2/ip/pynqz2_axi_smc_4/bd_0/ip/ip_9/bd_9057_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/pynqz2/ip/pynqz2_axi_smc_4/bd_0/ip/ip_10/bd_9057_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/pynqz2/ip/pynqz2_axi_smc_4/bd_0/ip/ip_11/bd_9057_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/pynqz2/ip/pynqz2_axi_smc_4/bd_0/ip/ip_12/bd_9057_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/pynqz2/ip/pynqz2_axi_apb_bridge_0_3/pynqz2_axi_apb_bridge_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynqz2_axi_apb_bridge_0_3 || ORIG_REF_NAME==pynqz2_axi_apb_bridge_0_3} -quiet] -quiet

# IP: bd/pynqz2/ip/pynqz2_auto_pc_0/pynqz2_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynqz2_auto_pc_0 || ORIG_REF_NAME==pynqz2_auto_pc_0} -quiet] -quiet

# XDC: bd/pynqz2/ip/pynqz2_ps7_0/pynqz2_ps7_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pynqz2_ps7_0 || ORIG_REF_NAME==pynqz2_ps7_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/pynqz2/ip/pynqz2_rst_ps7_30M_0/pynqz2_rst_ps7_30M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pynqz2_rst_ps7_30M_0 || ORIG_REF_NAME==pynqz2_rst_ps7_30M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/pynqz2/ip/pynqz2_rst_ps7_30M_0/pynqz2_rst_ps7_30M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pynqz2_rst_ps7_30M_0 || ORIG_REF_NAME==pynqz2_rst_ps7_30M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/pynqz2/ip/pynqz2_axi_smc_4/ooc.xdc

# XDC: bd/pynqz2/ip/pynqz2_axi_smc_4/bd_0/ip/ip_1/bd_9057_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/pynqz2/ip/pynqz2_axi_smc_4/bd_0/ip/ip_1/bd_9057_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/pynqz2/ip/pynqz2_axi_smc_4/bd_0/ip/ip_5/bd_9057_s00a2s_0_ooc.xdc

# XDC: bd/pynqz2/ip/pynqz2_axi_smc_4/bd_0/ip/ip_6/bd_9057_sarn_0_ooc.xdc

# XDC: bd/pynqz2/ip/pynqz2_axi_smc_4/bd_0/ip/ip_7/bd_9057_srn_0_ooc.xdc

# XDC: bd/pynqz2/ip/pynqz2_axi_smc_4/bd_0/ip/ip_8/bd_9057_sawn_0_ooc.xdc

# XDC: bd/pynqz2/ip/pynqz2_axi_smc_4/bd_0/ip/ip_9/bd_9057_swn_0_ooc.xdc

# XDC: bd/pynqz2/ip/pynqz2_axi_smc_4/bd_0/ip/ip_10/bd_9057_sbn_0_ooc.xdc

# XDC: bd/pynqz2/ip/pynqz2_axi_smc_4/bd_0/ip/ip_11/bd_9057_m00s2a_0_ooc.xdc

# XDC: bd/pynqz2/ip/pynqz2_axi_apb_bridge_0_3/pynqz2_axi_apb_bridge_0_3_ooc.xdc

# XDC: bd/pynqz2/ip/pynqz2_auto_pc_0/pynqz2_auto_pc_0_ooc.xdc

# XDC: bd/pynqz2/pynqz2_ooc.xdc
