# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/fra/Desktop/PYNQ/sdbuild/build/Pynq-Z2/petalinux_bsp/hardware_project/pynqz2/pynqz2.srcs/sources_1/bd/pynqz2/ip/pynqz2_ps7_0/pynqz2_ps7_0.xci
# IP: The module: 'pynqz2_ps7_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/fra/Desktop/PYNQ/sdbuild/build/Pynq-Z2/petalinux_bsp/hardware_project/pynqz2/pynqz2.srcs/sources_1/bd/pynqz2/ip/pynqz2_ps7_0/pynqz2_ps7_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'pynqz2_ps7_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/fra/Desktop/PYNQ/sdbuild/build/Pynq-Z2/petalinux_bsp/hardware_project/pynqz2/pynqz2.srcs/sources_1/bd/pynqz2/ip/pynqz2_ps7_0/pynqz2_ps7_0.xci
# IP: The module: 'pynqz2_ps7_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/fra/Desktop/PYNQ/sdbuild/build/Pynq-Z2/petalinux_bsp/hardware_project/pynqz2/pynqz2.srcs/sources_1/bd/pynqz2/ip/pynqz2_ps7_0/pynqz2_ps7_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'pynqz2_ps7_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
