#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sat Mar 21 19:37:51 CET 2020
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim tb_mxu_core_behav -key {Behavioral:sim_1:Functional:tb_mxu_core} -tclbatch tb_mxu_core.tcl -protoinst "protoinst_files/bd_7d7d.protoinst" -log simulate.log"
xsim tb_mxu_core_behav -key {Behavioral:sim_1:Functional:tb_mxu_core} -tclbatch tb_mxu_core.tcl -protoinst "protoinst_files/bd_7d7d.protoinst" -log simulate.log

