# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/uni/2019-2020/thesis/cogitantium/board_documentation/pynq-z2_v1.0.xdc

# IP: ip/processing_system7_0_1/processing_system7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==processing_system7_0 || ORIG_REF_NAME==processing_system7_0} -quiet] -quiet

# XDC: ip/processing_system7_0_1/processing_system7_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==processing_system7_0 || ORIG_REF_NAME==processing_system7_0} -quiet] {/inst } ]/inst ] -quiet] -quiet
