// Register NVDLA_BDMA_CFG_SRC_ADDR_LOW_0
#define NVDLA_BDMA_CFG_SRC_ADDR_LOW_0			_MK_ADDR_CONST(0x10000)
#define NVDLA_BDMA_CFG_SRC_ADDR_LOW_0_V32_SHIFT			_MK_SHIFT_CONST(5)
#define NVDLA_BDMA_CFG_SRC_ADDR_LOW_0_V32_FIELD			_MK_FIELD_CONST(0x7ffffff, NVDLA_BDMA_CFG_SRC_ADDR_LOW_0_V32_SHIFT)


// Register NVDLA_BDMA_CFG_SRC_ADDR_HIGH_0
#define NVDLA_BDMA_CFG_SRC_ADDR_HIGH_0			_MK_ADDR_CONST(0x10004)
#define NVDLA_BDMA_CFG_SRC_ADDR_HIGH_0_V8_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_BDMA_CFG_SRC_ADDR_HIGH_0_V8_FIELD			_MK_FIELD_CONST(0xffffffff, NVDLA_BDMA_CFG_SRC_ADDR_HIGH_0_V8_SHIFT)


// Register NVDLA_BDMA_CFG_DST_ADDR_LOW_0
#define NVDLA_BDMA_CFG_DST_ADDR_LOW_0			_MK_ADDR_CONST(0x10008)
#define NVDLA_BDMA_CFG_DST_ADDR_LOW_0_V32_SHIFT			_MK_SHIFT_CONST(5)
#define NVDLA_BDMA_CFG_DST_ADDR_LOW_0_V32_FIELD			_MK_FIELD_CONST(0x7ffffff, NVDLA_BDMA_CFG_DST_ADDR_LOW_0_V32_SHIFT)


// Register NVDLA_BDMA_CFG_DST_ADDR_HIGH_0
#define NVDLA_BDMA_CFG_DST_ADDR_HIGH_0			_MK_ADDR_CONST(0x1000c)
#define NVDLA_BDMA_CFG_DST_ADDR_HIGH_0_V8_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_BDMA_CFG_DST_ADDR_HIGH_0_V8_FIELD			_MK_FIELD_CONST(0xffffffff, NVDLA_BDMA_CFG_DST_ADDR_HIGH_0_V8_SHIFT)


// Register NVDLA_BDMA_CFG_LINE_0
#define NVDLA_BDMA_CFG_LINE_0			_MK_ADDR_CONST(0x10010)
#define NVDLA_BDMA_CFG_LINE_0_SIZE_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_BDMA_CFG_LINE_0_SIZE_FIELD			_MK_FIELD_CONST(0x1fff, NVDLA_BDMA_CFG_LINE_0_SIZE_SHIFT)


// Register NVDLA_BDMA_CFG_CMD_0
#define NVDLA_BDMA_CFG_CMD_0			_MK_ADDR_CONST(0x10014)
#define NVDLA_BDMA_CFG_CMD_0_SRC_RAM_TYPE_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_BDMA_CFG_CMD_0_SRC_RAM_TYPE_FIELD			_MK_FIELD_CONST(0x1, NVDLA_BDMA_CFG_CMD_0_SRC_RAM_TYPE_SHIFT)
#define NVDLA_BDMA_CFG_CMD_0_SRC_RAM_TYPE_CVSRAM			_MK_ENUM_CONST(0x0)
#define NVDLA_BDMA_CFG_CMD_0_SRC_RAM_TYPE_MC			_MK_ENUM_CONST(0x1)
#define NVDLA_BDMA_CFG_CMD_0_DST_RAM_TYPE_SHIFT			_MK_SHIFT_CONST(1)
#define NVDLA_BDMA_CFG_CMD_0_DST_RAM_TYPE_FIELD			_MK_FIELD_CONST(0x1, NVDLA_BDMA_CFG_CMD_0_DST_RAM_TYPE_SHIFT)
#define NVDLA_BDMA_CFG_CMD_0_DST_RAM_TYPE_CVSRAM			_MK_ENUM_CONST(0x0)
#define NVDLA_BDMA_CFG_CMD_0_DST_RAM_TYPE_MC			_MK_ENUM_CONST(0x1)


// Register NVDLA_BDMA_CFG_LINE_REPEAT_0
#define NVDLA_BDMA_CFG_LINE_REPEAT_0			_MK_ADDR_CONST(0x10018)
#define NVDLA_BDMA_CFG_LINE_REPEAT_0_NUMBER_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_BDMA_CFG_LINE_REPEAT_0_NUMBER_FIELD			_MK_FIELD_CONST(0xffffff, NVDLA_BDMA_CFG_LINE_REPEAT_0_NUMBER_SHIFT)


// Register NVDLA_BDMA_CFG_SRC_LINE_0
#define NVDLA_BDMA_CFG_SRC_LINE_0			_MK_ADDR_CONST(0x1001c)
#define NVDLA_BDMA_CFG_SRC_LINE_0_STRIDE_SHIFT			_MK_SHIFT_CONST(5)
#define NVDLA_BDMA_CFG_SRC_LINE_0_STRIDE_FIELD			_MK_FIELD_CONST(0x7ffffff, NVDLA_BDMA_CFG_SRC_LINE_0_STRIDE_SHIFT)


// Register NVDLA_BDMA_CFG_DST_LINE_0
#define NVDLA_BDMA_CFG_DST_LINE_0			_MK_ADDR_CONST(0x10020)
#define NVDLA_BDMA_CFG_DST_LINE_0_STRIDE_SHIFT			_MK_SHIFT_CONST(5)
#define NVDLA_BDMA_CFG_DST_LINE_0_STRIDE_FIELD			_MK_FIELD_CONST(0x7ffffff, NVDLA_BDMA_CFG_DST_LINE_0_STRIDE_SHIFT)


// Register NVDLA_BDMA_CFG_SURF_REPEAT_0
#define NVDLA_BDMA_CFG_SURF_REPEAT_0			_MK_ADDR_CONST(0x10024)
#define NVDLA_BDMA_CFG_SURF_REPEAT_0_NUMBER_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_BDMA_CFG_SURF_REPEAT_0_NUMBER_FIELD			_MK_FIELD_CONST(0xffffff, NVDLA_BDMA_CFG_SURF_REPEAT_0_NUMBER_SHIFT)


// Register NVDLA_BDMA_CFG_SRC_SURF_0
#define NVDLA_BDMA_CFG_SRC_SURF_0			_MK_ADDR_CONST(0x10028)
#define NVDLA_BDMA_CFG_SRC_SURF_0_STRIDE_SHIFT			_MK_SHIFT_CONST(5)
#define NVDLA_BDMA_CFG_SRC_SURF_0_STRIDE_FIELD			_MK_FIELD_CONST(0x7ffffff, NVDLA_BDMA_CFG_SRC_SURF_0_STRIDE_SHIFT)


// Register NVDLA_BDMA_CFG_DST_SURF_0
#define NVDLA_BDMA_CFG_DST_SURF_0			_MK_ADDR_CONST(0x1002c)
#define NVDLA_BDMA_CFG_DST_SURF_0_STRIDE_SHIFT			_MK_SHIFT_CONST(5)
#define NVDLA_BDMA_CFG_DST_SURF_0_STRIDE_FIELD			_MK_FIELD_CONST(0x7ffffff, NVDLA_BDMA_CFG_DST_SURF_0_STRIDE_SHIFT)


// Register NVDLA_BDMA_CFG_OP_0
#define NVDLA_BDMA_CFG_OP_0			_MK_ADDR_CONST(0x10030)
#define NVDLA_BDMA_CFG_OP_0_EN_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_BDMA_CFG_OP_0_EN_FIELD			_MK_FIELD_CONST(0x1, NVDLA_BDMA_CFG_OP_0_EN_SHIFT)
#define NVDLA_BDMA_CFG_OP_0_EN_DISABLE			_MK_ENUM_CONST(0x0)
#define NVDLA_BDMA_CFG_OP_0_EN_ENABLE			_MK_ENUM_CONST(0x1)


// Register NVDLA_BDMA_CFG_LAUNCH0_0
#define NVDLA_BDMA_CFG_LAUNCH0_0			_MK_ADDR_CONST(0x10034)
#define NVDLA_BDMA_CFG_LAUNCH0_0_GRP0_LAUNCH_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_BDMA_CFG_LAUNCH0_0_GRP0_LAUNCH_FIELD			_MK_FIELD_CONST(0x1, NVDLA_BDMA_CFG_LAUNCH0_0_GRP0_LAUNCH_SHIFT)
#define NVDLA_BDMA_CFG_LAUNCH0_0_GRP0_LAUNCH_NO			_MK_ENUM_CONST(0x0)
#define NVDLA_BDMA_CFG_LAUNCH0_0_GRP0_LAUNCH_YES			_MK_ENUM_CONST(0x1)


// Register NVDLA_BDMA_CFG_LAUNCH1_0
#define NVDLA_BDMA_CFG_LAUNCH1_0			_MK_ADDR_CONST(0x10038)
#define NVDLA_BDMA_CFG_LAUNCH1_0_GRP1_LAUNCH_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_BDMA_CFG_LAUNCH1_0_GRP1_LAUNCH_FIELD			_MK_FIELD_CONST(0x1, NVDLA_BDMA_CFG_LAUNCH1_0_GRP1_LAUNCH_SHIFT)
#define NVDLA_BDMA_CFG_LAUNCH1_0_GRP1_LAUNCH_NO			_MK_ENUM_CONST(0x0)
#define NVDLA_BDMA_CFG_LAUNCH1_0_GRP1_LAUNCH_YES			_MK_ENUM_CONST(0x1)


// Register NVDLA_BDMA_CFG_STATUS_0
#define NVDLA_BDMA_CFG_STATUS_0			_MK_ADDR_CONST(0x1003c)
#define NVDLA_BDMA_CFG_STATUS_0_STALL_COUNT_EN_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_BDMA_CFG_STATUS_0_STALL_COUNT_EN_FIELD			_MK_FIELD_CONST(0x1, NVDLA_BDMA_CFG_STATUS_0_STALL_COUNT_EN_SHIFT)
#define NVDLA_BDMA_CFG_STATUS_0_STALL_COUNT_EN_NO			_MK_ENUM_CONST(0x0)
#define NVDLA_BDMA_CFG_STATUS_0_STALL_COUNT_EN_YES			_MK_ENUM_CONST(0x1)


// Register NVDLA_BDMA_STATUS_0
#define NVDLA_BDMA_STATUS_0			_MK_ADDR_CONST(0x10040)
#define NVDLA_BDMA_STATUS_0_FREE_SLOT_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_BDMA_STATUS_0_FREE_SLOT_FIELD			_MK_FIELD_CONST(0xff, NVDLA_BDMA_STATUS_0_FREE_SLOT_SHIFT)
#define NVDLA_BDMA_STATUS_0_IDLE_SHIFT			_MK_SHIFT_CONST(8)
#define NVDLA_BDMA_STATUS_0_IDLE_FIELD			_MK_FIELD_CONST(0x1, NVDLA_BDMA_STATUS_0_IDLE_SHIFT)
#define NVDLA_BDMA_STATUS_0_IDLE_NO			_MK_ENUM_CONST(0x0)
#define NVDLA_BDMA_STATUS_0_IDLE_YES			_MK_ENUM_CONST(0x1)
#define NVDLA_BDMA_STATUS_0_GRP0_BUSY_SHIFT			_MK_SHIFT_CONST(9)
#define NVDLA_BDMA_STATUS_0_GRP0_BUSY_FIELD			_MK_FIELD_CONST(0x1, NVDLA_BDMA_STATUS_0_GRP0_BUSY_SHIFT)
#define NVDLA_BDMA_STATUS_0_GRP0_BUSY_NO			_MK_ENUM_CONST(0x0)
#define NVDLA_BDMA_STATUS_0_GRP0_BUSY_YES			_MK_ENUM_CONST(0x1)
#define NVDLA_BDMA_STATUS_0_GRP1_BUSY_SHIFT			_MK_SHIFT_CONST(10)
#define NVDLA_BDMA_STATUS_0_GRP1_BUSY_FIELD			_MK_FIELD_CONST(0x1, NVDLA_BDMA_STATUS_0_GRP1_BUSY_SHIFT)
#define NVDLA_BDMA_STATUS_0_GRP1_BUSY_NO			_MK_ENUM_CONST(0x0)
#define NVDLA_BDMA_STATUS_0_GRP1_BUSY_YES			_MK_ENUM_CONST(0x1)


// Register NVDLA_BDMA_STATUS_GRP0_READ_STALL_0
#define NVDLA_BDMA_STATUS_GRP0_READ_STALL_0			_MK_ADDR_CONST(0x10044)
#define NVDLA_BDMA_STATUS_GRP0_READ_STALL_0_COUNT_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_BDMA_STATUS_GRP0_READ_STALL_0_COUNT_FIELD			_MK_FIELD_CONST(0xffffffff, NVDLA_BDMA_STATUS_GRP0_READ_STALL_0_COUNT_SHIFT)


// Register NVDLA_BDMA_STATUS_GRP0_WRITE_STALL_0
#define NVDLA_BDMA_STATUS_GRP0_WRITE_STALL_0			_MK_ADDR_CONST(0x10048)
#define NVDLA_BDMA_STATUS_GRP0_WRITE_STALL_0_COUNT_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_BDMA_STATUS_GRP0_WRITE_STALL_0_COUNT_FIELD			_MK_FIELD_CONST(0xffffffff, NVDLA_BDMA_STATUS_GRP0_WRITE_STALL_0_COUNT_SHIFT)


// Register NVDLA_BDMA_STATUS_GRP1_READ_STALL_0
#define NVDLA_BDMA_STATUS_GRP1_READ_STALL_0			_MK_ADDR_CONST(0x1004c)
#define NVDLA_BDMA_STATUS_GRP1_READ_STALL_0_COUNT_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_BDMA_STATUS_GRP1_READ_STALL_0_COUNT_FIELD			_MK_FIELD_CONST(0xffffffff, NVDLA_BDMA_STATUS_GRP1_READ_STALL_0_COUNT_SHIFT)


// Register NVDLA_BDMA_STATUS_GRP1_WRITE_STALL_0
#define NVDLA_BDMA_STATUS_GRP1_WRITE_STALL_0			_MK_ADDR_CONST(0x10050)
#define NVDLA_BDMA_STATUS_GRP1_WRITE_STALL_0_COUNT_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_BDMA_STATUS_GRP1_WRITE_STALL_0_COUNT_FIELD			_MK_FIELD_CONST(0xffffffff, NVDLA_BDMA_STATUS_GRP1_WRITE_STALL_0_COUNT_SHIFT)



// To satisfy various compilers and platforms,
// we let users control the types and syntax of certain constants, using macros.
#ifndef _MK_SHIFT_CONST
  #define _MK_SHIFT_CONST(_constant_) _constant_
#endif
#ifndef _MK_MASK_CONST
  #define _MK_MASK_CONST(_constant_) _constant_
#endif
#ifndef _MK_ENUM_CONST
  #define _MK_ENUM_CONST(_constant_) (_constant_ ## UL)
#endif
#ifndef _MK_ADDR_CONST
  #define _MK_ADDR_CONST(_constant_) _constant_
#endif
#ifndef _MK_FIELD_CONST
  #define _MK_FIELD_CONST(_mask_, _shift_) (_MK_MASK_CONST(_mask_) << _MK_SHIFT_CONST(_shift_))
#endif



//
// ADDRESS SPACES
//

#define BASE_ADDRESS_NVDLA_BDMA	0x10000
