// Register NVDLA_RBK_S_STATUS_0
#define NVDLA_RBK_S_STATUS_0			_MK_ADDR_CONST(0x11000)
#define NVDLA_RBK_S_STATUS_0_STATUS_0_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_RBK_S_STATUS_0_STATUS_0_FIELD			_MK_FIELD_CONST(0x3, NVDLA_RBK_S_STATUS_0_STATUS_0_SHIFT)
#define NVDLA_RBK_S_STATUS_0_STATUS_0_IDLE			_MK_ENUM_CONST(0x0)
#define NVDLA_RBK_S_STATUS_0_STATUS_0_RUNNING			_MK_ENUM_CONST(0x1)
#define NVDLA_RBK_S_STATUS_0_STATUS_0_PENDING			_MK_ENUM_CONST(0x2)
#define NVDLA_RBK_S_STATUS_0_STATUS_1_SHIFT			_MK_SHIFT_CONST(16)
#define NVDLA_RBK_S_STATUS_0_STATUS_1_FIELD			_MK_FIELD_CONST(0x3, NVDLA_RBK_S_STATUS_0_STATUS_1_SHIFT)
#define NVDLA_RBK_S_STATUS_0_STATUS_1_IDLE			_MK_ENUM_CONST(0x0)
#define NVDLA_RBK_S_STATUS_0_STATUS_1_RUNNING			_MK_ENUM_CONST(0x1)
#define NVDLA_RBK_S_STATUS_0_STATUS_1_PENDING			_MK_ENUM_CONST(0x2)


// Register NVDLA_RBK_S_POINTER_0
#define NVDLA_RBK_S_POINTER_0			_MK_ADDR_CONST(0x11004)
#define NVDLA_RBK_S_POINTER_0_PRODUCER_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_RBK_S_POINTER_0_PRODUCER_FIELD			_MK_FIELD_CONST(0x1, NVDLA_RBK_S_POINTER_0_PRODUCER_SHIFT)
#define NVDLA_RBK_S_POINTER_0_PRODUCER_GROUP_0			_MK_ENUM_CONST(0x0)
#define NVDLA_RBK_S_POINTER_0_PRODUCER_GROUP_1			_MK_ENUM_CONST(0x1)
#define NVDLA_RBK_S_POINTER_0_CONSUMER_SHIFT			_MK_SHIFT_CONST(16)
#define NVDLA_RBK_S_POINTER_0_CONSUMER_FIELD			_MK_FIELD_CONST(0x1, NVDLA_RBK_S_POINTER_0_CONSUMER_SHIFT)
#define NVDLA_RBK_S_POINTER_0_CONSUMER_GROUP_0			_MK_ENUM_CONST(0x0)
#define NVDLA_RBK_S_POINTER_0_CONSUMER_GROUP_1			_MK_ENUM_CONST(0x1)


// Register NVDLA_RBK_D_OP_ENABLE_0
#define NVDLA_RBK_D_OP_ENABLE_0			_MK_ADDR_CONST(0x11008)
#define NVDLA_RBK_D_OP_ENABLE_0_OP_EN_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_RBK_D_OP_ENABLE_0_OP_EN_FIELD			_MK_FIELD_CONST(0x1, NVDLA_RBK_D_OP_ENABLE_0_OP_EN_SHIFT)
#define NVDLA_RBK_D_OP_ENABLE_0_OP_EN_DISABLE			_MK_ENUM_CONST(0x0)
#define NVDLA_RBK_D_OP_ENABLE_0_OP_EN_ENABLE			_MK_ENUM_CONST(0x1)


// Register NVDLA_RBK_D_MISC_CFG_0
#define NVDLA_RBK_D_MISC_CFG_0			_MK_ADDR_CONST(0x1100c)
#define NVDLA_RBK_D_MISC_CFG_0_RUBIK_MODE_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_RBK_D_MISC_CFG_0_RUBIK_MODE_FIELD			_MK_FIELD_CONST(0x3, NVDLA_RBK_D_MISC_CFG_0_RUBIK_MODE_SHIFT)
#define NVDLA_RBK_D_MISC_CFG_0_RUBIK_MODE_CONTRACT			_MK_ENUM_CONST(0x0)
#define NVDLA_RBK_D_MISC_CFG_0_RUBIK_MODE_SPLIT			_MK_ENUM_CONST(0x1)
#define NVDLA_RBK_D_MISC_CFG_0_RUBIK_MODE_MERGE			_MK_ENUM_CONST(0x2)
#define NVDLA_RBK_D_MISC_CFG_0_IN_PRECISION_SHIFT			_MK_SHIFT_CONST(8)
#define NVDLA_RBK_D_MISC_CFG_0_IN_PRECISION_FIELD			_MK_FIELD_CONST(0x3, NVDLA_RBK_D_MISC_CFG_0_IN_PRECISION_SHIFT)
#define NVDLA_RBK_D_MISC_CFG_0_IN_PRECISION_INT8			_MK_ENUM_CONST(0x0)
#define NVDLA_RBK_D_MISC_CFG_0_IN_PRECISION_INT16			_MK_ENUM_CONST(0x1)
#define NVDLA_RBK_D_MISC_CFG_0_IN_PRECISION_FP16			_MK_ENUM_CONST(0x2)


// Register NVDLA_RBK_D_DAIN_RAM_TYPE_0
#define NVDLA_RBK_D_DAIN_RAM_TYPE_0			_MK_ADDR_CONST(0x11010)
#define NVDLA_RBK_D_DAIN_RAM_TYPE_0_DATAIN_RAM_TYPE_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_RBK_D_DAIN_RAM_TYPE_0_DATAIN_RAM_TYPE_FIELD			_MK_FIELD_CONST(0x1, NVDLA_RBK_D_DAIN_RAM_TYPE_0_DATAIN_RAM_TYPE_SHIFT)
#define NVDLA_RBK_D_DAIN_RAM_TYPE_0_DATAIN_RAM_TYPE_CVIF			_MK_ENUM_CONST(0x0)
#define NVDLA_RBK_D_DAIN_RAM_TYPE_0_DATAIN_RAM_TYPE_MCIF			_MK_ENUM_CONST(0x1)


// Register NVDLA_RBK_D_DATAIN_SIZE_0_0
#define NVDLA_RBK_D_DATAIN_SIZE_0_0			_MK_ADDR_CONST(0x11014)
#define NVDLA_RBK_D_DATAIN_SIZE_0_0_DATAIN_WIDTH_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_RBK_D_DATAIN_SIZE_0_0_DATAIN_WIDTH_FIELD			_MK_FIELD_CONST(0x1fff, NVDLA_RBK_D_DATAIN_SIZE_0_0_DATAIN_WIDTH_SHIFT)
#define NVDLA_RBK_D_DATAIN_SIZE_0_0_DATAIN_HEIGHT_SHIFT			_MK_SHIFT_CONST(16)
#define NVDLA_RBK_D_DATAIN_SIZE_0_0_DATAIN_HEIGHT_FIELD			_MK_FIELD_CONST(0x1fff, NVDLA_RBK_D_DATAIN_SIZE_0_0_DATAIN_HEIGHT_SHIFT)


// Register NVDLA_RBK_D_DATAIN_SIZE_1_0
#define NVDLA_RBK_D_DATAIN_SIZE_1_0			_MK_ADDR_CONST(0x11018)
#define NVDLA_RBK_D_DATAIN_SIZE_1_0_DATAIN_CHANNEL_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_RBK_D_DATAIN_SIZE_1_0_DATAIN_CHANNEL_FIELD			_MK_FIELD_CONST(0x1fff, NVDLA_RBK_D_DATAIN_SIZE_1_0_DATAIN_CHANNEL_SHIFT)


// Register NVDLA_RBK_D_DAIN_ADDR_HIGH_0
#define NVDLA_RBK_D_DAIN_ADDR_HIGH_0			_MK_ADDR_CONST(0x1101c)
#define NVDLA_RBK_D_DAIN_ADDR_HIGH_0_DAIN_ADDR_HIGH_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_RBK_D_DAIN_ADDR_HIGH_0_DAIN_ADDR_HIGH_FIELD			_MK_FIELD_CONST(0xffffffff, NVDLA_RBK_D_DAIN_ADDR_HIGH_0_DAIN_ADDR_HIGH_SHIFT)


// Register NVDLA_RBK_D_DAIN_ADDR_LOW_0
#define NVDLA_RBK_D_DAIN_ADDR_LOW_0			_MK_ADDR_CONST(0x11020)
#define NVDLA_RBK_D_DAIN_ADDR_LOW_0_DAIN_ADDR_LOW_SHIFT			_MK_SHIFT_CONST(5)
#define NVDLA_RBK_D_DAIN_ADDR_LOW_0_DAIN_ADDR_LOW_FIELD			_MK_FIELD_CONST(0x7ffffff, NVDLA_RBK_D_DAIN_ADDR_LOW_0_DAIN_ADDR_LOW_SHIFT)


// Register NVDLA_RBK_D_DAIN_LINE_STRIDE_0
#define NVDLA_RBK_D_DAIN_LINE_STRIDE_0			_MK_ADDR_CONST(0x11024)
#define NVDLA_RBK_D_DAIN_LINE_STRIDE_0_DAIN_LINE_STRIDE_SHIFT			_MK_SHIFT_CONST(5)
#define NVDLA_RBK_D_DAIN_LINE_STRIDE_0_DAIN_LINE_STRIDE_FIELD			_MK_FIELD_CONST(0x7ffffff, NVDLA_RBK_D_DAIN_LINE_STRIDE_0_DAIN_LINE_STRIDE_SHIFT)


// Register NVDLA_RBK_D_DAIN_SURF_STRIDE_0
#define NVDLA_RBK_D_DAIN_SURF_STRIDE_0			_MK_ADDR_CONST(0x11028)
#define NVDLA_RBK_D_DAIN_SURF_STRIDE_0_DAIN_SURF_STRIDE_SHIFT			_MK_SHIFT_CONST(5)
#define NVDLA_RBK_D_DAIN_SURF_STRIDE_0_DAIN_SURF_STRIDE_FIELD			_MK_FIELD_CONST(0x7ffffff, NVDLA_RBK_D_DAIN_SURF_STRIDE_0_DAIN_SURF_STRIDE_SHIFT)


// Register NVDLA_RBK_D_DAIN_PLANAR_STRIDE_0
#define NVDLA_RBK_D_DAIN_PLANAR_STRIDE_0			_MK_ADDR_CONST(0x1102c)
#define NVDLA_RBK_D_DAIN_PLANAR_STRIDE_0_DAIN_PLANAR_STRIDE_SHIFT			_MK_SHIFT_CONST(5)
#define NVDLA_RBK_D_DAIN_PLANAR_STRIDE_0_DAIN_PLANAR_STRIDE_FIELD			_MK_FIELD_CONST(0x7ffffff, NVDLA_RBK_D_DAIN_PLANAR_STRIDE_0_DAIN_PLANAR_STRIDE_SHIFT)


// Register NVDLA_RBK_D_DAOUT_RAM_TYPE_0
#define NVDLA_RBK_D_DAOUT_RAM_TYPE_0			_MK_ADDR_CONST(0x11030)
#define NVDLA_RBK_D_DAOUT_RAM_TYPE_0_DATAOUT_RAM_TYPE_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_RBK_D_DAOUT_RAM_TYPE_0_DATAOUT_RAM_TYPE_FIELD			_MK_FIELD_CONST(0x1, NVDLA_RBK_D_DAOUT_RAM_TYPE_0_DATAOUT_RAM_TYPE_SHIFT)
#define NVDLA_RBK_D_DAOUT_RAM_TYPE_0_DATAOUT_RAM_TYPE_CVIF			_MK_ENUM_CONST(0x0)
#define NVDLA_RBK_D_DAOUT_RAM_TYPE_0_DATAOUT_RAM_TYPE_MCIF			_MK_ENUM_CONST(0x1)


// Register NVDLA_RBK_D_DATAOUT_SIZE_1_0
#define NVDLA_RBK_D_DATAOUT_SIZE_1_0			_MK_ADDR_CONST(0x11034)
#define NVDLA_RBK_D_DATAOUT_SIZE_1_0_DATAOUT_CHANNEL_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_RBK_D_DATAOUT_SIZE_1_0_DATAOUT_CHANNEL_FIELD			_MK_FIELD_CONST(0x1fff, NVDLA_RBK_D_DATAOUT_SIZE_1_0_DATAOUT_CHANNEL_SHIFT)


// Register NVDLA_RBK_D_DAOUT_ADDR_HIGH_0
#define NVDLA_RBK_D_DAOUT_ADDR_HIGH_0			_MK_ADDR_CONST(0x11038)
#define NVDLA_RBK_D_DAOUT_ADDR_HIGH_0_DAOUT_ADDR_HIGH_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_RBK_D_DAOUT_ADDR_HIGH_0_DAOUT_ADDR_HIGH_FIELD			_MK_FIELD_CONST(0xffffffff, NVDLA_RBK_D_DAOUT_ADDR_HIGH_0_DAOUT_ADDR_HIGH_SHIFT)


// Register NVDLA_RBK_D_DAOUT_ADDR_LOW_0
#define NVDLA_RBK_D_DAOUT_ADDR_LOW_0			_MK_ADDR_CONST(0x1103c)
#define NVDLA_RBK_D_DAOUT_ADDR_LOW_0_DAOUT_ADDR_LOW_SHIFT			_MK_SHIFT_CONST(5)
#define NVDLA_RBK_D_DAOUT_ADDR_LOW_0_DAOUT_ADDR_LOW_FIELD			_MK_FIELD_CONST(0x7ffffff, NVDLA_RBK_D_DAOUT_ADDR_LOW_0_DAOUT_ADDR_LOW_SHIFT)


// Register NVDLA_RBK_D_DAOUT_LINE_STRIDE_0
#define NVDLA_RBK_D_DAOUT_LINE_STRIDE_0			_MK_ADDR_CONST(0x11040)
#define NVDLA_RBK_D_DAOUT_LINE_STRIDE_0_DAOUT_LINE_STRIDE_SHIFT			_MK_SHIFT_CONST(5)
#define NVDLA_RBK_D_DAOUT_LINE_STRIDE_0_DAOUT_LINE_STRIDE_FIELD			_MK_FIELD_CONST(0x7ffffff, NVDLA_RBK_D_DAOUT_LINE_STRIDE_0_DAOUT_LINE_STRIDE_SHIFT)


// Register NVDLA_RBK_D_CONTRACT_STRIDE_0_0
#define NVDLA_RBK_D_CONTRACT_STRIDE_0_0			_MK_ADDR_CONST(0x11044)
#define NVDLA_RBK_D_CONTRACT_STRIDE_0_0_CONTRACT_STRIDE_0_SHIFT			_MK_SHIFT_CONST(5)
#define NVDLA_RBK_D_CONTRACT_STRIDE_0_0_CONTRACT_STRIDE_0_FIELD			_MK_FIELD_CONST(0x7ffffff, NVDLA_RBK_D_CONTRACT_STRIDE_0_0_CONTRACT_STRIDE_0_SHIFT)


// Register NVDLA_RBK_D_CONTRACT_STRIDE_1_0
#define NVDLA_RBK_D_CONTRACT_STRIDE_1_0			_MK_ADDR_CONST(0x11048)
#define NVDLA_RBK_D_CONTRACT_STRIDE_1_0_CONTRACT_STRIDE_1_SHIFT			_MK_SHIFT_CONST(5)
#define NVDLA_RBK_D_CONTRACT_STRIDE_1_0_CONTRACT_STRIDE_1_FIELD			_MK_FIELD_CONST(0x7ffffff, NVDLA_RBK_D_CONTRACT_STRIDE_1_0_CONTRACT_STRIDE_1_SHIFT)


// Register NVDLA_RBK_D_DAOUT_SURF_STRIDE_0
#define NVDLA_RBK_D_DAOUT_SURF_STRIDE_0			_MK_ADDR_CONST(0x1104c)
#define NVDLA_RBK_D_DAOUT_SURF_STRIDE_0_DAOUT_SURF_STRIDE_SHIFT			_MK_SHIFT_CONST(5)
#define NVDLA_RBK_D_DAOUT_SURF_STRIDE_0_DAOUT_SURF_STRIDE_FIELD			_MK_FIELD_CONST(0x7ffffff, NVDLA_RBK_D_DAOUT_SURF_STRIDE_0_DAOUT_SURF_STRIDE_SHIFT)


// Register NVDLA_RBK_D_DAOUT_PLANAR_STRIDE_0
#define NVDLA_RBK_D_DAOUT_PLANAR_STRIDE_0			_MK_ADDR_CONST(0x11050)
#define NVDLA_RBK_D_DAOUT_PLANAR_STRIDE_0_DAOUT_PLANAR_STRIDE_SHIFT			_MK_SHIFT_CONST(5)
#define NVDLA_RBK_D_DAOUT_PLANAR_STRIDE_0_DAOUT_PLANAR_STRIDE_FIELD			_MK_FIELD_CONST(0x7ffffff, NVDLA_RBK_D_DAOUT_PLANAR_STRIDE_0_DAOUT_PLANAR_STRIDE_SHIFT)


// Register NVDLA_RBK_D_DECONV_STRIDE_0
#define NVDLA_RBK_D_DECONV_STRIDE_0			_MK_ADDR_CONST(0x11054)
#define NVDLA_RBK_D_DECONV_STRIDE_0_DECONV_X_STRIDE_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_RBK_D_DECONV_STRIDE_0_DECONV_X_STRIDE_FIELD			_MK_FIELD_CONST(0x1f, NVDLA_RBK_D_DECONV_STRIDE_0_DECONV_X_STRIDE_SHIFT)
#define NVDLA_RBK_D_DECONV_STRIDE_0_DECONV_Y_STRIDE_SHIFT			_MK_SHIFT_CONST(16)
#define NVDLA_RBK_D_DECONV_STRIDE_0_DECONV_Y_STRIDE_FIELD			_MK_FIELD_CONST(0x1f, NVDLA_RBK_D_DECONV_STRIDE_0_DECONV_Y_STRIDE_SHIFT)


// Register NVDLA_RBK_D_PERF_ENABLE_0
#define NVDLA_RBK_D_PERF_ENABLE_0			_MK_ADDR_CONST(0x11058)
#define NVDLA_RBK_D_PERF_ENABLE_0_PERF_EN_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_RBK_D_PERF_ENABLE_0_PERF_EN_FIELD			_MK_FIELD_CONST(0x1, NVDLA_RBK_D_PERF_ENABLE_0_PERF_EN_SHIFT)


// Register NVDLA_RBK_D_PERF_READ_STALL_0
#define NVDLA_RBK_D_PERF_READ_STALL_0			_MK_ADDR_CONST(0x1105c)
#define NVDLA_RBK_D_PERF_READ_STALL_0_RD_STALL_CNT_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_RBK_D_PERF_READ_STALL_0_RD_STALL_CNT_FIELD			_MK_FIELD_CONST(0xffffffff, NVDLA_RBK_D_PERF_READ_STALL_0_RD_STALL_CNT_SHIFT)


// Register NVDLA_RBK_D_PERF_WRITE_STALL_0
#define NVDLA_RBK_D_PERF_WRITE_STALL_0			_MK_ADDR_CONST(0x11060)
#define NVDLA_RBK_D_PERF_WRITE_STALL_0_WR_STALL_CNT_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_RBK_D_PERF_WRITE_STALL_0_WR_STALL_CNT_FIELD			_MK_FIELD_CONST(0xffffffff, NVDLA_RBK_D_PERF_WRITE_STALL_0_WR_STALL_CNT_SHIFT)



// To satisfy various compilers and platforms,
// we let users control the types and syntax of certain constants, using macros.
#ifndef _MK_SHIFT_CONST
  #define _MK_SHIFT_CONST(_constant_) _constant_
#endif
#ifndef _MK_MASK_CONST
  #define _MK_MASK_CONST(_constant_) _constant_
#endif
#ifndef _MK_ENUM_CONST
  #define _MK_ENUM_CONST(_constant_) (_constant_ ## UL)
#endif
#ifndef _MK_ADDR_CONST
  #define _MK_ADDR_CONST(_constant_) _constant_
#endif
#ifndef _MK_FIELD_CONST
  #define _MK_FIELD_CONST(_mask_, _shift_) (_MK_MASK_CONST(_mask_) << _MK_SHIFT_CONST(_shift_))
#endif



//
// ADDRESS SPACES
//

#define BASE_ADDRESS_NVDLA_RBK	0x11000
