// Register NVDLA_CSC_S_STATUS_0
#define NVDLA_CSC_S_STATUS_0			_MK_ADDR_CONST(0x4000)
#define NVDLA_CSC_S_STATUS_0_STATUS_0_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CSC_S_STATUS_0_STATUS_0_FIELD			_MK_FIELD_CONST(0x3, NVDLA_CSC_S_STATUS_0_STATUS_0_SHIFT)
#define NVDLA_CSC_S_STATUS_0_STATUS_0_IDLE			_MK_ENUM_CONST(0x0)
#define NVDLA_CSC_S_STATUS_0_STATUS_0_RUNNING			_MK_ENUM_CONST(0x1)
#define NVDLA_CSC_S_STATUS_0_STATUS_0_PENDING			_MK_ENUM_CONST(0x2)
#define NVDLA_CSC_S_STATUS_0_STATUS_1_SHIFT			_MK_SHIFT_CONST(16)
#define NVDLA_CSC_S_STATUS_0_STATUS_1_FIELD			_MK_FIELD_CONST(0x3, NVDLA_CSC_S_STATUS_0_STATUS_1_SHIFT)
#define NVDLA_CSC_S_STATUS_0_STATUS_1_IDLE			_MK_ENUM_CONST(0x0)
#define NVDLA_CSC_S_STATUS_0_STATUS_1_RUNNING			_MK_ENUM_CONST(0x1)
#define NVDLA_CSC_S_STATUS_0_STATUS_1_PENDING			_MK_ENUM_CONST(0x2)


// Register NVDLA_CSC_S_POINTER_0
#define NVDLA_CSC_S_POINTER_0			_MK_ADDR_CONST(0x4004)
#define NVDLA_CSC_S_POINTER_0_PRODUCER_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CSC_S_POINTER_0_PRODUCER_FIELD			_MK_FIELD_CONST(0x1, NVDLA_CSC_S_POINTER_0_PRODUCER_SHIFT)
#define NVDLA_CSC_S_POINTER_0_PRODUCER_GROUP_0			_MK_ENUM_CONST(0x0)
#define NVDLA_CSC_S_POINTER_0_PRODUCER_GROUP_1			_MK_ENUM_CONST(0x1)
#define NVDLA_CSC_S_POINTER_0_CONSUMER_SHIFT			_MK_SHIFT_CONST(16)
#define NVDLA_CSC_S_POINTER_0_CONSUMER_FIELD			_MK_FIELD_CONST(0x1, NVDLA_CSC_S_POINTER_0_CONSUMER_SHIFT)
#define NVDLA_CSC_S_POINTER_0_CONSUMER_GROUP_0			_MK_ENUM_CONST(0x0)
#define NVDLA_CSC_S_POINTER_0_CONSUMER_GROUP_1			_MK_ENUM_CONST(0x1)


// Register NVDLA_CSC_D_OP_ENABLE_0
#define NVDLA_CSC_D_OP_ENABLE_0			_MK_ADDR_CONST(0x4008)
#define NVDLA_CSC_D_OP_ENABLE_0_OP_EN_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CSC_D_OP_ENABLE_0_OP_EN_FIELD			_MK_FIELD_CONST(0x1, NVDLA_CSC_D_OP_ENABLE_0_OP_EN_SHIFT)
#define NVDLA_CSC_D_OP_ENABLE_0_OP_EN_DISABLE			_MK_ENUM_CONST(0x0)
#define NVDLA_CSC_D_OP_ENABLE_0_OP_EN_ENABLE			_MK_ENUM_CONST(0x1)


// Register NVDLA_CSC_D_MISC_CFG_0
#define NVDLA_CSC_D_MISC_CFG_0			_MK_ADDR_CONST(0x400c)
#define NVDLA_CSC_D_MISC_CFG_0_CONV_MODE_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CSC_D_MISC_CFG_0_CONV_MODE_FIELD			_MK_FIELD_CONST(0x1, NVDLA_CSC_D_MISC_CFG_0_CONV_MODE_SHIFT)
#define NVDLA_CSC_D_MISC_CFG_0_CONV_MODE_DIRECT			_MK_ENUM_CONST(0x0)
#define NVDLA_CSC_D_MISC_CFG_0_CONV_MODE_WINOGRAD			_MK_ENUM_CONST(0x1)
#define NVDLA_CSC_D_MISC_CFG_0_IN_PRECISION_SHIFT			_MK_SHIFT_CONST(8)
#define NVDLA_CSC_D_MISC_CFG_0_IN_PRECISION_FIELD			_MK_FIELD_CONST(0x3, NVDLA_CSC_D_MISC_CFG_0_IN_PRECISION_SHIFT)
#define NVDLA_CSC_D_MISC_CFG_0_IN_PRECISION_INT8			_MK_ENUM_CONST(0x0)
#define NVDLA_CSC_D_MISC_CFG_0_IN_PRECISION_INT16			_MK_ENUM_CONST(0x1)
#define NVDLA_CSC_D_MISC_CFG_0_IN_PRECISION_FP16			_MK_ENUM_CONST(0x2)
#define NVDLA_CSC_D_MISC_CFG_0_PROC_PRECISION_SHIFT			_MK_SHIFT_CONST(12)
#define NVDLA_CSC_D_MISC_CFG_0_PROC_PRECISION_FIELD			_MK_FIELD_CONST(0x3, NVDLA_CSC_D_MISC_CFG_0_PROC_PRECISION_SHIFT)
#define NVDLA_CSC_D_MISC_CFG_0_PROC_PRECISION_INT8			_MK_ENUM_CONST(0x0)
#define NVDLA_CSC_D_MISC_CFG_0_PROC_PRECISION_INT16			_MK_ENUM_CONST(0x1)
#define NVDLA_CSC_D_MISC_CFG_0_PROC_PRECISION_FP16			_MK_ENUM_CONST(0x2)
#define NVDLA_CSC_D_MISC_CFG_0_DATA_REUSE_SHIFT			_MK_SHIFT_CONST(16)
#define NVDLA_CSC_D_MISC_CFG_0_DATA_REUSE_FIELD			_MK_FIELD_CONST(0x1, NVDLA_CSC_D_MISC_CFG_0_DATA_REUSE_SHIFT)
#define NVDLA_CSC_D_MISC_CFG_0_DATA_REUSE_DISABLE			_MK_ENUM_CONST(0x0)
#define NVDLA_CSC_D_MISC_CFG_0_DATA_REUSE_ENABLE			_MK_ENUM_CONST(0x1)
#define NVDLA_CSC_D_MISC_CFG_0_WEIGHT_REUSE_SHIFT			_MK_SHIFT_CONST(20)
#define NVDLA_CSC_D_MISC_CFG_0_WEIGHT_REUSE_FIELD			_MK_FIELD_CONST(0x1, NVDLA_CSC_D_MISC_CFG_0_WEIGHT_REUSE_SHIFT)
#define NVDLA_CSC_D_MISC_CFG_0_WEIGHT_REUSE_DISABLE			_MK_ENUM_CONST(0x0)
#define NVDLA_CSC_D_MISC_CFG_0_WEIGHT_REUSE_ENABLE			_MK_ENUM_CONST(0x1)
#define NVDLA_CSC_D_MISC_CFG_0_SKIP_DATA_RLS_SHIFT			_MK_SHIFT_CONST(24)
#define NVDLA_CSC_D_MISC_CFG_0_SKIP_DATA_RLS_FIELD			_MK_FIELD_CONST(0x1, NVDLA_CSC_D_MISC_CFG_0_SKIP_DATA_RLS_SHIFT)
#define NVDLA_CSC_D_MISC_CFG_0_SKIP_DATA_RLS_DISABLE			_MK_ENUM_CONST(0x0)
#define NVDLA_CSC_D_MISC_CFG_0_SKIP_DATA_RLS_ENABLE			_MK_ENUM_CONST(0x1)
#define NVDLA_CSC_D_MISC_CFG_0_SKIP_WEIGHT_RLS_SHIFT			_MK_SHIFT_CONST(28)
#define NVDLA_CSC_D_MISC_CFG_0_SKIP_WEIGHT_RLS_FIELD			_MK_FIELD_CONST(0x1, NVDLA_CSC_D_MISC_CFG_0_SKIP_WEIGHT_RLS_SHIFT)
#define NVDLA_CSC_D_MISC_CFG_0_SKIP_WEIGHT_RLS_DISABLE			_MK_ENUM_CONST(0x0)
#define NVDLA_CSC_D_MISC_CFG_0_SKIP_WEIGHT_RLS_ENABLE			_MK_ENUM_CONST(0x1)


// Register NVDLA_CSC_D_DATAIN_FORMAT_0
#define NVDLA_CSC_D_DATAIN_FORMAT_0			_MK_ADDR_CONST(0x4010)
#define NVDLA_CSC_D_DATAIN_FORMAT_0_DATAIN_FORMAT_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CSC_D_DATAIN_FORMAT_0_DATAIN_FORMAT_FIELD			_MK_FIELD_CONST(0x1, NVDLA_CSC_D_DATAIN_FORMAT_0_DATAIN_FORMAT_SHIFT)
#define NVDLA_CSC_D_DATAIN_FORMAT_0_DATAIN_FORMAT_FEATURE			_MK_ENUM_CONST(0x0)
#define NVDLA_CSC_D_DATAIN_FORMAT_0_DATAIN_FORMAT_PIXEL			_MK_ENUM_CONST(0x1)


// Register NVDLA_CSC_D_DATAIN_SIZE_EXT_0_0
#define NVDLA_CSC_D_DATAIN_SIZE_EXT_0_0			_MK_ADDR_CONST(0x4014)
#define NVDLA_CSC_D_DATAIN_SIZE_EXT_0_0_DATAIN_WIDTH_EXT_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CSC_D_DATAIN_SIZE_EXT_0_0_DATAIN_WIDTH_EXT_FIELD			_MK_FIELD_CONST(0x1fff, NVDLA_CSC_D_DATAIN_SIZE_EXT_0_0_DATAIN_WIDTH_EXT_SHIFT)
#define NVDLA_CSC_D_DATAIN_SIZE_EXT_0_0_DATAIN_HEIGHT_EXT_SHIFT			_MK_SHIFT_CONST(16)
#define NVDLA_CSC_D_DATAIN_SIZE_EXT_0_0_DATAIN_HEIGHT_EXT_FIELD			_MK_FIELD_CONST(0x1fff, NVDLA_CSC_D_DATAIN_SIZE_EXT_0_0_DATAIN_HEIGHT_EXT_SHIFT)


// Register NVDLA_CSC_D_DATAIN_SIZE_EXT_1_0
#define NVDLA_CSC_D_DATAIN_SIZE_EXT_1_0			_MK_ADDR_CONST(0x4018)
#define NVDLA_CSC_D_DATAIN_SIZE_EXT_1_0_DATAIN_CHANNEL_EXT_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CSC_D_DATAIN_SIZE_EXT_1_0_DATAIN_CHANNEL_EXT_FIELD			_MK_FIELD_CONST(0x1fff, NVDLA_CSC_D_DATAIN_SIZE_EXT_1_0_DATAIN_CHANNEL_EXT_SHIFT)


// Register NVDLA_CSC_D_BATCH_NUMBER_0
#define NVDLA_CSC_D_BATCH_NUMBER_0			_MK_ADDR_CONST(0x401c)
#define NVDLA_CSC_D_BATCH_NUMBER_0_BATCHES_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CSC_D_BATCH_NUMBER_0_BATCHES_FIELD			_MK_FIELD_CONST(0x1f, NVDLA_CSC_D_BATCH_NUMBER_0_BATCHES_SHIFT)


// Register NVDLA_CSC_D_POST_Y_EXTENSION_0
#define NVDLA_CSC_D_POST_Y_EXTENSION_0			_MK_ADDR_CONST(0x4020)
#define NVDLA_CSC_D_POST_Y_EXTENSION_0_Y_EXTENSION_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CSC_D_POST_Y_EXTENSION_0_Y_EXTENSION_FIELD			_MK_FIELD_CONST(0x3, NVDLA_CSC_D_POST_Y_EXTENSION_0_Y_EXTENSION_SHIFT)


// Register NVDLA_CSC_D_ENTRY_PER_SLICE_0
#define NVDLA_CSC_D_ENTRY_PER_SLICE_0			_MK_ADDR_CONST(0x4024)
#define NVDLA_CSC_D_ENTRY_PER_SLICE_0_ENTRIES_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CSC_D_ENTRY_PER_SLICE_0_ENTRIES_FIELD			_MK_FIELD_CONST(0x3fff, NVDLA_CSC_D_ENTRY_PER_SLICE_0_ENTRIES_SHIFT)


// Register NVDLA_CSC_D_WEIGHT_FORMAT_0
#define NVDLA_CSC_D_WEIGHT_FORMAT_0			_MK_ADDR_CONST(0x4028)
#define NVDLA_CSC_D_WEIGHT_FORMAT_0_WEIGHT_FORMAT_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CSC_D_WEIGHT_FORMAT_0_WEIGHT_FORMAT_FIELD			_MK_FIELD_CONST(0x1, NVDLA_CSC_D_WEIGHT_FORMAT_0_WEIGHT_FORMAT_SHIFT)
#define NVDLA_CSC_D_WEIGHT_FORMAT_0_WEIGHT_FORMAT_UNCOMPRESSED			_MK_ENUM_CONST(0x0)
#define NVDLA_CSC_D_WEIGHT_FORMAT_0_WEIGHT_FORMAT_COMPRESSED			_MK_ENUM_CONST(0x1)


// Register NVDLA_CSC_D_WEIGHT_SIZE_EXT_0_0
#define NVDLA_CSC_D_WEIGHT_SIZE_EXT_0_0			_MK_ADDR_CONST(0x402c)
#define NVDLA_CSC_D_WEIGHT_SIZE_EXT_0_0_WEIGHT_WIDTH_EXT_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CSC_D_WEIGHT_SIZE_EXT_0_0_WEIGHT_WIDTH_EXT_FIELD			_MK_FIELD_CONST(0x1f, NVDLA_CSC_D_WEIGHT_SIZE_EXT_0_0_WEIGHT_WIDTH_EXT_SHIFT)
#define NVDLA_CSC_D_WEIGHT_SIZE_EXT_0_0_WEIGHT_HEIGHT_EXT_SHIFT			_MK_SHIFT_CONST(16)
#define NVDLA_CSC_D_WEIGHT_SIZE_EXT_0_0_WEIGHT_HEIGHT_EXT_FIELD			_MK_FIELD_CONST(0x1f, NVDLA_CSC_D_WEIGHT_SIZE_EXT_0_0_WEIGHT_HEIGHT_EXT_SHIFT)


// Register NVDLA_CSC_D_WEIGHT_SIZE_EXT_1_0
#define NVDLA_CSC_D_WEIGHT_SIZE_EXT_1_0			_MK_ADDR_CONST(0x4030)
#define NVDLA_CSC_D_WEIGHT_SIZE_EXT_1_0_WEIGHT_CHANNEL_EXT_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CSC_D_WEIGHT_SIZE_EXT_1_0_WEIGHT_CHANNEL_EXT_FIELD			_MK_FIELD_CONST(0x1fff, NVDLA_CSC_D_WEIGHT_SIZE_EXT_1_0_WEIGHT_CHANNEL_EXT_SHIFT)
#define NVDLA_CSC_D_WEIGHT_SIZE_EXT_1_0_WEIGHT_KERNEL_SHIFT			_MK_SHIFT_CONST(16)
#define NVDLA_CSC_D_WEIGHT_SIZE_EXT_1_0_WEIGHT_KERNEL_FIELD			_MK_FIELD_CONST(0x1fff, NVDLA_CSC_D_WEIGHT_SIZE_EXT_1_0_WEIGHT_KERNEL_SHIFT)


// Register NVDLA_CSC_D_WEIGHT_BYTES_0
#define NVDLA_CSC_D_WEIGHT_BYTES_0			_MK_ADDR_CONST(0x4034)
#define NVDLA_CSC_D_WEIGHT_BYTES_0_WEIGHT_BYTES_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CSC_D_WEIGHT_BYTES_0_WEIGHT_BYTES_FIELD			_MK_FIELD_CONST(0xffffffff, NVDLA_CSC_D_WEIGHT_BYTES_0_WEIGHT_BYTES_SHIFT)


// Register NVDLA_CSC_D_WMB_BYTES_0
#define NVDLA_CSC_D_WMB_BYTES_0			_MK_ADDR_CONST(0x4038)
#define NVDLA_CSC_D_WMB_BYTES_0_WMB_BYTES_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CSC_D_WMB_BYTES_0_WMB_BYTES_FIELD			_MK_FIELD_CONST(0xfffffff, NVDLA_CSC_D_WMB_BYTES_0_WMB_BYTES_SHIFT)


// Register NVDLA_CSC_D_DATAOUT_SIZE_0_0
#define NVDLA_CSC_D_DATAOUT_SIZE_0_0			_MK_ADDR_CONST(0x403c)
#define NVDLA_CSC_D_DATAOUT_SIZE_0_0_DATAOUT_WIDTH_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CSC_D_DATAOUT_SIZE_0_0_DATAOUT_WIDTH_FIELD			_MK_FIELD_CONST(0x1fff, NVDLA_CSC_D_DATAOUT_SIZE_0_0_DATAOUT_WIDTH_SHIFT)
#define NVDLA_CSC_D_DATAOUT_SIZE_0_0_DATAOUT_HEIGHT_SHIFT			_MK_SHIFT_CONST(16)
#define NVDLA_CSC_D_DATAOUT_SIZE_0_0_DATAOUT_HEIGHT_FIELD			_MK_FIELD_CONST(0x1fff, NVDLA_CSC_D_DATAOUT_SIZE_0_0_DATAOUT_HEIGHT_SHIFT)


// Register NVDLA_CSC_D_DATAOUT_SIZE_1_0
#define NVDLA_CSC_D_DATAOUT_SIZE_1_0			_MK_ADDR_CONST(0x4040)
#define NVDLA_CSC_D_DATAOUT_SIZE_1_0_DATAOUT_CHANNEL_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CSC_D_DATAOUT_SIZE_1_0_DATAOUT_CHANNEL_FIELD			_MK_FIELD_CONST(0x1fff, NVDLA_CSC_D_DATAOUT_SIZE_1_0_DATAOUT_CHANNEL_SHIFT)


// Register NVDLA_CSC_D_ATOMICS_0
#define NVDLA_CSC_D_ATOMICS_0			_MK_ADDR_CONST(0x4044)
#define NVDLA_CSC_D_ATOMICS_0_ATOMICS_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CSC_D_ATOMICS_0_ATOMICS_FIELD			_MK_FIELD_CONST(0x1fffff, NVDLA_CSC_D_ATOMICS_0_ATOMICS_SHIFT)


// Register NVDLA_CSC_D_RELEASE_0
#define NVDLA_CSC_D_RELEASE_0			_MK_ADDR_CONST(0x4048)
#define NVDLA_CSC_D_RELEASE_0_RLS_SLICES_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CSC_D_RELEASE_0_RLS_SLICES_FIELD			_MK_FIELD_CONST(0xfff, NVDLA_CSC_D_RELEASE_0_RLS_SLICES_SHIFT)


// Register NVDLA_CSC_D_CONV_STRIDE_EXT_0
#define NVDLA_CSC_D_CONV_STRIDE_EXT_0			_MK_ADDR_CONST(0x404c)
#define NVDLA_CSC_D_CONV_STRIDE_EXT_0_CONV_X_STRIDE_EXT_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CSC_D_CONV_STRIDE_EXT_0_CONV_X_STRIDE_EXT_FIELD			_MK_FIELD_CONST(0x7, NVDLA_CSC_D_CONV_STRIDE_EXT_0_CONV_X_STRIDE_EXT_SHIFT)
#define NVDLA_CSC_D_CONV_STRIDE_EXT_0_CONV_Y_STRIDE_EXT_SHIFT			_MK_SHIFT_CONST(16)
#define NVDLA_CSC_D_CONV_STRIDE_EXT_0_CONV_Y_STRIDE_EXT_FIELD			_MK_FIELD_CONST(0x7, NVDLA_CSC_D_CONV_STRIDE_EXT_0_CONV_Y_STRIDE_EXT_SHIFT)


// Register NVDLA_CSC_D_DILATION_EXT_0
#define NVDLA_CSC_D_DILATION_EXT_0			_MK_ADDR_CONST(0x4050)
#define NVDLA_CSC_D_DILATION_EXT_0_X_DILATION_EXT_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CSC_D_DILATION_EXT_0_X_DILATION_EXT_FIELD			_MK_FIELD_CONST(0x1f, NVDLA_CSC_D_DILATION_EXT_0_X_DILATION_EXT_SHIFT)
#define NVDLA_CSC_D_DILATION_EXT_0_Y_DILATION_EXT_SHIFT			_MK_SHIFT_CONST(16)
#define NVDLA_CSC_D_DILATION_EXT_0_Y_DILATION_EXT_FIELD			_MK_FIELD_CONST(0x1f, NVDLA_CSC_D_DILATION_EXT_0_Y_DILATION_EXT_SHIFT)


// Register NVDLA_CSC_D_ZERO_PADDING_0
#define NVDLA_CSC_D_ZERO_PADDING_0			_MK_ADDR_CONST(0x4054)
#define NVDLA_CSC_D_ZERO_PADDING_0_PAD_LEFT_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CSC_D_ZERO_PADDING_0_PAD_LEFT_FIELD			_MK_FIELD_CONST(0x1f, NVDLA_CSC_D_ZERO_PADDING_0_PAD_LEFT_SHIFT)
#define NVDLA_CSC_D_ZERO_PADDING_0_PAD_TOP_SHIFT			_MK_SHIFT_CONST(16)
#define NVDLA_CSC_D_ZERO_PADDING_0_PAD_TOP_FIELD			_MK_FIELD_CONST(0x1f, NVDLA_CSC_D_ZERO_PADDING_0_PAD_TOP_SHIFT)


// Register NVDLA_CSC_D_ZERO_PADDING_VALUE_0
#define NVDLA_CSC_D_ZERO_PADDING_VALUE_0			_MK_ADDR_CONST(0x4058)
#define NVDLA_CSC_D_ZERO_PADDING_VALUE_0_PAD_VALUE_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CSC_D_ZERO_PADDING_VALUE_0_PAD_VALUE_FIELD			_MK_FIELD_CONST(0xffff, NVDLA_CSC_D_ZERO_PADDING_VALUE_0_PAD_VALUE_SHIFT)


// Register NVDLA_CSC_D_BANK_0
#define NVDLA_CSC_D_BANK_0			_MK_ADDR_CONST(0x405c)
#define NVDLA_CSC_D_BANK_0_DATA_BANK_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CSC_D_BANK_0_DATA_BANK_FIELD			_MK_FIELD_CONST(0x1f, NVDLA_CSC_D_BANK_0_DATA_BANK_SHIFT)
#define NVDLA_CSC_D_BANK_0_WEIGHT_BANK_SHIFT			_MK_SHIFT_CONST(16)
#define NVDLA_CSC_D_BANK_0_WEIGHT_BANK_FIELD			_MK_FIELD_CONST(0x1f, NVDLA_CSC_D_BANK_0_WEIGHT_BANK_SHIFT)


// Register NVDLA_CSC_D_PRA_CFG_0
#define NVDLA_CSC_D_PRA_CFG_0			_MK_ADDR_CONST(0x4060)
#define NVDLA_CSC_D_PRA_CFG_0_PRA_TRUNCATE_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CSC_D_PRA_CFG_0_PRA_TRUNCATE_FIELD			_MK_FIELD_CONST(0x3, NVDLA_CSC_D_PRA_CFG_0_PRA_TRUNCATE_SHIFT)


// Register NVDLA_CSC_D_CYA_0
#define NVDLA_CSC_D_CYA_0			_MK_ADDR_CONST(0x4064)
#define NVDLA_CSC_D_CYA_0_CYA_SHIFT			_MK_SHIFT_CONST(0)
#define NVDLA_CSC_D_CYA_0_CYA_FIELD			_MK_FIELD_CONST(0xffffffff, NVDLA_CSC_D_CYA_0_CYA_SHIFT)



// To satisfy various compilers and platforms,
// we let users control the types and syntax of certain constants, using macros.
#ifndef _MK_SHIFT_CONST
  #define _MK_SHIFT_CONST(_constant_) _constant_
#endif
#ifndef _MK_MASK_CONST
  #define _MK_MASK_CONST(_constant_) _constant_
#endif
#ifndef _MK_ENUM_CONST
  #define _MK_ENUM_CONST(_constant_) (_constant_ ## UL)
#endif
#ifndef _MK_ADDR_CONST
  #define _MK_ADDR_CONST(_constant_) _constant_
#endif
#ifndef _MK_FIELD_CONST
  #define _MK_FIELD_CONST(_mask_, _shift_) (_MK_MASK_CONST(_mask_) << _MK_SHIFT_CONST(_shift_))
#endif



//
// ADDRESS SPACES
//

#define BASE_ADDRESS_NVDLA_CSC	0x4000
