//   Ordt 171103.01 autogenerated file 
//   Input: NVDLA_CACC.rdl
//   Parms: opendla.parms
//   Date: Sat Feb 01 17:43:22 CET 2020
//

//
//---------- module addrmap_NVDLA_jrdl_logic
//
module addrmap_NVDLA_jrdl_logic
(
  clk,
  reset,
  d2l_NVDLA_CACC_S_STATUS_w,
  d2l_NVDLA_CACC_S_STATUS_we,
  d2l_NVDLA_CACC_S_STATUS_re,
  d2l_NVDLA_CACC_S_POINTER_w,
  d2l_NVDLA_CACC_S_POINTER_we,
  d2l_NVDLA_CACC_S_POINTER_re,
  d2l_NVDLA_CACC_D_OP_ENABLE_w,
  d2l_NVDLA_CACC_D_OP_ENABLE_we,
  d2l_NVDLA_CACC_D_OP_ENABLE_re,
  d2l_NVDLA_CACC_D_MISC_CFG_w,
  d2l_NVDLA_CACC_D_MISC_CFG_we,
  d2l_NVDLA_CACC_D_MISC_CFG_re,
  d2l_NVDLA_CACC_D_DATAOUT_SIZE_0_w,
  d2l_NVDLA_CACC_D_DATAOUT_SIZE_0_we,
  d2l_NVDLA_CACC_D_DATAOUT_SIZE_0_re,
  d2l_NVDLA_CACC_D_DATAOUT_SIZE_1_w,
  d2l_NVDLA_CACC_D_DATAOUT_SIZE_1_we,
  d2l_NVDLA_CACC_D_DATAOUT_SIZE_1_re,
  d2l_NVDLA_CACC_D_DATAOUT_ADDR_w,
  d2l_NVDLA_CACC_D_DATAOUT_ADDR_we,
  d2l_NVDLA_CACC_D_DATAOUT_ADDR_re,
  d2l_NVDLA_CACC_D_BATCH_NUMBER_w,
  d2l_NVDLA_CACC_D_BATCH_NUMBER_we,
  d2l_NVDLA_CACC_D_BATCH_NUMBER_re,
  d2l_NVDLA_CACC_D_LINE_STRIDE_w,
  d2l_NVDLA_CACC_D_LINE_STRIDE_we,
  d2l_NVDLA_CACC_D_LINE_STRIDE_re,
  d2l_NVDLA_CACC_D_SURF_STRIDE_w,
  d2l_NVDLA_CACC_D_SURF_STRIDE_we,
  d2l_NVDLA_CACC_D_SURF_STRIDE_re,
  d2l_NVDLA_CACC_D_DATAOUT_MAP_w,
  d2l_NVDLA_CACC_D_DATAOUT_MAP_we,
  d2l_NVDLA_CACC_D_DATAOUT_MAP_re,
  d2l_NVDLA_CACC_D_CLIP_CFG_w,
  d2l_NVDLA_CACC_D_CLIP_CFG_we,
  d2l_NVDLA_CACC_D_CLIP_CFG_re,
  d2l_NVDLA_CACC_D_OUT_SATURATION_w,
  d2l_NVDLA_CACC_D_OUT_SATURATION_we,
  d2l_NVDLA_CACC_D_OUT_SATURATION_re,
  d2l_NVDLA_CACC_D_CYA_w,
  d2l_NVDLA_CACC_D_CYA_we,
  d2l_NVDLA_CACC_D_CYA_re,
  h2l_NVDLA_CACC_S_STATUS_STATUS_0_w,
  h2l_NVDLA_CACC_S_STATUS_STATUS_1_w,
  h2l_NVDLA_CACC_S_POINTER_CONSUMER_w,
  h2l_NVDLA_CACC_D_OUT_SATURATION_SAT_COUNT_w,

  l2d_NVDLA_CACC_S_STATUS_r,
  l2d_NVDLA_CACC_S_POINTER_r,
  l2d_NVDLA_CACC_D_OP_ENABLE_r,
  l2d_NVDLA_CACC_D_MISC_CFG_r,
  l2d_NVDLA_CACC_D_DATAOUT_SIZE_0_r,
  l2d_NVDLA_CACC_D_DATAOUT_SIZE_1_r,
  l2d_NVDLA_CACC_D_DATAOUT_ADDR_r,
  l2d_NVDLA_CACC_D_BATCH_NUMBER_r,
  l2d_NVDLA_CACC_D_LINE_STRIDE_r,
  l2d_NVDLA_CACC_D_SURF_STRIDE_r,
  l2d_NVDLA_CACC_D_DATAOUT_MAP_r,
  l2d_NVDLA_CACC_D_CLIP_CFG_r,
  l2d_NVDLA_CACC_D_OUT_SATURATION_r,
  l2d_NVDLA_CACC_D_CYA_r,
  l2h_NVDLA_CACC_S_POINTER_PRODUCER_r,
  l2h_NVDLA_CACC_D_OP_ENABLE_OP_EN_r,
  l2h_NVDLA_CACC_D_MISC_CFG_CONV_MODE_r,
  l2h_NVDLA_CACC_D_MISC_CFG_PROC_PRECISION_r,
  l2h_NVDLA_CACC_D_DATAOUT_SIZE_0_DATAOUT_WIDTH_r,
  l2h_NVDLA_CACC_D_DATAOUT_SIZE_0_DATAOUT_HEIGHT_r,
  l2h_NVDLA_CACC_D_DATAOUT_SIZE_1_DATAOUT_CHANNEL_r,
  l2h_NVDLA_CACC_D_DATAOUT_ADDR_DATAOUT_ADDR_r,
  l2h_NVDLA_CACC_D_BATCH_NUMBER_BATCHES_r,
  l2h_NVDLA_CACC_D_LINE_STRIDE_LINE_STRIDE_r,
  l2h_NVDLA_CACC_D_SURF_STRIDE_SURF_STRIDE_r,
  l2h_NVDLA_CACC_D_DATAOUT_MAP_LINE_PACKED_r,
  l2h_NVDLA_CACC_D_DATAOUT_MAP_SURF_PACKED_r,
  l2h_NVDLA_CACC_D_CLIP_CFG_CLIP_TRUNCATE_r,
  l2h_NVDLA_CACC_D_CYA_CYA_r );

  //------- inputs
  input    clk;
  input    reset;
  input     [31:0] d2l_NVDLA_CACC_S_STATUS_w;
  input    d2l_NVDLA_CACC_S_STATUS_we;
  input    d2l_NVDLA_CACC_S_STATUS_re;
  input     [31:0] d2l_NVDLA_CACC_S_POINTER_w;
  input    d2l_NVDLA_CACC_S_POINTER_we;
  input    d2l_NVDLA_CACC_S_POINTER_re;
  input     [31:0] d2l_NVDLA_CACC_D_OP_ENABLE_w;
  input    d2l_NVDLA_CACC_D_OP_ENABLE_we;
  input    d2l_NVDLA_CACC_D_OP_ENABLE_re;
  input     [31:0] d2l_NVDLA_CACC_D_MISC_CFG_w;
  input    d2l_NVDLA_CACC_D_MISC_CFG_we;
  input    d2l_NVDLA_CACC_D_MISC_CFG_re;
  input     [31:0] d2l_NVDLA_CACC_D_DATAOUT_SIZE_0_w;
  input    d2l_NVDLA_CACC_D_DATAOUT_SIZE_0_we;
  input    d2l_NVDLA_CACC_D_DATAOUT_SIZE_0_re;
  input     [31:0] d2l_NVDLA_CACC_D_DATAOUT_SIZE_1_w;
  input    d2l_NVDLA_CACC_D_DATAOUT_SIZE_1_we;
  input    d2l_NVDLA_CACC_D_DATAOUT_SIZE_1_re;
  input     [31:0] d2l_NVDLA_CACC_D_DATAOUT_ADDR_w;
  input    d2l_NVDLA_CACC_D_DATAOUT_ADDR_we;
  input    d2l_NVDLA_CACC_D_DATAOUT_ADDR_re;
  input     [31:0] d2l_NVDLA_CACC_D_BATCH_NUMBER_w;
  input    d2l_NVDLA_CACC_D_BATCH_NUMBER_we;
  input    d2l_NVDLA_CACC_D_BATCH_NUMBER_re;
  input     [31:0] d2l_NVDLA_CACC_D_LINE_STRIDE_w;
  input    d2l_NVDLA_CACC_D_LINE_STRIDE_we;
  input    d2l_NVDLA_CACC_D_LINE_STRIDE_re;
  input     [31:0] d2l_NVDLA_CACC_D_SURF_STRIDE_w;
  input    d2l_NVDLA_CACC_D_SURF_STRIDE_we;
  input    d2l_NVDLA_CACC_D_SURF_STRIDE_re;
  input     [31:0] d2l_NVDLA_CACC_D_DATAOUT_MAP_w;
  input    d2l_NVDLA_CACC_D_DATAOUT_MAP_we;
  input    d2l_NVDLA_CACC_D_DATAOUT_MAP_re;
  input     [31:0] d2l_NVDLA_CACC_D_CLIP_CFG_w;
  input    d2l_NVDLA_CACC_D_CLIP_CFG_we;
  input    d2l_NVDLA_CACC_D_CLIP_CFG_re;
  input     [31:0] d2l_NVDLA_CACC_D_OUT_SATURATION_w;
  input    d2l_NVDLA_CACC_D_OUT_SATURATION_we;
  input    d2l_NVDLA_CACC_D_OUT_SATURATION_re;
  input     [31:0] d2l_NVDLA_CACC_D_CYA_w;
  input    d2l_NVDLA_CACC_D_CYA_we;
  input    d2l_NVDLA_CACC_D_CYA_re;
  input     [1:0] h2l_NVDLA_CACC_S_STATUS_STATUS_0_w;
  input     [1:0] h2l_NVDLA_CACC_S_STATUS_STATUS_1_w;
  input    h2l_NVDLA_CACC_S_POINTER_CONSUMER_w;
  input     [31:0] h2l_NVDLA_CACC_D_OUT_SATURATION_SAT_COUNT_w;

  //------- outputs
  output     [31:0] l2d_NVDLA_CACC_S_STATUS_r;
  output     [31:0] l2d_NVDLA_CACC_S_POINTER_r;
  output     [31:0] l2d_NVDLA_CACC_D_OP_ENABLE_r;
  output     [31:0] l2d_NVDLA_CACC_D_MISC_CFG_r;
  output     [31:0] l2d_NVDLA_CACC_D_DATAOUT_SIZE_0_r;
  output     [31:0] l2d_NVDLA_CACC_D_DATAOUT_SIZE_1_r;
  output     [31:0] l2d_NVDLA_CACC_D_DATAOUT_ADDR_r;
  output     [31:0] l2d_NVDLA_CACC_D_BATCH_NUMBER_r;
  output     [31:0] l2d_NVDLA_CACC_D_LINE_STRIDE_r;
  output     [31:0] l2d_NVDLA_CACC_D_SURF_STRIDE_r;
  output     [31:0] l2d_NVDLA_CACC_D_DATAOUT_MAP_r;
  output     [31:0] l2d_NVDLA_CACC_D_CLIP_CFG_r;
  output     [31:0] l2d_NVDLA_CACC_D_OUT_SATURATION_r;
  output     [31:0] l2d_NVDLA_CACC_D_CYA_r;
  output    l2h_NVDLA_CACC_S_POINTER_PRODUCER_r;
  output    l2h_NVDLA_CACC_D_OP_ENABLE_OP_EN_r;
  output    l2h_NVDLA_CACC_D_MISC_CFG_CONV_MODE_r;
  output     [1:0] l2h_NVDLA_CACC_D_MISC_CFG_PROC_PRECISION_r;
  output     [12:0] l2h_NVDLA_CACC_D_DATAOUT_SIZE_0_DATAOUT_WIDTH_r;
  output     [12:0] l2h_NVDLA_CACC_D_DATAOUT_SIZE_0_DATAOUT_HEIGHT_r;
  output     [12:0] l2h_NVDLA_CACC_D_DATAOUT_SIZE_1_DATAOUT_CHANNEL_r;
  output     [31:0] l2h_NVDLA_CACC_D_DATAOUT_ADDR_DATAOUT_ADDR_r;
  output     [4:0] l2h_NVDLA_CACC_D_BATCH_NUMBER_BATCHES_r;
  output     [23:0] l2h_NVDLA_CACC_D_LINE_STRIDE_LINE_STRIDE_r;
  output     [23:0] l2h_NVDLA_CACC_D_SURF_STRIDE_SURF_STRIDE_r;
  output    l2h_NVDLA_CACC_D_DATAOUT_MAP_LINE_PACKED_r;
  output    l2h_NVDLA_CACC_D_DATAOUT_MAP_SURF_PACKED_r;
  output     [4:0] l2h_NVDLA_CACC_D_CLIP_CFG_CLIP_TRUNCATE_r;
  output     [31:0] l2h_NVDLA_CACC_D_CYA_CYA_r;


  //------- reg defines
  reg   [1:0] rg_NVDLA_CACC_S_STATUS_STATUS_0;
  reg   [1:0] rg_NVDLA_CACC_S_STATUS_STATUS_1;
  reg   [31:0] l2d_NVDLA_CACC_S_STATUS_r;
  reg  rg_NVDLA_CACC_S_POINTER_PRODUCER;
  reg  reg_NVDLA_CACC_S_POINTER_PRODUCER_next;
  reg  l2h_NVDLA_CACC_S_POINTER_PRODUCER_r;
  reg  rg_NVDLA_CACC_S_POINTER_CONSUMER;
  reg   [31:0] l2d_NVDLA_CACC_S_POINTER_r;
  reg  rg_NVDLA_CACC_D_OP_ENABLE_OP_EN;
  reg  reg_NVDLA_CACC_D_OP_ENABLE_OP_EN_next;
  reg  l2h_NVDLA_CACC_D_OP_ENABLE_OP_EN_r;
  reg   [31:0] l2d_NVDLA_CACC_D_OP_ENABLE_r;
  reg  rg_NVDLA_CACC_D_MISC_CFG_CONV_MODE;
  reg  reg_NVDLA_CACC_D_MISC_CFG_CONV_MODE_next;
  reg  l2h_NVDLA_CACC_D_MISC_CFG_CONV_MODE_r;
  reg   [1:0] rg_NVDLA_CACC_D_MISC_CFG_PROC_PRECISION;
  reg   [1:0] reg_NVDLA_CACC_D_MISC_CFG_PROC_PRECISION_next;
  reg   [1:0] l2h_NVDLA_CACC_D_MISC_CFG_PROC_PRECISION_r;
  reg   [31:0] l2d_NVDLA_CACC_D_MISC_CFG_r;
  reg   [12:0] rg_NVDLA_CACC_D_DATAOUT_SIZE_0_DATAOUT_WIDTH;
  reg   [12:0] reg_NVDLA_CACC_D_DATAOUT_SIZE_0_DATAOUT_WIDTH_next;
  reg   [12:0] l2h_NVDLA_CACC_D_DATAOUT_SIZE_0_DATAOUT_WIDTH_r;
  reg   [12:0] rg_NVDLA_CACC_D_DATAOUT_SIZE_0_DATAOUT_HEIGHT;
  reg   [12:0] reg_NVDLA_CACC_D_DATAOUT_SIZE_0_DATAOUT_HEIGHT_next;
  reg   [12:0] l2h_NVDLA_CACC_D_DATAOUT_SIZE_0_DATAOUT_HEIGHT_r;
  reg   [31:0] l2d_NVDLA_CACC_D_DATAOUT_SIZE_0_r;
  reg   [12:0] rg_NVDLA_CACC_D_DATAOUT_SIZE_1_DATAOUT_CHANNEL;
  reg   [12:0] reg_NVDLA_CACC_D_DATAOUT_SIZE_1_DATAOUT_CHANNEL_next;
  reg   [12:0] l2h_NVDLA_CACC_D_DATAOUT_SIZE_1_DATAOUT_CHANNEL_r;
  reg   [31:0] l2d_NVDLA_CACC_D_DATAOUT_SIZE_1_r;
  reg   [31:0] rg_NVDLA_CACC_D_DATAOUT_ADDR_DATAOUT_ADDR;
  reg   [31:0] reg_NVDLA_CACC_D_DATAOUT_ADDR_DATAOUT_ADDR_next;
  reg   [31:0] l2h_NVDLA_CACC_D_DATAOUT_ADDR_DATAOUT_ADDR_r;
  reg   [31:0] l2d_NVDLA_CACC_D_DATAOUT_ADDR_r;
  reg   [4:0] rg_NVDLA_CACC_D_BATCH_NUMBER_BATCHES;
  reg   [4:0] reg_NVDLA_CACC_D_BATCH_NUMBER_BATCHES_next;
  reg   [4:0] l2h_NVDLA_CACC_D_BATCH_NUMBER_BATCHES_r;
  reg   [31:0] l2d_NVDLA_CACC_D_BATCH_NUMBER_r;
  reg   [23:0] rg_NVDLA_CACC_D_LINE_STRIDE_LINE_STRIDE;
  reg   [23:0] reg_NVDLA_CACC_D_LINE_STRIDE_LINE_STRIDE_next;
  reg   [23:0] l2h_NVDLA_CACC_D_LINE_STRIDE_LINE_STRIDE_r;
  reg   [31:0] l2d_NVDLA_CACC_D_LINE_STRIDE_r;
  reg   [23:0] rg_NVDLA_CACC_D_SURF_STRIDE_SURF_STRIDE;
  reg   [23:0] reg_NVDLA_CACC_D_SURF_STRIDE_SURF_STRIDE_next;
  reg   [23:0] l2h_NVDLA_CACC_D_SURF_STRIDE_SURF_STRIDE_r;
  reg   [31:0] l2d_NVDLA_CACC_D_SURF_STRIDE_r;
  reg  rg_NVDLA_CACC_D_DATAOUT_MAP_LINE_PACKED;
  reg  reg_NVDLA_CACC_D_DATAOUT_MAP_LINE_PACKED_next;
  reg  l2h_NVDLA_CACC_D_DATAOUT_MAP_LINE_PACKED_r;
  reg  rg_NVDLA_CACC_D_DATAOUT_MAP_SURF_PACKED;
  reg  reg_NVDLA_CACC_D_DATAOUT_MAP_SURF_PACKED_next;
  reg  l2h_NVDLA_CACC_D_DATAOUT_MAP_SURF_PACKED_r;
  reg   [31:0] l2d_NVDLA_CACC_D_DATAOUT_MAP_r;
  reg   [4:0] rg_NVDLA_CACC_D_CLIP_CFG_CLIP_TRUNCATE;
  reg   [4:0] reg_NVDLA_CACC_D_CLIP_CFG_CLIP_TRUNCATE_next;
  reg   [4:0] l2h_NVDLA_CACC_D_CLIP_CFG_CLIP_TRUNCATE_r;
  reg   [31:0] l2d_NVDLA_CACC_D_CLIP_CFG_r;
  reg   [31:0] rg_NVDLA_CACC_D_OUT_SATURATION_SAT_COUNT;
  reg   [31:0] l2d_NVDLA_CACC_D_OUT_SATURATION_r;
  reg   [31:0] rg_NVDLA_CACC_D_CYA_CYA;
  reg   [31:0] reg_NVDLA_CACC_D_CYA_CYA_next;
  reg   [31:0] l2h_NVDLA_CACC_D_CYA_CYA_r;
  reg   [31:0] l2d_NVDLA_CACC_D_CYA_r;
  
  
  //------- combinatorial assigns for NVDLA_CACC_D_CLIP_CFG (pio read data)
  always @ (*) begin
    l2d_NVDLA_CACC_D_CLIP_CFG_r = 32'b0;
    l2d_NVDLA_CACC_D_CLIP_CFG_r [4:0]  = rg_NVDLA_CACC_D_CLIP_CFG_CLIP_TRUNCATE;
  end
  
  //------- combinatorial assigns for NVDLA_CACC_D_BATCH_NUMBER (pio read data)
  always @ (*) begin
    l2d_NVDLA_CACC_D_BATCH_NUMBER_r = 32'b0;
    l2d_NVDLA_CACC_D_BATCH_NUMBER_r [4:0]  = rg_NVDLA_CACC_D_BATCH_NUMBER_BATCHES;
  end
  
  //------- combinatorial assigns for NVDLA_CACC_D_CLIP_CFG
  always @ (*) begin
    reg_NVDLA_CACC_D_CLIP_CFG_CLIP_TRUNCATE_next = rg_NVDLA_CACC_D_CLIP_CFG_CLIP_TRUNCATE;
    l2h_NVDLA_CACC_D_CLIP_CFG_CLIP_TRUNCATE_r = rg_NVDLA_CACC_D_CLIP_CFG_CLIP_TRUNCATE;
    if (d2l_NVDLA_CACC_D_CLIP_CFG_we) reg_NVDLA_CACC_D_CLIP_CFG_CLIP_TRUNCATE_next = d2l_NVDLA_CACC_D_CLIP_CFG_w [4:0] ;
  end
  
  //------- reg assigns for NVDLA_CACC_D_CLIP_CFG
  always @ (posedge clk) begin
    if (reset) begin
      rg_NVDLA_CACC_D_CLIP_CFG_CLIP_TRUNCATE <= #1 5'h0;
    end
    else begin
      rg_NVDLA_CACC_D_CLIP_CFG_CLIP_TRUNCATE <= #1  reg_NVDLA_CACC_D_CLIP_CFG_CLIP_TRUNCATE_next;
    end
  end
  
  //------- combinatorial assigns for NVDLA_CACC_D_SURF_STRIDE
  always @ (*) begin
    reg_NVDLA_CACC_D_SURF_STRIDE_SURF_STRIDE_next = rg_NVDLA_CACC_D_SURF_STRIDE_SURF_STRIDE;
    l2h_NVDLA_CACC_D_SURF_STRIDE_SURF_STRIDE_r = rg_NVDLA_CACC_D_SURF_STRIDE_SURF_STRIDE;
    if (d2l_NVDLA_CACC_D_SURF_STRIDE_we) reg_NVDLA_CACC_D_SURF_STRIDE_SURF_STRIDE_next = d2l_NVDLA_CACC_D_SURF_STRIDE_w [23:0] ;
  end
  
  //------- reg assigns for NVDLA_CACC_D_SURF_STRIDE
  always @ (posedge clk) begin
    if (reset) begin
      rg_NVDLA_CACC_D_SURF_STRIDE_SURF_STRIDE <= #1 24'h0;
    end
    else begin
      rg_NVDLA_CACC_D_SURF_STRIDE_SURF_STRIDE <= #1  reg_NVDLA_CACC_D_SURF_STRIDE_SURF_STRIDE_next;
    end
  end
  
  //------- combinatorial assigns for NVDLA_CACC_D_DATAOUT_SIZE_0 (pio read data)
  always @ (*) begin
    l2d_NVDLA_CACC_D_DATAOUT_SIZE_0_r = 32'b0;
    l2d_NVDLA_CACC_D_DATAOUT_SIZE_0_r [12:0]  = rg_NVDLA_CACC_D_DATAOUT_SIZE_0_DATAOUT_WIDTH;
    l2d_NVDLA_CACC_D_DATAOUT_SIZE_0_r [28:16]  = rg_NVDLA_CACC_D_DATAOUT_SIZE_0_DATAOUT_HEIGHT;
  end
  
  //------- combinatorial assigns for NVDLA_CACC_D_LINE_STRIDE
  always @ (*) begin
    reg_NVDLA_CACC_D_LINE_STRIDE_LINE_STRIDE_next = rg_NVDLA_CACC_D_LINE_STRIDE_LINE_STRIDE;
    l2h_NVDLA_CACC_D_LINE_STRIDE_LINE_STRIDE_r = rg_NVDLA_CACC_D_LINE_STRIDE_LINE_STRIDE;
    if (d2l_NVDLA_CACC_D_LINE_STRIDE_we) reg_NVDLA_CACC_D_LINE_STRIDE_LINE_STRIDE_next = d2l_NVDLA_CACC_D_LINE_STRIDE_w [23:0] ;
  end
  
  //------- reg assigns for NVDLA_CACC_D_LINE_STRIDE
  always @ (posedge clk) begin
    if (reset) begin
      rg_NVDLA_CACC_D_LINE_STRIDE_LINE_STRIDE <= #1 24'h0;
    end
    else begin
      rg_NVDLA_CACC_D_LINE_STRIDE_LINE_STRIDE <= #1  reg_NVDLA_CACC_D_LINE_STRIDE_LINE_STRIDE_next;
    end
  end
  
  //------- combinatorial assigns for NVDLA_CACC_D_DATAOUT_SIZE_0
  always @ (*) begin
    reg_NVDLA_CACC_D_DATAOUT_SIZE_0_DATAOUT_WIDTH_next = rg_NVDLA_CACC_D_DATAOUT_SIZE_0_DATAOUT_WIDTH;
    l2h_NVDLA_CACC_D_DATAOUT_SIZE_0_DATAOUT_WIDTH_r = rg_NVDLA_CACC_D_DATAOUT_SIZE_0_DATAOUT_WIDTH;
    reg_NVDLA_CACC_D_DATAOUT_SIZE_0_DATAOUT_HEIGHT_next = rg_NVDLA_CACC_D_DATAOUT_SIZE_0_DATAOUT_HEIGHT;
    l2h_NVDLA_CACC_D_DATAOUT_SIZE_0_DATAOUT_HEIGHT_r = rg_NVDLA_CACC_D_DATAOUT_SIZE_0_DATAOUT_HEIGHT;
    if (d2l_NVDLA_CACC_D_DATAOUT_SIZE_0_we) reg_NVDLA_CACC_D_DATAOUT_SIZE_0_DATAOUT_WIDTH_next = d2l_NVDLA_CACC_D_DATAOUT_SIZE_0_w [12:0] ;
    if (d2l_NVDLA_CACC_D_DATAOUT_SIZE_0_we) reg_NVDLA_CACC_D_DATAOUT_SIZE_0_DATAOUT_HEIGHT_next = d2l_NVDLA_CACC_D_DATAOUT_SIZE_0_w [28:16] ;
  end
  
  //------- reg assigns for NVDLA_CACC_D_DATAOUT_SIZE_0
  always @ (posedge clk) begin
    if (reset) begin
      rg_NVDLA_CACC_D_DATAOUT_SIZE_0_DATAOUT_WIDTH <= #1 13'h0;
      rg_NVDLA_CACC_D_DATAOUT_SIZE_0_DATAOUT_HEIGHT <= #1 13'h0;
    end
    else begin
      rg_NVDLA_CACC_D_DATAOUT_SIZE_0_DATAOUT_WIDTH <= #1  reg_NVDLA_CACC_D_DATAOUT_SIZE_0_DATAOUT_WIDTH_next;
      rg_NVDLA_CACC_D_DATAOUT_SIZE_0_DATAOUT_HEIGHT <= #1  reg_NVDLA_CACC_D_DATAOUT_SIZE_0_DATAOUT_HEIGHT_next;
    end
  end
  
  //------- combinatorial assigns for NVDLA_CACC_S_STATUS (pio read data)
  always @ (*) begin
    l2d_NVDLA_CACC_S_STATUS_r = 32'b0;
    l2d_NVDLA_CACC_S_STATUS_r [1:0]  = rg_NVDLA_CACC_S_STATUS_STATUS_0;
    l2d_NVDLA_CACC_S_STATUS_r [17:16]  = rg_NVDLA_CACC_S_STATUS_STATUS_1;
  end
  
  //------- combinatorial assigns for NVDLA_CACC_D_MISC_CFG (pio read data)
  always @ (*) begin
    l2d_NVDLA_CACC_D_MISC_CFG_r = 32'b0;
    l2d_NVDLA_CACC_D_MISC_CFG_r [0]  = rg_NVDLA_CACC_D_MISC_CFG_CONV_MODE;
    l2d_NVDLA_CACC_D_MISC_CFG_r [13:12]  = rg_NVDLA_CACC_D_MISC_CFG_PROC_PRECISION;
  end
  
  //------- combinatorial assigns for NVDLA_CACC_D_DATAOUT_SIZE_1
  always @ (*) begin
    reg_NVDLA_CACC_D_DATAOUT_SIZE_1_DATAOUT_CHANNEL_next = rg_NVDLA_CACC_D_DATAOUT_SIZE_1_DATAOUT_CHANNEL;
    l2h_NVDLA_CACC_D_DATAOUT_SIZE_1_DATAOUT_CHANNEL_r = rg_NVDLA_CACC_D_DATAOUT_SIZE_1_DATAOUT_CHANNEL;
    if (d2l_NVDLA_CACC_D_DATAOUT_SIZE_1_we) reg_NVDLA_CACC_D_DATAOUT_SIZE_1_DATAOUT_CHANNEL_next = d2l_NVDLA_CACC_D_DATAOUT_SIZE_1_w [12:0] ;
  end
  
  //------- reg assigns for NVDLA_CACC_D_DATAOUT_SIZE_1
  always @ (posedge clk) begin
    if (reset) begin
      rg_NVDLA_CACC_D_DATAOUT_SIZE_1_DATAOUT_CHANNEL <= #1 13'h0;
    end
    else begin
      rg_NVDLA_CACC_D_DATAOUT_SIZE_1_DATAOUT_CHANNEL <= #1  reg_NVDLA_CACC_D_DATAOUT_SIZE_1_DATAOUT_CHANNEL_next;
    end
  end
  
  //------- combinatorial assigns for NVDLA_CACC_D_OP_ENABLE (pio read data)
  always @ (*) begin
    l2d_NVDLA_CACC_D_OP_ENABLE_r = 32'b0;
    l2d_NVDLA_CACC_D_OP_ENABLE_r [0]  = rg_NVDLA_CACC_D_OP_ENABLE_OP_EN;
  end
  
  //------- combinatorial assigns for NVDLA_CACC_D_CYA
  always @ (*) begin
    reg_NVDLA_CACC_D_CYA_CYA_next = rg_NVDLA_CACC_D_CYA_CYA;
    l2h_NVDLA_CACC_D_CYA_CYA_r = rg_NVDLA_CACC_D_CYA_CYA;
    if (d2l_NVDLA_CACC_D_CYA_we) reg_NVDLA_CACC_D_CYA_CYA_next = d2l_NVDLA_CACC_D_CYA_w;
  end
  
  //------- reg assigns for NVDLA_CACC_D_CYA
  always @ (posedge clk) begin
    if (reset) begin
      rg_NVDLA_CACC_D_CYA_CYA <= #1 32'h0;
    end
    else begin
      rg_NVDLA_CACC_D_CYA_CYA <= #1  reg_NVDLA_CACC_D_CYA_CYA_next;
    end
  end
  
  //------- combinatorial assigns for NVDLA_CACC_D_MISC_CFG
  always @ (*) begin
    reg_NVDLA_CACC_D_MISC_CFG_CONV_MODE_next = rg_NVDLA_CACC_D_MISC_CFG_CONV_MODE;
    l2h_NVDLA_CACC_D_MISC_CFG_CONV_MODE_r = rg_NVDLA_CACC_D_MISC_CFG_CONV_MODE;
    reg_NVDLA_CACC_D_MISC_CFG_PROC_PRECISION_next = rg_NVDLA_CACC_D_MISC_CFG_PROC_PRECISION;
    l2h_NVDLA_CACC_D_MISC_CFG_PROC_PRECISION_r = rg_NVDLA_CACC_D_MISC_CFG_PROC_PRECISION;
    if (d2l_NVDLA_CACC_D_MISC_CFG_we) reg_NVDLA_CACC_D_MISC_CFG_CONV_MODE_next = d2l_NVDLA_CACC_D_MISC_CFG_w [0] ;
    if (d2l_NVDLA_CACC_D_MISC_CFG_we) reg_NVDLA_CACC_D_MISC_CFG_PROC_PRECISION_next = d2l_NVDLA_CACC_D_MISC_CFG_w [13:12] ;
  end
  
  //------- reg assigns for NVDLA_CACC_D_MISC_CFG
  always @ (posedge clk) begin
    if (reset) begin
      rg_NVDLA_CACC_D_MISC_CFG_CONV_MODE <= #1 1'h0;
      rg_NVDLA_CACC_D_MISC_CFG_PROC_PRECISION <= #1 2'h1;
    end
    else begin
      rg_NVDLA_CACC_D_MISC_CFG_CONV_MODE <= #1  reg_NVDLA_CACC_D_MISC_CFG_CONV_MODE_next;
      rg_NVDLA_CACC_D_MISC_CFG_PROC_PRECISION <= #1  reg_NVDLA_CACC_D_MISC_CFG_PROC_PRECISION_next;
    end
  end
  
  //------- combinatorial assigns for NVDLA_CACC_D_SURF_STRIDE (pio read data)
  always @ (*) begin
    l2d_NVDLA_CACC_D_SURF_STRIDE_r = 32'b0;
    l2d_NVDLA_CACC_D_SURF_STRIDE_r [23:0]  = rg_NVDLA_CACC_D_SURF_STRIDE_SURF_STRIDE;
  end
  
  //------- combinatorial assigns for NVDLA_CACC_D_OUT_SATURATION
  always @ (*) begin
    rg_NVDLA_CACC_D_OUT_SATURATION_SAT_COUNT =  h2l_NVDLA_CACC_D_OUT_SATURATION_SAT_COUNT_w;
  end
  
  //------- combinatorial assigns for NVDLA_CACC_D_DATAOUT_ADDR (pio read data)
  always @ (*) begin
    l2d_NVDLA_CACC_D_DATAOUT_ADDR_r = rg_NVDLA_CACC_D_DATAOUT_ADDR_DATAOUT_ADDR;
  end
  
  //------- combinatorial assigns for NVDLA_CACC_D_DATAOUT_MAP
  always @ (*) begin
    reg_NVDLA_CACC_D_DATAOUT_MAP_LINE_PACKED_next = rg_NVDLA_CACC_D_DATAOUT_MAP_LINE_PACKED;
    l2h_NVDLA_CACC_D_DATAOUT_MAP_LINE_PACKED_r = rg_NVDLA_CACC_D_DATAOUT_MAP_LINE_PACKED;
    reg_NVDLA_CACC_D_DATAOUT_MAP_SURF_PACKED_next = rg_NVDLA_CACC_D_DATAOUT_MAP_SURF_PACKED;
    l2h_NVDLA_CACC_D_DATAOUT_MAP_SURF_PACKED_r = rg_NVDLA_CACC_D_DATAOUT_MAP_SURF_PACKED;
    if (d2l_NVDLA_CACC_D_DATAOUT_MAP_we) reg_NVDLA_CACC_D_DATAOUT_MAP_LINE_PACKED_next = d2l_NVDLA_CACC_D_DATAOUT_MAP_w [0] ;
    if (d2l_NVDLA_CACC_D_DATAOUT_MAP_we) reg_NVDLA_CACC_D_DATAOUT_MAP_SURF_PACKED_next = d2l_NVDLA_CACC_D_DATAOUT_MAP_w [16] ;
  end
  
  //------- reg assigns for NVDLA_CACC_D_DATAOUT_MAP
  always @ (posedge clk) begin
    if (reset) begin
      rg_NVDLA_CACC_D_DATAOUT_MAP_LINE_PACKED <= #1 1'h0;
      rg_NVDLA_CACC_D_DATAOUT_MAP_SURF_PACKED <= #1 1'h0;
    end
    else begin
      rg_NVDLA_CACC_D_DATAOUT_MAP_LINE_PACKED <= #1  reg_NVDLA_CACC_D_DATAOUT_MAP_LINE_PACKED_next;
      rg_NVDLA_CACC_D_DATAOUT_MAP_SURF_PACKED <= #1  reg_NVDLA_CACC_D_DATAOUT_MAP_SURF_PACKED_next;
    end
  end
  
  //------- combinatorial assigns for NVDLA_CACC_D_DATAOUT_ADDR
  always @ (*) begin
    reg_NVDLA_CACC_D_DATAOUT_ADDR_DATAOUT_ADDR_next = rg_NVDLA_CACC_D_DATAOUT_ADDR_DATAOUT_ADDR;
    l2h_NVDLA_CACC_D_DATAOUT_ADDR_DATAOUT_ADDR_r = rg_NVDLA_CACC_D_DATAOUT_ADDR_DATAOUT_ADDR;
    if (d2l_NVDLA_CACC_D_DATAOUT_ADDR_we) reg_NVDLA_CACC_D_DATAOUT_ADDR_DATAOUT_ADDR_next = d2l_NVDLA_CACC_D_DATAOUT_ADDR_w;
  end
  
  //------- reg assigns for NVDLA_CACC_D_DATAOUT_ADDR
  always @ (posedge clk) begin
    if (reset) begin
      rg_NVDLA_CACC_D_DATAOUT_ADDR_DATAOUT_ADDR <= #1 32'h0;
    end
    else begin
      rg_NVDLA_CACC_D_DATAOUT_ADDR_DATAOUT_ADDR <= #1  reg_NVDLA_CACC_D_DATAOUT_ADDR_DATAOUT_ADDR_next;
    end
  end
  
  //------- combinatorial assigns for NVDLA_CACC_D_LINE_STRIDE (pio read data)
  always @ (*) begin
    l2d_NVDLA_CACC_D_LINE_STRIDE_r = 32'b0;
    l2d_NVDLA_CACC_D_LINE_STRIDE_r [23:0]  = rg_NVDLA_CACC_D_LINE_STRIDE_LINE_STRIDE;
  end
  
  //------- combinatorial assigns for NVDLA_CACC_D_BATCH_NUMBER
  always @ (*) begin
    reg_NVDLA_CACC_D_BATCH_NUMBER_BATCHES_next = rg_NVDLA_CACC_D_BATCH_NUMBER_BATCHES;
    l2h_NVDLA_CACC_D_BATCH_NUMBER_BATCHES_r = rg_NVDLA_CACC_D_BATCH_NUMBER_BATCHES;
    if (d2l_NVDLA_CACC_D_BATCH_NUMBER_we) reg_NVDLA_CACC_D_BATCH_NUMBER_BATCHES_next = d2l_NVDLA_CACC_D_BATCH_NUMBER_w [4:0] ;
  end
  
  //------- reg assigns for NVDLA_CACC_D_BATCH_NUMBER
  always @ (posedge clk) begin
    if (reset) begin
      rg_NVDLA_CACC_D_BATCH_NUMBER_BATCHES <= #1 5'h0;
    end
    else begin
      rg_NVDLA_CACC_D_BATCH_NUMBER_BATCHES <= #1  reg_NVDLA_CACC_D_BATCH_NUMBER_BATCHES_next;
    end
  end
  
  //------- combinatorial assigns for NVDLA_CACC_D_OP_ENABLE
  always @ (*) begin
    reg_NVDLA_CACC_D_OP_ENABLE_OP_EN_next = rg_NVDLA_CACC_D_OP_ENABLE_OP_EN;
    l2h_NVDLA_CACC_D_OP_ENABLE_OP_EN_r = rg_NVDLA_CACC_D_OP_ENABLE_OP_EN;
    if (d2l_NVDLA_CACC_D_OP_ENABLE_we) reg_NVDLA_CACC_D_OP_ENABLE_OP_EN_next = d2l_NVDLA_CACC_D_OP_ENABLE_w [0] ;
  end
  
  //------- reg assigns for NVDLA_CACC_D_OP_ENABLE
  always @ (posedge clk) begin
    if (reset) begin
      rg_NVDLA_CACC_D_OP_ENABLE_OP_EN <= #1 1'h0;
    end
    else begin
      rg_NVDLA_CACC_D_OP_ENABLE_OP_EN <= #1  reg_NVDLA_CACC_D_OP_ENABLE_OP_EN_next;
    end
  end
  
  //------- combinatorial assigns for NVDLA_CACC_S_POINTER (pio read data)
  always @ (*) begin
    l2d_NVDLA_CACC_S_POINTER_r = 32'b0;
    l2d_NVDLA_CACC_S_POINTER_r [0]  = rg_NVDLA_CACC_S_POINTER_PRODUCER;
    l2d_NVDLA_CACC_S_POINTER_r [16]  = rg_NVDLA_CACC_S_POINTER_CONSUMER;
  end
  
  //------- combinatorial assigns for NVDLA_CACC_D_CYA (pio read data)
  always @ (*) begin
    l2d_NVDLA_CACC_D_CYA_r = rg_NVDLA_CACC_D_CYA_CYA;
  end
  
  //------- combinatorial assigns for NVDLA_CACC_D_DATAOUT_SIZE_1 (pio read data)
  always @ (*) begin
    l2d_NVDLA_CACC_D_DATAOUT_SIZE_1_r = 32'b0;
    l2d_NVDLA_CACC_D_DATAOUT_SIZE_1_r [12:0]  = rg_NVDLA_CACC_D_DATAOUT_SIZE_1_DATAOUT_CHANNEL;
  end
  
  //------- combinatorial assigns for NVDLA_CACC_S_POINTER
  always @ (*) begin
    reg_NVDLA_CACC_S_POINTER_PRODUCER_next = rg_NVDLA_CACC_S_POINTER_PRODUCER;
    l2h_NVDLA_CACC_S_POINTER_PRODUCER_r = rg_NVDLA_CACC_S_POINTER_PRODUCER;
    rg_NVDLA_CACC_S_POINTER_CONSUMER =  h2l_NVDLA_CACC_S_POINTER_CONSUMER_w;
    if (d2l_NVDLA_CACC_S_POINTER_we) reg_NVDLA_CACC_S_POINTER_PRODUCER_next = d2l_NVDLA_CACC_S_POINTER_w [0] ;
  end
  
  //------- reg assigns for NVDLA_CACC_S_POINTER
  always @ (posedge clk) begin
    if (reset) begin
      rg_NVDLA_CACC_S_POINTER_PRODUCER <= #1 1'h0;
    end
    else begin
      rg_NVDLA_CACC_S_POINTER_PRODUCER <= #1  reg_NVDLA_CACC_S_POINTER_PRODUCER_next;
    end
  end
  
  //------- combinatorial assigns for NVDLA_CACC_D_OUT_SATURATION (pio read data)
  always @ (*) begin
    l2d_NVDLA_CACC_D_OUT_SATURATION_r = rg_NVDLA_CACC_D_OUT_SATURATION_SAT_COUNT;
  end
  
  //------- combinatorial assigns for NVDLA_CACC_S_STATUS
  always @ (*) begin
    rg_NVDLA_CACC_S_STATUS_STATUS_0 =  h2l_NVDLA_CACC_S_STATUS_STATUS_0_w;
    rg_NVDLA_CACC_S_STATUS_STATUS_1 =  h2l_NVDLA_CACC_S_STATUS_STATUS_1_w;
  end
  
  //------- combinatorial assigns for NVDLA_CACC_D_DATAOUT_MAP (pio read data)
  always @ (*) begin
    l2d_NVDLA_CACC_D_DATAOUT_MAP_r = 32'b0;
    l2d_NVDLA_CACC_D_DATAOUT_MAP_r [0]  = rg_NVDLA_CACC_D_DATAOUT_MAP_LINE_PACKED;
    l2d_NVDLA_CACC_D_DATAOUT_MAP_r [16]  = rg_NVDLA_CACC_D_DATAOUT_MAP_SURF_PACKED;
  end
  
endmodule

//
//---------- module addrmap_NVDLA_jrdl_decode
//
module addrmap_NVDLA_jrdl_decode
(
  clk,
  reset,
  leaf_dec_wr_data,
  leaf_dec_addr,
  leaf_dec_block_sel,
  leaf_dec_valid,
  leaf_dec_wr_dvld,
  leaf_dec_cycle,
  leaf_dec_wr_width,
  l2d_NVDLA_CACC_S_STATUS_r,
  l2d_NVDLA_CACC_S_POINTER_r,
  l2d_NVDLA_CACC_D_OP_ENABLE_r,
  l2d_NVDLA_CACC_D_MISC_CFG_r,
  l2d_NVDLA_CACC_D_DATAOUT_SIZE_0_r,
  l2d_NVDLA_CACC_D_DATAOUT_SIZE_1_r,
  l2d_NVDLA_CACC_D_DATAOUT_ADDR_r,
  l2d_NVDLA_CACC_D_BATCH_NUMBER_r,
  l2d_NVDLA_CACC_D_LINE_STRIDE_r,
  l2d_NVDLA_CACC_D_SURF_STRIDE_r,
  l2d_NVDLA_CACC_D_DATAOUT_MAP_r,
  l2d_NVDLA_CACC_D_CLIP_CFG_r,
  l2d_NVDLA_CACC_D_OUT_SATURATION_r,
  l2d_NVDLA_CACC_D_CYA_r,

  dec_leaf_rd_data,
  dec_leaf_ack,
  dec_leaf_nack,
  dec_leaf_accept,
  dec_leaf_reject,
  dec_leaf_retry_atomic,
  dec_leaf_data_width,
  d2l_NVDLA_CACC_S_STATUS_w,
  d2l_NVDLA_CACC_S_STATUS_we,
  d2l_NVDLA_CACC_S_STATUS_re,
  d2l_NVDLA_CACC_S_POINTER_w,
  d2l_NVDLA_CACC_S_POINTER_we,
  d2l_NVDLA_CACC_S_POINTER_re,
  d2l_NVDLA_CACC_D_OP_ENABLE_w,
  d2l_NVDLA_CACC_D_OP_ENABLE_we,
  d2l_NVDLA_CACC_D_OP_ENABLE_re,
  d2l_NVDLA_CACC_D_MISC_CFG_w,
  d2l_NVDLA_CACC_D_MISC_CFG_we,
  d2l_NVDLA_CACC_D_MISC_CFG_re,
  d2l_NVDLA_CACC_D_DATAOUT_SIZE_0_w,
  d2l_NVDLA_CACC_D_DATAOUT_SIZE_0_we,
  d2l_NVDLA_CACC_D_DATAOUT_SIZE_0_re,
  d2l_NVDLA_CACC_D_DATAOUT_SIZE_1_w,
  d2l_NVDLA_CACC_D_DATAOUT_SIZE_1_we,
  d2l_NVDLA_CACC_D_DATAOUT_SIZE_1_re,
  d2l_NVDLA_CACC_D_DATAOUT_ADDR_w,
  d2l_NVDLA_CACC_D_DATAOUT_ADDR_we,
  d2l_NVDLA_CACC_D_DATAOUT_ADDR_re,
  d2l_NVDLA_CACC_D_BATCH_NUMBER_w,
  d2l_NVDLA_CACC_D_BATCH_NUMBER_we,
  d2l_NVDLA_CACC_D_BATCH_NUMBER_re,
  d2l_NVDLA_CACC_D_LINE_STRIDE_w,
  d2l_NVDLA_CACC_D_LINE_STRIDE_we,
  d2l_NVDLA_CACC_D_LINE_STRIDE_re,
  d2l_NVDLA_CACC_D_SURF_STRIDE_w,
  d2l_NVDLA_CACC_D_SURF_STRIDE_we,
  d2l_NVDLA_CACC_D_SURF_STRIDE_re,
  d2l_NVDLA_CACC_D_DATAOUT_MAP_w,
  d2l_NVDLA_CACC_D_DATAOUT_MAP_we,
  d2l_NVDLA_CACC_D_DATAOUT_MAP_re,
  d2l_NVDLA_CACC_D_CLIP_CFG_w,
  d2l_NVDLA_CACC_D_CLIP_CFG_we,
  d2l_NVDLA_CACC_D_CLIP_CFG_re,
  d2l_NVDLA_CACC_D_OUT_SATURATION_w,
  d2l_NVDLA_CACC_D_OUT_SATURATION_we,
  d2l_NVDLA_CACC_D_OUT_SATURATION_re,
  d2l_NVDLA_CACC_D_CYA_w,
  d2l_NVDLA_CACC_D_CYA_we,
  d2l_NVDLA_CACC_D_CYA_re );

  //------- inputs
  input    clk;
  input    reset;
  input     [31:0] leaf_dec_wr_data;
  input     [39:0] leaf_dec_addr;
  input    leaf_dec_block_sel;
  input    leaf_dec_valid;
  input    leaf_dec_wr_dvld;
  input     [1:0] leaf_dec_cycle;
  input     [2:0] leaf_dec_wr_width;
  input     [31:0] l2d_NVDLA_CACC_S_STATUS_r;
  input     [31:0] l2d_NVDLA_CACC_S_POINTER_r;
  input     [31:0] l2d_NVDLA_CACC_D_OP_ENABLE_r;
  input     [31:0] l2d_NVDLA_CACC_D_MISC_CFG_r;
  input     [31:0] l2d_NVDLA_CACC_D_DATAOUT_SIZE_0_r;
  input     [31:0] l2d_NVDLA_CACC_D_DATAOUT_SIZE_1_r;
  input     [31:0] l2d_NVDLA_CACC_D_DATAOUT_ADDR_r;
  input     [31:0] l2d_NVDLA_CACC_D_BATCH_NUMBER_r;
  input     [31:0] l2d_NVDLA_CACC_D_LINE_STRIDE_r;
  input     [31:0] l2d_NVDLA_CACC_D_SURF_STRIDE_r;
  input     [31:0] l2d_NVDLA_CACC_D_DATAOUT_MAP_r;
  input     [31:0] l2d_NVDLA_CACC_D_CLIP_CFG_r;
  input     [31:0] l2d_NVDLA_CACC_D_OUT_SATURATION_r;
  input     [31:0] l2d_NVDLA_CACC_D_CYA_r;

  //------- outputs
  output     [31:0] dec_leaf_rd_data;
  output    dec_leaf_ack;
  output    dec_leaf_nack;
  output    dec_leaf_accept;
  output    dec_leaf_reject;
  output    dec_leaf_retry_atomic;
  output     [2:0] dec_leaf_data_width;
  output     [31:0] d2l_NVDLA_CACC_S_STATUS_w;
  output    d2l_NVDLA_CACC_S_STATUS_we;
  output    d2l_NVDLA_CACC_S_STATUS_re;
  output     [31:0] d2l_NVDLA_CACC_S_POINTER_w;
  output    d2l_NVDLA_CACC_S_POINTER_we;
  output    d2l_NVDLA_CACC_S_POINTER_re;
  output     [31:0] d2l_NVDLA_CACC_D_OP_ENABLE_w;
  output    d2l_NVDLA_CACC_D_OP_ENABLE_we;
  output    d2l_NVDLA_CACC_D_OP_ENABLE_re;
  output     [31:0] d2l_NVDLA_CACC_D_MISC_CFG_w;
  output    d2l_NVDLA_CACC_D_MISC_CFG_we;
  output    d2l_NVDLA_CACC_D_MISC_CFG_re;
  output     [31:0] d2l_NVDLA_CACC_D_DATAOUT_SIZE_0_w;
  output    d2l_NVDLA_CACC_D_DATAOUT_SIZE_0_we;
  output    d2l_NVDLA_CACC_D_DATAOUT_SIZE_0_re;
  output     [31:0] d2l_NVDLA_CACC_D_DATAOUT_SIZE_1_w;
  output    d2l_NVDLA_CACC_D_DATAOUT_SIZE_1_we;
  output    d2l_NVDLA_CACC_D_DATAOUT_SIZE_1_re;
  output     [31:0] d2l_NVDLA_CACC_D_DATAOUT_ADDR_w;
  output    d2l_NVDLA_CACC_D_DATAOUT_ADDR_we;
  output    d2l_NVDLA_CACC_D_DATAOUT_ADDR_re;
  output     [31:0] d2l_NVDLA_CACC_D_BATCH_NUMBER_w;
  output    d2l_NVDLA_CACC_D_BATCH_NUMBER_we;
  output    d2l_NVDLA_CACC_D_BATCH_NUMBER_re;
  output     [31:0] d2l_NVDLA_CACC_D_LINE_STRIDE_w;
  output    d2l_NVDLA_CACC_D_LINE_STRIDE_we;
  output    d2l_NVDLA_CACC_D_LINE_STRIDE_re;
  output     [31:0] d2l_NVDLA_CACC_D_SURF_STRIDE_w;
  output    d2l_NVDLA_CACC_D_SURF_STRIDE_we;
  output    d2l_NVDLA_CACC_D_SURF_STRIDE_re;
  output     [31:0] d2l_NVDLA_CACC_D_DATAOUT_MAP_w;
  output    d2l_NVDLA_CACC_D_DATAOUT_MAP_we;
  output    d2l_NVDLA_CACC_D_DATAOUT_MAP_re;
  output     [31:0] d2l_NVDLA_CACC_D_CLIP_CFG_w;
  output    d2l_NVDLA_CACC_D_CLIP_CFG_we;
  output    d2l_NVDLA_CACC_D_CLIP_CFG_re;
  output     [31:0] d2l_NVDLA_CACC_D_OUT_SATURATION_w;
  output    d2l_NVDLA_CACC_D_OUT_SATURATION_we;
  output    d2l_NVDLA_CACC_D_OUT_SATURATION_re;
  output     [31:0] d2l_NVDLA_CACC_D_CYA_w;
  output    d2l_NVDLA_CACC_D_CYA_we;
  output    d2l_NVDLA_CACC_D_CYA_re;


  //------- wire defines
  wire   [31:0] pio_dec_write_data;
  wire   [14:2] pio_dec_address;
  wire  pio_dec_read;
  wire  pio_dec_write;
  wire   [39:0] block_sel_addr;
  wire  block_sel;
  wire  leaf_dec_valid_active;
  wire  leaf_dec_wr_dvld_active;
  
  //------- reg defines
  reg   [31:0] d2l_NVDLA_CACC_S_STATUS_w;
  reg  d2l_NVDLA_CACC_S_STATUS_we;
  reg  d2l_NVDLA_CACC_S_STATUS_re;
  reg   [31:0] d2l_NVDLA_CACC_S_POINTER_w;
  reg  d2l_NVDLA_CACC_S_POINTER_we;
  reg  d2l_NVDLA_CACC_S_POINTER_re;
  reg   [31:0] d2l_NVDLA_CACC_D_OP_ENABLE_w;
  reg  d2l_NVDLA_CACC_D_OP_ENABLE_we;
  reg  d2l_NVDLA_CACC_D_OP_ENABLE_re;
  reg   [31:0] d2l_NVDLA_CACC_D_MISC_CFG_w;
  reg  d2l_NVDLA_CACC_D_MISC_CFG_we;
  reg  d2l_NVDLA_CACC_D_MISC_CFG_re;
  reg   [31:0] d2l_NVDLA_CACC_D_DATAOUT_SIZE_0_w;
  reg  d2l_NVDLA_CACC_D_DATAOUT_SIZE_0_we;
  reg  d2l_NVDLA_CACC_D_DATAOUT_SIZE_0_re;
  reg   [31:0] d2l_NVDLA_CACC_D_DATAOUT_SIZE_1_w;
  reg  d2l_NVDLA_CACC_D_DATAOUT_SIZE_1_we;
  reg  d2l_NVDLA_CACC_D_DATAOUT_SIZE_1_re;
  reg   [31:0] d2l_NVDLA_CACC_D_DATAOUT_ADDR_w;
  reg  d2l_NVDLA_CACC_D_DATAOUT_ADDR_we;
  reg  d2l_NVDLA_CACC_D_DATAOUT_ADDR_re;
  reg   [31:0] d2l_NVDLA_CACC_D_BATCH_NUMBER_w;
  reg  d2l_NVDLA_CACC_D_BATCH_NUMBER_we;
  reg  d2l_NVDLA_CACC_D_BATCH_NUMBER_re;
  reg   [31:0] d2l_NVDLA_CACC_D_LINE_STRIDE_w;
  reg  d2l_NVDLA_CACC_D_LINE_STRIDE_we;
  reg  d2l_NVDLA_CACC_D_LINE_STRIDE_re;
  reg   [31:0] d2l_NVDLA_CACC_D_SURF_STRIDE_w;
  reg  d2l_NVDLA_CACC_D_SURF_STRIDE_we;
  reg  d2l_NVDLA_CACC_D_SURF_STRIDE_re;
  reg   [31:0] d2l_NVDLA_CACC_D_DATAOUT_MAP_w;
  reg  d2l_NVDLA_CACC_D_DATAOUT_MAP_we;
  reg  d2l_NVDLA_CACC_D_DATAOUT_MAP_re;
  reg   [31:0] d2l_NVDLA_CACC_D_CLIP_CFG_w;
  reg  d2l_NVDLA_CACC_D_CLIP_CFG_we;
  reg  d2l_NVDLA_CACC_D_CLIP_CFG_re;
  reg   [31:0] d2l_NVDLA_CACC_D_OUT_SATURATION_w;
  reg  d2l_NVDLA_CACC_D_OUT_SATURATION_we;
  reg  d2l_NVDLA_CACC_D_OUT_SATURATION_re;
  reg   [31:0] d2l_NVDLA_CACC_D_CYA_w;
  reg  d2l_NVDLA_CACC_D_CYA_we;
  reg  d2l_NVDLA_CACC_D_CYA_re;
  reg  leaf_dec_valid_hld1;
  reg  leaf_dec_valid_hld1_next;
  reg  leaf_dec_wr_dvld_hld1;
  reg  leaf_dec_wr_dvld_hld1_next;
  reg  pio_write_active;
  reg  pio_read_active;
  reg   [14:2] pio_dec_address_d1;
  reg   [31:0] pio_dec_write_data_d1;
  reg   [31:0] dec_pio_read_data;
  reg   [31:0] dec_pio_read_data_d1;
  reg  dec_pio_ack;
  reg  dec_pio_nack;
  reg  dec_pio_ack_next;
  reg  dec_pio_nack_next;
  reg  pio_internal_ack;
  reg  pio_internal_nack;
  reg  pio_external_ack;
  reg  pio_external_nack;
  reg  pio_external_ack_next;
  reg  pio_external_nack_next;
  reg  pio_no_acks;
  reg  pio_activate_write;
  reg  pio_activate_read;
  reg   [31:0] dec_pio_read_data_next;
  reg  external_transaction_active;
  
  
  //------- assigns
  assign  pio_dec_write_data = leaf_dec_wr_data;
  assign  dec_leaf_rd_data = dec_pio_read_data;
  assign  dec_leaf_ack = dec_pio_ack;
  assign  dec_leaf_nack = dec_pio_nack;
  assign  pio_dec_address = leaf_dec_addr [14:2] ;
  assign  block_sel_addr = 40'h0;
  assign  block_sel = leaf_dec_block_sel;
  assign  leaf_dec_wr_dvld_active = leaf_dec_wr_dvld | leaf_dec_wr_dvld_hld1;
  assign  leaf_dec_valid_active = leaf_dec_valid | leaf_dec_valid_hld1;
  assign  dec_leaf_accept = leaf_dec_valid & block_sel;
  assign  dec_leaf_reject = leaf_dec_valid & ~block_sel;
  assign  pio_dec_read = block_sel & leaf_dec_valid_active & (leaf_dec_cycle == 2'b10);
  assign  pio_dec_write = block_sel & leaf_dec_wr_dvld_active & (leaf_dec_cycle[1] == 1'b0);
  assign  dec_leaf_retry_atomic = 1'b0;
  assign  dec_leaf_data_width = 3'b0;
  
  //------- combinatorial assigns for pio read data
  always @ (*) begin
    dec_pio_read_data = dec_pio_read_data_d1;
  end
  
  //------- reg assigns for pio read data
  always @ (posedge clk) begin
    if (reset) begin
      dec_pio_read_data_d1 <= #1  32'b0;
    end
    else begin
      dec_pio_read_data_d1 <= #1 dec_pio_read_data_next;
    end
  end
  
  //------- reg assigns for pio i/f
  always @ (posedge clk) begin
    if (reset) begin
      pio_write_active <= #1  1'b0;
      pio_read_active <= #1  1'b0;
    end
    else begin
      pio_write_active <= #1  pio_write_active ? pio_no_acks : pio_activate_write;
      pio_read_active <= #1  pio_read_active ? pio_no_acks : pio_activate_read;
      pio_dec_address_d1 <= #1   pio_dec_address;
      pio_dec_write_data_d1 <= #1  pio_dec_write_data;
    end
  end
  
  //------- combinatorial assigns for leaf i/f
  always @ (*) begin
    leaf_dec_valid_hld1_next = leaf_dec_valid | leaf_dec_valid_hld1;
    if (dec_pio_ack_next | dec_pio_nack_next) leaf_dec_valid_hld1_next = 1'b0;
    leaf_dec_wr_dvld_hld1_next = leaf_dec_wr_dvld | leaf_dec_wr_dvld_hld1;
    if (dec_pio_ack_next | dec_pio_nack_next | leaf_dec_valid) leaf_dec_wr_dvld_hld1_next = 1'b0;
  end
  
  //------- reg assigns for leaf i/f
  always @ (posedge clk) begin
    if (reset) begin
      leaf_dec_valid_hld1 <= #1  1'b0;
      leaf_dec_wr_dvld_hld1 <= #1  1'b0;
    end
    else begin
      leaf_dec_valid_hld1 <= #1 leaf_dec_valid_hld1_next;
      leaf_dec_wr_dvld_hld1 <= #1 leaf_dec_wr_dvld_hld1_next;
    end
  end
  
  //------- combinatorial assigns for pio ack/nack
  always @ (*) begin
    pio_internal_nack = (pio_read_active | pio_write_active) & ~pio_internal_ack & ~external_transaction_active;
    dec_pio_ack_next = (pio_internal_ack | (pio_external_ack_next & external_transaction_active));
    dec_pio_nack_next = (pio_internal_nack | (pio_external_nack_next & external_transaction_active));
    pio_no_acks = ~(dec_pio_ack | dec_pio_nack | pio_external_ack | pio_external_nack);
    pio_activate_write = (pio_dec_write & ~(dec_pio_ack | dec_pio_nack));
    pio_activate_read = (pio_dec_read & ~(dec_pio_ack | dec_pio_nack));
  end
  
  //------- reg assigns for pio ack/nack
  always @ (posedge clk) begin
    if (reset) begin
      dec_pio_ack <= #1 1'b0;
      dec_pio_nack <= #1 1'b0;
      pio_external_ack <= #1  1'b0;
      pio_external_nack <= #1  1'b0;
    end
    else begin
      dec_pio_ack <= #1 dec_pio_ack ? 1'b0 : dec_pio_ack_next;
      dec_pio_nack <= #1 dec_pio_nack ? 1'b0 : dec_pio_nack_next;
      pio_external_ack <= #1 pio_external_ack_next;
      pio_external_nack <= #1 pio_external_nack_next;
    end
  end
  
  
  //------- address decode
  always @ (*) begin
    pio_internal_ack = 1'b0;
    external_transaction_active = 1'b0;
    pio_external_ack_next = 1'b0;
    pio_external_nack_next = 1'b0;
    dec_pio_read_data_next = 32'b0;
    
    d2l_NVDLA_CACC_S_STATUS_w = pio_dec_write_data_d1  [31:0] ;
    d2l_NVDLA_CACC_S_STATUS_we = 1'b0;
    d2l_NVDLA_CACC_S_STATUS_re = 1'b0;
    d2l_NVDLA_CACC_S_POINTER_w = pio_dec_write_data_d1  [31:0] ;
    d2l_NVDLA_CACC_S_POINTER_we = 1'b0;
    d2l_NVDLA_CACC_S_POINTER_re = 1'b0;
    d2l_NVDLA_CACC_D_OP_ENABLE_w = pio_dec_write_data_d1  [31:0] ;
    d2l_NVDLA_CACC_D_OP_ENABLE_we = 1'b0;
    d2l_NVDLA_CACC_D_OP_ENABLE_re = 1'b0;
    d2l_NVDLA_CACC_D_MISC_CFG_w = pio_dec_write_data_d1  [31:0] ;
    d2l_NVDLA_CACC_D_MISC_CFG_we = 1'b0;
    d2l_NVDLA_CACC_D_MISC_CFG_re = 1'b0;
    d2l_NVDLA_CACC_D_DATAOUT_SIZE_0_w = pio_dec_write_data_d1  [31:0] ;
    d2l_NVDLA_CACC_D_DATAOUT_SIZE_0_we = 1'b0;
    d2l_NVDLA_CACC_D_DATAOUT_SIZE_0_re = 1'b0;
    d2l_NVDLA_CACC_D_DATAOUT_SIZE_1_w = pio_dec_write_data_d1  [31:0] ;
    d2l_NVDLA_CACC_D_DATAOUT_SIZE_1_we = 1'b0;
    d2l_NVDLA_CACC_D_DATAOUT_SIZE_1_re = 1'b0;
    d2l_NVDLA_CACC_D_DATAOUT_ADDR_w = pio_dec_write_data_d1  [31:0] ;
    d2l_NVDLA_CACC_D_DATAOUT_ADDR_we = 1'b0;
    d2l_NVDLA_CACC_D_DATAOUT_ADDR_re = 1'b0;
    d2l_NVDLA_CACC_D_BATCH_NUMBER_w = pio_dec_write_data_d1  [31:0] ;
    d2l_NVDLA_CACC_D_BATCH_NUMBER_we = 1'b0;
    d2l_NVDLA_CACC_D_BATCH_NUMBER_re = 1'b0;
    d2l_NVDLA_CACC_D_LINE_STRIDE_w = pio_dec_write_data_d1  [31:0] ;
    d2l_NVDLA_CACC_D_LINE_STRIDE_we = 1'b0;
    d2l_NVDLA_CACC_D_LINE_STRIDE_re = 1'b0;
    d2l_NVDLA_CACC_D_SURF_STRIDE_w = pio_dec_write_data_d1  [31:0] ;
    d2l_NVDLA_CACC_D_SURF_STRIDE_we = 1'b0;
    d2l_NVDLA_CACC_D_SURF_STRIDE_re = 1'b0;
    d2l_NVDLA_CACC_D_DATAOUT_MAP_w = pio_dec_write_data_d1  [31:0] ;
    d2l_NVDLA_CACC_D_DATAOUT_MAP_we = 1'b0;
    d2l_NVDLA_CACC_D_DATAOUT_MAP_re = 1'b0;
    d2l_NVDLA_CACC_D_CLIP_CFG_w = pio_dec_write_data_d1  [31:0] ;
    d2l_NVDLA_CACC_D_CLIP_CFG_we = 1'b0;
    d2l_NVDLA_CACC_D_CLIP_CFG_re = 1'b0;
    d2l_NVDLA_CACC_D_OUT_SATURATION_w = pio_dec_write_data_d1  [31:0] ;
    d2l_NVDLA_CACC_D_OUT_SATURATION_we = 1'b0;
    d2l_NVDLA_CACC_D_OUT_SATURATION_re = 1'b0;
    d2l_NVDLA_CACC_D_CYA_w = pio_dec_write_data_d1  [31:0] ;
    d2l_NVDLA_CACC_D_CYA_we = 1'b0;
    d2l_NVDLA_CACC_D_CYA_re = 1'b0;
    
    casez(pio_dec_address_d1)
    //  Register: NVDLA_CACC.S_STATUS     Address: 0x7000     External: false
    13'b1110000000000:
      begin
        d2l_NVDLA_CACC_S_STATUS_we = pio_write_active & ~dec_pio_ack;
        d2l_NVDLA_CACC_S_STATUS_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active;
        dec_pio_read_data_next  [31:0]  = l2d_NVDLA_CACC_S_STATUS_r;
      end
    //  Register: NVDLA_CACC.S_POINTER     Address: 0x7004     External: false
    13'b1110000000001:
      begin
        d2l_NVDLA_CACC_S_POINTER_we = pio_write_active & ~dec_pio_ack;
        d2l_NVDLA_CACC_S_POINTER_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_NVDLA_CACC_S_POINTER_r;
      end
    //  Register: NVDLA_CACC.D_OP_ENABLE     Address: 0x7008     External: false
    13'b1110000000010:
      begin
        d2l_NVDLA_CACC_D_OP_ENABLE_we = pio_write_active & ~dec_pio_ack;
        d2l_NVDLA_CACC_D_OP_ENABLE_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_NVDLA_CACC_D_OP_ENABLE_r;
      end
    //  Register: NVDLA_CACC.D_MISC_CFG     Address: 0x700c     External: false
    13'b1110000000011:
      begin
        d2l_NVDLA_CACC_D_MISC_CFG_we = pio_write_active & ~dec_pio_ack;
        d2l_NVDLA_CACC_D_MISC_CFG_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_NVDLA_CACC_D_MISC_CFG_r;
      end
    //  Register: NVDLA_CACC.D_DATAOUT_SIZE_0     Address: 0x7010     External: false
    13'b1110000000100:
      begin
        d2l_NVDLA_CACC_D_DATAOUT_SIZE_0_we = pio_write_active & ~dec_pio_ack;
        d2l_NVDLA_CACC_D_DATAOUT_SIZE_0_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_NVDLA_CACC_D_DATAOUT_SIZE_0_r;
      end
    //  Register: NVDLA_CACC.D_DATAOUT_SIZE_1     Address: 0x7014     External: false
    13'b1110000000101:
      begin
        d2l_NVDLA_CACC_D_DATAOUT_SIZE_1_we = pio_write_active & ~dec_pio_ack;
        d2l_NVDLA_CACC_D_DATAOUT_SIZE_1_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_NVDLA_CACC_D_DATAOUT_SIZE_1_r;
      end
    //  Register: NVDLA_CACC.D_DATAOUT_ADDR     Address: 0x7018     External: false
    13'b1110000000110:
      begin
        d2l_NVDLA_CACC_D_DATAOUT_ADDR_we = pio_write_active & ~dec_pio_ack;
        d2l_NVDLA_CACC_D_DATAOUT_ADDR_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_NVDLA_CACC_D_DATAOUT_ADDR_r;
      end
    //  Register: NVDLA_CACC.D_BATCH_NUMBER     Address: 0x701c     External: false
    13'b1110000000111:
      begin
        d2l_NVDLA_CACC_D_BATCH_NUMBER_we = pio_write_active & ~dec_pio_ack;
        d2l_NVDLA_CACC_D_BATCH_NUMBER_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_NVDLA_CACC_D_BATCH_NUMBER_r;
      end
    //  Register: NVDLA_CACC.D_LINE_STRIDE     Address: 0x7020     External: false
    13'b1110000001000:
      begin
        d2l_NVDLA_CACC_D_LINE_STRIDE_we = pio_write_active & ~dec_pio_ack;
        d2l_NVDLA_CACC_D_LINE_STRIDE_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_NVDLA_CACC_D_LINE_STRIDE_r;
      end
    //  Register: NVDLA_CACC.D_SURF_STRIDE     Address: 0x7024     External: false
    13'b1110000001001:
      begin
        d2l_NVDLA_CACC_D_SURF_STRIDE_we = pio_write_active & ~dec_pio_ack;
        d2l_NVDLA_CACC_D_SURF_STRIDE_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_NVDLA_CACC_D_SURF_STRIDE_r;
      end
    //  Register: NVDLA_CACC.D_DATAOUT_MAP     Address: 0x7028     External: false
    13'b1110000001010:
      begin
        d2l_NVDLA_CACC_D_DATAOUT_MAP_we = pio_write_active & ~dec_pio_ack;
        d2l_NVDLA_CACC_D_DATAOUT_MAP_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_NVDLA_CACC_D_DATAOUT_MAP_r;
      end
    //  Register: NVDLA_CACC.D_CLIP_CFG     Address: 0x702c     External: false
    13'b1110000001011:
      begin
        d2l_NVDLA_CACC_D_CLIP_CFG_we = pio_write_active & ~dec_pio_ack;
        d2l_NVDLA_CACC_D_CLIP_CFG_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_NVDLA_CACC_D_CLIP_CFG_r;
      end
    //  Register: NVDLA_CACC.D_OUT_SATURATION     Address: 0x7030     External: false
    13'b1110000001100:
      begin
        d2l_NVDLA_CACC_D_OUT_SATURATION_we = pio_write_active & ~dec_pio_ack;
        d2l_NVDLA_CACC_D_OUT_SATURATION_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active;
        dec_pio_read_data_next  [31:0]  = l2d_NVDLA_CACC_D_OUT_SATURATION_r;
      end
    //  Register: NVDLA_CACC.D_CYA     Address: 0x7034     External: false
    13'b1110000001101:
      begin
        d2l_NVDLA_CACC_D_CYA_we = pio_write_active & ~dec_pio_ack;
        d2l_NVDLA_CACC_D_CYA_re = pio_read_active & ~dec_pio_ack;
        pio_internal_ack =  pio_read_active | pio_write_active;
        dec_pio_read_data_next  [31:0]  = l2d_NVDLA_CACC_D_CYA_r;
      end
    endcase
  end
  
endmodule

//
//---------- module addrmap_NVDLA_pio
//
module addrmap_NVDLA_pio
(
  clk,
  reset,
  h2l_NVDLA_CACC_S_STATUS_STATUS_0_w,
  h2l_NVDLA_CACC_S_STATUS_STATUS_1_w,
  h2l_NVDLA_CACC_S_POINTER_CONSUMER_w,
  h2l_NVDLA_CACC_D_OUT_SATURATION_SAT_COUNT_w,
  leaf_dec_wr_data,
  leaf_dec_addr,
  leaf_dec_block_sel,
  leaf_dec_valid,
  leaf_dec_wr_dvld,
  leaf_dec_cycle,
  leaf_dec_wr_width,

  l2h_NVDLA_CACC_S_POINTER_PRODUCER_r,
  l2h_NVDLA_CACC_D_OP_ENABLE_OP_EN_r,
  l2h_NVDLA_CACC_D_MISC_CFG_CONV_MODE_r,
  l2h_NVDLA_CACC_D_MISC_CFG_PROC_PRECISION_r,
  l2h_NVDLA_CACC_D_DATAOUT_SIZE_0_DATAOUT_WIDTH_r,
  l2h_NVDLA_CACC_D_DATAOUT_SIZE_0_DATAOUT_HEIGHT_r,
  l2h_NVDLA_CACC_D_DATAOUT_SIZE_1_DATAOUT_CHANNEL_r,
  l2h_NVDLA_CACC_D_DATAOUT_ADDR_DATAOUT_ADDR_r,
  l2h_NVDLA_CACC_D_BATCH_NUMBER_BATCHES_r,
  l2h_NVDLA_CACC_D_LINE_STRIDE_LINE_STRIDE_r,
  l2h_NVDLA_CACC_D_SURF_STRIDE_SURF_STRIDE_r,
  l2h_NVDLA_CACC_D_DATAOUT_MAP_LINE_PACKED_r,
  l2h_NVDLA_CACC_D_DATAOUT_MAP_SURF_PACKED_r,
  l2h_NVDLA_CACC_D_CLIP_CFG_CLIP_TRUNCATE_r,
  l2h_NVDLA_CACC_D_CYA_CYA_r,
  dec_leaf_rd_data,
  dec_leaf_ack,
  dec_leaf_nack,
  dec_leaf_accept,
  dec_leaf_reject,
  dec_leaf_retry_atomic,
  dec_leaf_data_width );

  //------- inputs
  input    clk;
  input    reset;
  input     [1:0] h2l_NVDLA_CACC_S_STATUS_STATUS_0_w;
  input     [1:0] h2l_NVDLA_CACC_S_STATUS_STATUS_1_w;
  input    h2l_NVDLA_CACC_S_POINTER_CONSUMER_w;
  input     [31:0] h2l_NVDLA_CACC_D_OUT_SATURATION_SAT_COUNT_w;
  input     [31:0] leaf_dec_wr_data;
  input     [39:0] leaf_dec_addr;
  input    leaf_dec_block_sel;
  input    leaf_dec_valid;
  input    leaf_dec_wr_dvld;
  input     [1:0] leaf_dec_cycle;
  input     [2:0] leaf_dec_wr_width;

  //------- outputs
  output    l2h_NVDLA_CACC_S_POINTER_PRODUCER_r;
  output    l2h_NVDLA_CACC_D_OP_ENABLE_OP_EN_r;
  output    l2h_NVDLA_CACC_D_MISC_CFG_CONV_MODE_r;
  output     [1:0] l2h_NVDLA_CACC_D_MISC_CFG_PROC_PRECISION_r;
  output     [12:0] l2h_NVDLA_CACC_D_DATAOUT_SIZE_0_DATAOUT_WIDTH_r;
  output     [12:0] l2h_NVDLA_CACC_D_DATAOUT_SIZE_0_DATAOUT_HEIGHT_r;
  output     [12:0] l2h_NVDLA_CACC_D_DATAOUT_SIZE_1_DATAOUT_CHANNEL_r;
  output     [31:0] l2h_NVDLA_CACC_D_DATAOUT_ADDR_DATAOUT_ADDR_r;
  output     [4:0] l2h_NVDLA_CACC_D_BATCH_NUMBER_BATCHES_r;
  output     [23:0] l2h_NVDLA_CACC_D_LINE_STRIDE_LINE_STRIDE_r;
  output     [23:0] l2h_NVDLA_CACC_D_SURF_STRIDE_SURF_STRIDE_r;
  output    l2h_NVDLA_CACC_D_DATAOUT_MAP_LINE_PACKED_r;
  output    l2h_NVDLA_CACC_D_DATAOUT_MAP_SURF_PACKED_r;
  output     [4:0] l2h_NVDLA_CACC_D_CLIP_CFG_CLIP_TRUNCATE_r;
  output     [31:0] l2h_NVDLA_CACC_D_CYA_CYA_r;
  output     [31:0] dec_leaf_rd_data;
  output    dec_leaf_ack;
  output    dec_leaf_nack;
  output    dec_leaf_accept;
  output    dec_leaf_reject;
  output    dec_leaf_retry_atomic;
  output     [2:0] dec_leaf_data_width;


  //------- wire defines
  wire   [31:0] d2l_NVDLA_CACC_S_STATUS_w;
  wire  d2l_NVDLA_CACC_S_STATUS_we;
  wire  d2l_NVDLA_CACC_S_STATUS_re;
  wire   [31:0] d2l_NVDLA_CACC_S_POINTER_w;
  wire  d2l_NVDLA_CACC_S_POINTER_we;
  wire  d2l_NVDLA_CACC_S_POINTER_re;
  wire   [31:0] d2l_NVDLA_CACC_D_OP_ENABLE_w;
  wire  d2l_NVDLA_CACC_D_OP_ENABLE_we;
  wire  d2l_NVDLA_CACC_D_OP_ENABLE_re;
  wire   [31:0] d2l_NVDLA_CACC_D_MISC_CFG_w;
  wire  d2l_NVDLA_CACC_D_MISC_CFG_we;
  wire  d2l_NVDLA_CACC_D_MISC_CFG_re;
  wire   [31:0] d2l_NVDLA_CACC_D_DATAOUT_SIZE_0_w;
  wire  d2l_NVDLA_CACC_D_DATAOUT_SIZE_0_we;
  wire  d2l_NVDLA_CACC_D_DATAOUT_SIZE_0_re;
  wire   [31:0] d2l_NVDLA_CACC_D_DATAOUT_SIZE_1_w;
  wire  d2l_NVDLA_CACC_D_DATAOUT_SIZE_1_we;
  wire  d2l_NVDLA_CACC_D_DATAOUT_SIZE_1_re;
  wire   [31:0] d2l_NVDLA_CACC_D_DATAOUT_ADDR_w;
  wire  d2l_NVDLA_CACC_D_DATAOUT_ADDR_we;
  wire  d2l_NVDLA_CACC_D_DATAOUT_ADDR_re;
  wire   [31:0] d2l_NVDLA_CACC_D_BATCH_NUMBER_w;
  wire  d2l_NVDLA_CACC_D_BATCH_NUMBER_we;
  wire  d2l_NVDLA_CACC_D_BATCH_NUMBER_re;
  wire   [31:0] d2l_NVDLA_CACC_D_LINE_STRIDE_w;
  wire  d2l_NVDLA_CACC_D_LINE_STRIDE_we;
  wire  d2l_NVDLA_CACC_D_LINE_STRIDE_re;
  wire   [31:0] d2l_NVDLA_CACC_D_SURF_STRIDE_w;
  wire  d2l_NVDLA_CACC_D_SURF_STRIDE_we;
  wire  d2l_NVDLA_CACC_D_SURF_STRIDE_re;
  wire   [31:0] d2l_NVDLA_CACC_D_DATAOUT_MAP_w;
  wire  d2l_NVDLA_CACC_D_DATAOUT_MAP_we;
  wire  d2l_NVDLA_CACC_D_DATAOUT_MAP_re;
  wire   [31:0] d2l_NVDLA_CACC_D_CLIP_CFG_w;
  wire  d2l_NVDLA_CACC_D_CLIP_CFG_we;
  wire  d2l_NVDLA_CACC_D_CLIP_CFG_re;
  wire   [31:0] d2l_NVDLA_CACC_D_OUT_SATURATION_w;
  wire  d2l_NVDLA_CACC_D_OUT_SATURATION_we;
  wire  d2l_NVDLA_CACC_D_OUT_SATURATION_re;
  wire   [31:0] d2l_NVDLA_CACC_D_CYA_w;
  wire  d2l_NVDLA_CACC_D_CYA_we;
  wire  d2l_NVDLA_CACC_D_CYA_re;
  wire   [31:0] l2d_NVDLA_CACC_S_STATUS_r;
  wire   [31:0] l2d_NVDLA_CACC_S_POINTER_r;
  wire   [31:0] l2d_NVDLA_CACC_D_OP_ENABLE_r;
  wire   [31:0] l2d_NVDLA_CACC_D_MISC_CFG_r;
  wire   [31:0] l2d_NVDLA_CACC_D_DATAOUT_SIZE_0_r;
  wire   [31:0] l2d_NVDLA_CACC_D_DATAOUT_SIZE_1_r;
  wire   [31:0] l2d_NVDLA_CACC_D_DATAOUT_ADDR_r;
  wire   [31:0] l2d_NVDLA_CACC_D_BATCH_NUMBER_r;
  wire   [31:0] l2d_NVDLA_CACC_D_LINE_STRIDE_r;
  wire   [31:0] l2d_NVDLA_CACC_D_SURF_STRIDE_r;
  wire   [31:0] l2d_NVDLA_CACC_D_DATAOUT_MAP_r;
  wire   [31:0] l2d_NVDLA_CACC_D_CLIP_CFG_r;
  wire   [31:0] l2d_NVDLA_CACC_D_OUT_SATURATION_r;
  wire   [31:0] l2d_NVDLA_CACC_D_CYA_r;
  
  
  addrmap_NVDLA_jrdl_decode pio_decode (
    .clk(clk),
    .reset(reset),
    .leaf_dec_wr_data(leaf_dec_wr_data),
    .leaf_dec_addr(leaf_dec_addr),
    .leaf_dec_block_sel(leaf_dec_block_sel),
    .leaf_dec_valid(leaf_dec_valid),
    .leaf_dec_wr_dvld(leaf_dec_wr_dvld),
    .leaf_dec_cycle(leaf_dec_cycle),
    .leaf_dec_wr_width(leaf_dec_wr_width),
    .l2d_NVDLA_CACC_S_STATUS_r(l2d_NVDLA_CACC_S_STATUS_r),
    .l2d_NVDLA_CACC_S_POINTER_r(l2d_NVDLA_CACC_S_POINTER_r),
    .l2d_NVDLA_CACC_D_OP_ENABLE_r(l2d_NVDLA_CACC_D_OP_ENABLE_r),
    .l2d_NVDLA_CACC_D_MISC_CFG_r(l2d_NVDLA_CACC_D_MISC_CFG_r),
    .l2d_NVDLA_CACC_D_DATAOUT_SIZE_0_r(l2d_NVDLA_CACC_D_DATAOUT_SIZE_0_r),
    .l2d_NVDLA_CACC_D_DATAOUT_SIZE_1_r(l2d_NVDLA_CACC_D_DATAOUT_SIZE_1_r),
    .l2d_NVDLA_CACC_D_DATAOUT_ADDR_r(l2d_NVDLA_CACC_D_DATAOUT_ADDR_r),
    .l2d_NVDLA_CACC_D_BATCH_NUMBER_r(l2d_NVDLA_CACC_D_BATCH_NUMBER_r),
    .l2d_NVDLA_CACC_D_LINE_STRIDE_r(l2d_NVDLA_CACC_D_LINE_STRIDE_r),
    .l2d_NVDLA_CACC_D_SURF_STRIDE_r(l2d_NVDLA_CACC_D_SURF_STRIDE_r),
    .l2d_NVDLA_CACC_D_DATAOUT_MAP_r(l2d_NVDLA_CACC_D_DATAOUT_MAP_r),
    .l2d_NVDLA_CACC_D_CLIP_CFG_r(l2d_NVDLA_CACC_D_CLIP_CFG_r),
    .l2d_NVDLA_CACC_D_OUT_SATURATION_r(l2d_NVDLA_CACC_D_OUT_SATURATION_r),
    .l2d_NVDLA_CACC_D_CYA_r(l2d_NVDLA_CACC_D_CYA_r),
    .dec_leaf_rd_data(dec_leaf_rd_data),
    .dec_leaf_ack(dec_leaf_ack),
    .dec_leaf_nack(dec_leaf_nack),
    .dec_leaf_accept(dec_leaf_accept),
    .dec_leaf_reject(dec_leaf_reject),
    .dec_leaf_retry_atomic(dec_leaf_retry_atomic),
    .dec_leaf_data_width(dec_leaf_data_width),
    .d2l_NVDLA_CACC_S_STATUS_w(d2l_NVDLA_CACC_S_STATUS_w),
    .d2l_NVDLA_CACC_S_STATUS_we(d2l_NVDLA_CACC_S_STATUS_we),
    .d2l_NVDLA_CACC_S_STATUS_re(d2l_NVDLA_CACC_S_STATUS_re),
    .d2l_NVDLA_CACC_S_POINTER_w(d2l_NVDLA_CACC_S_POINTER_w),
    .d2l_NVDLA_CACC_S_POINTER_we(d2l_NVDLA_CACC_S_POINTER_we),
    .d2l_NVDLA_CACC_S_POINTER_re(d2l_NVDLA_CACC_S_POINTER_re),
    .d2l_NVDLA_CACC_D_OP_ENABLE_w(d2l_NVDLA_CACC_D_OP_ENABLE_w),
    .d2l_NVDLA_CACC_D_OP_ENABLE_we(d2l_NVDLA_CACC_D_OP_ENABLE_we),
    .d2l_NVDLA_CACC_D_OP_ENABLE_re(d2l_NVDLA_CACC_D_OP_ENABLE_re),
    .d2l_NVDLA_CACC_D_MISC_CFG_w(d2l_NVDLA_CACC_D_MISC_CFG_w),
    .d2l_NVDLA_CACC_D_MISC_CFG_we(d2l_NVDLA_CACC_D_MISC_CFG_we),
    .d2l_NVDLA_CACC_D_MISC_CFG_re(d2l_NVDLA_CACC_D_MISC_CFG_re),
    .d2l_NVDLA_CACC_D_DATAOUT_SIZE_0_w(d2l_NVDLA_CACC_D_DATAOUT_SIZE_0_w),
    .d2l_NVDLA_CACC_D_DATAOUT_SIZE_0_we(d2l_NVDLA_CACC_D_DATAOUT_SIZE_0_we),
    .d2l_NVDLA_CACC_D_DATAOUT_SIZE_0_re(d2l_NVDLA_CACC_D_DATAOUT_SIZE_0_re),
    .d2l_NVDLA_CACC_D_DATAOUT_SIZE_1_w(d2l_NVDLA_CACC_D_DATAOUT_SIZE_1_w),
    .d2l_NVDLA_CACC_D_DATAOUT_SIZE_1_we(d2l_NVDLA_CACC_D_DATAOUT_SIZE_1_we),
    .d2l_NVDLA_CACC_D_DATAOUT_SIZE_1_re(d2l_NVDLA_CACC_D_DATAOUT_SIZE_1_re),
    .d2l_NVDLA_CACC_D_DATAOUT_ADDR_w(d2l_NVDLA_CACC_D_DATAOUT_ADDR_w),
    .d2l_NVDLA_CACC_D_DATAOUT_ADDR_we(d2l_NVDLA_CACC_D_DATAOUT_ADDR_we),
    .d2l_NVDLA_CACC_D_DATAOUT_ADDR_re(d2l_NVDLA_CACC_D_DATAOUT_ADDR_re),
    .d2l_NVDLA_CACC_D_BATCH_NUMBER_w(d2l_NVDLA_CACC_D_BATCH_NUMBER_w),
    .d2l_NVDLA_CACC_D_BATCH_NUMBER_we(d2l_NVDLA_CACC_D_BATCH_NUMBER_we),
    .d2l_NVDLA_CACC_D_BATCH_NUMBER_re(d2l_NVDLA_CACC_D_BATCH_NUMBER_re),
    .d2l_NVDLA_CACC_D_LINE_STRIDE_w(d2l_NVDLA_CACC_D_LINE_STRIDE_w),
    .d2l_NVDLA_CACC_D_LINE_STRIDE_we(d2l_NVDLA_CACC_D_LINE_STRIDE_we),
    .d2l_NVDLA_CACC_D_LINE_STRIDE_re(d2l_NVDLA_CACC_D_LINE_STRIDE_re),
    .d2l_NVDLA_CACC_D_SURF_STRIDE_w(d2l_NVDLA_CACC_D_SURF_STRIDE_w),
    .d2l_NVDLA_CACC_D_SURF_STRIDE_we(d2l_NVDLA_CACC_D_SURF_STRIDE_we),
    .d2l_NVDLA_CACC_D_SURF_STRIDE_re(d2l_NVDLA_CACC_D_SURF_STRIDE_re),
    .d2l_NVDLA_CACC_D_DATAOUT_MAP_w(d2l_NVDLA_CACC_D_DATAOUT_MAP_w),
    .d2l_NVDLA_CACC_D_DATAOUT_MAP_we(d2l_NVDLA_CACC_D_DATAOUT_MAP_we),
    .d2l_NVDLA_CACC_D_DATAOUT_MAP_re(d2l_NVDLA_CACC_D_DATAOUT_MAP_re),
    .d2l_NVDLA_CACC_D_CLIP_CFG_w(d2l_NVDLA_CACC_D_CLIP_CFG_w),
    .d2l_NVDLA_CACC_D_CLIP_CFG_we(d2l_NVDLA_CACC_D_CLIP_CFG_we),
    .d2l_NVDLA_CACC_D_CLIP_CFG_re(d2l_NVDLA_CACC_D_CLIP_CFG_re),
    .d2l_NVDLA_CACC_D_OUT_SATURATION_w(d2l_NVDLA_CACC_D_OUT_SATURATION_w),
    .d2l_NVDLA_CACC_D_OUT_SATURATION_we(d2l_NVDLA_CACC_D_OUT_SATURATION_we),
    .d2l_NVDLA_CACC_D_OUT_SATURATION_re(d2l_NVDLA_CACC_D_OUT_SATURATION_re),
    .d2l_NVDLA_CACC_D_CYA_w(d2l_NVDLA_CACC_D_CYA_w),
    .d2l_NVDLA_CACC_D_CYA_we(d2l_NVDLA_CACC_D_CYA_we),
    .d2l_NVDLA_CACC_D_CYA_re(d2l_NVDLA_CACC_D_CYA_re) );
    
  addrmap_NVDLA_jrdl_logic pio_logic (
    .clk(clk),
    .reset(reset),
    .d2l_NVDLA_CACC_S_STATUS_w(d2l_NVDLA_CACC_S_STATUS_w),
    .d2l_NVDLA_CACC_S_STATUS_we(d2l_NVDLA_CACC_S_STATUS_we),
    .d2l_NVDLA_CACC_S_STATUS_re(d2l_NVDLA_CACC_S_STATUS_re),
    .d2l_NVDLA_CACC_S_POINTER_w(d2l_NVDLA_CACC_S_POINTER_w),
    .d2l_NVDLA_CACC_S_POINTER_we(d2l_NVDLA_CACC_S_POINTER_we),
    .d2l_NVDLA_CACC_S_POINTER_re(d2l_NVDLA_CACC_S_POINTER_re),
    .d2l_NVDLA_CACC_D_OP_ENABLE_w(d2l_NVDLA_CACC_D_OP_ENABLE_w),
    .d2l_NVDLA_CACC_D_OP_ENABLE_we(d2l_NVDLA_CACC_D_OP_ENABLE_we),
    .d2l_NVDLA_CACC_D_OP_ENABLE_re(d2l_NVDLA_CACC_D_OP_ENABLE_re),
    .d2l_NVDLA_CACC_D_MISC_CFG_w(d2l_NVDLA_CACC_D_MISC_CFG_w),
    .d2l_NVDLA_CACC_D_MISC_CFG_we(d2l_NVDLA_CACC_D_MISC_CFG_we),
    .d2l_NVDLA_CACC_D_MISC_CFG_re(d2l_NVDLA_CACC_D_MISC_CFG_re),
    .d2l_NVDLA_CACC_D_DATAOUT_SIZE_0_w(d2l_NVDLA_CACC_D_DATAOUT_SIZE_0_w),
    .d2l_NVDLA_CACC_D_DATAOUT_SIZE_0_we(d2l_NVDLA_CACC_D_DATAOUT_SIZE_0_we),
    .d2l_NVDLA_CACC_D_DATAOUT_SIZE_0_re(d2l_NVDLA_CACC_D_DATAOUT_SIZE_0_re),
    .d2l_NVDLA_CACC_D_DATAOUT_SIZE_1_w(d2l_NVDLA_CACC_D_DATAOUT_SIZE_1_w),
    .d2l_NVDLA_CACC_D_DATAOUT_SIZE_1_we(d2l_NVDLA_CACC_D_DATAOUT_SIZE_1_we),
    .d2l_NVDLA_CACC_D_DATAOUT_SIZE_1_re(d2l_NVDLA_CACC_D_DATAOUT_SIZE_1_re),
    .d2l_NVDLA_CACC_D_DATAOUT_ADDR_w(d2l_NVDLA_CACC_D_DATAOUT_ADDR_w),
    .d2l_NVDLA_CACC_D_DATAOUT_ADDR_we(d2l_NVDLA_CACC_D_DATAOUT_ADDR_we),
    .d2l_NVDLA_CACC_D_DATAOUT_ADDR_re(d2l_NVDLA_CACC_D_DATAOUT_ADDR_re),
    .d2l_NVDLA_CACC_D_BATCH_NUMBER_w(d2l_NVDLA_CACC_D_BATCH_NUMBER_w),
    .d2l_NVDLA_CACC_D_BATCH_NUMBER_we(d2l_NVDLA_CACC_D_BATCH_NUMBER_we),
    .d2l_NVDLA_CACC_D_BATCH_NUMBER_re(d2l_NVDLA_CACC_D_BATCH_NUMBER_re),
    .d2l_NVDLA_CACC_D_LINE_STRIDE_w(d2l_NVDLA_CACC_D_LINE_STRIDE_w),
    .d2l_NVDLA_CACC_D_LINE_STRIDE_we(d2l_NVDLA_CACC_D_LINE_STRIDE_we),
    .d2l_NVDLA_CACC_D_LINE_STRIDE_re(d2l_NVDLA_CACC_D_LINE_STRIDE_re),
    .d2l_NVDLA_CACC_D_SURF_STRIDE_w(d2l_NVDLA_CACC_D_SURF_STRIDE_w),
    .d2l_NVDLA_CACC_D_SURF_STRIDE_we(d2l_NVDLA_CACC_D_SURF_STRIDE_we),
    .d2l_NVDLA_CACC_D_SURF_STRIDE_re(d2l_NVDLA_CACC_D_SURF_STRIDE_re),
    .d2l_NVDLA_CACC_D_DATAOUT_MAP_w(d2l_NVDLA_CACC_D_DATAOUT_MAP_w),
    .d2l_NVDLA_CACC_D_DATAOUT_MAP_we(d2l_NVDLA_CACC_D_DATAOUT_MAP_we),
    .d2l_NVDLA_CACC_D_DATAOUT_MAP_re(d2l_NVDLA_CACC_D_DATAOUT_MAP_re),
    .d2l_NVDLA_CACC_D_CLIP_CFG_w(d2l_NVDLA_CACC_D_CLIP_CFG_w),
    .d2l_NVDLA_CACC_D_CLIP_CFG_we(d2l_NVDLA_CACC_D_CLIP_CFG_we),
    .d2l_NVDLA_CACC_D_CLIP_CFG_re(d2l_NVDLA_CACC_D_CLIP_CFG_re),
    .d2l_NVDLA_CACC_D_OUT_SATURATION_w(d2l_NVDLA_CACC_D_OUT_SATURATION_w),
    .d2l_NVDLA_CACC_D_OUT_SATURATION_we(d2l_NVDLA_CACC_D_OUT_SATURATION_we),
    .d2l_NVDLA_CACC_D_OUT_SATURATION_re(d2l_NVDLA_CACC_D_OUT_SATURATION_re),
    .d2l_NVDLA_CACC_D_CYA_w(d2l_NVDLA_CACC_D_CYA_w),
    .d2l_NVDLA_CACC_D_CYA_we(d2l_NVDLA_CACC_D_CYA_we),
    .d2l_NVDLA_CACC_D_CYA_re(d2l_NVDLA_CACC_D_CYA_re),
    .h2l_NVDLA_CACC_S_STATUS_STATUS_0_w(h2l_NVDLA_CACC_S_STATUS_STATUS_0_w),
    .h2l_NVDLA_CACC_S_STATUS_STATUS_1_w(h2l_NVDLA_CACC_S_STATUS_STATUS_1_w),
    .h2l_NVDLA_CACC_S_POINTER_CONSUMER_w(h2l_NVDLA_CACC_S_POINTER_CONSUMER_w),
    .h2l_NVDLA_CACC_D_OUT_SATURATION_SAT_COUNT_w(h2l_NVDLA_CACC_D_OUT_SATURATION_SAT_COUNT_w),
    .l2d_NVDLA_CACC_S_STATUS_r(l2d_NVDLA_CACC_S_STATUS_r),
    .l2d_NVDLA_CACC_S_POINTER_r(l2d_NVDLA_CACC_S_POINTER_r),
    .l2d_NVDLA_CACC_D_OP_ENABLE_r(l2d_NVDLA_CACC_D_OP_ENABLE_r),
    .l2d_NVDLA_CACC_D_MISC_CFG_r(l2d_NVDLA_CACC_D_MISC_CFG_r),
    .l2d_NVDLA_CACC_D_DATAOUT_SIZE_0_r(l2d_NVDLA_CACC_D_DATAOUT_SIZE_0_r),
    .l2d_NVDLA_CACC_D_DATAOUT_SIZE_1_r(l2d_NVDLA_CACC_D_DATAOUT_SIZE_1_r),
    .l2d_NVDLA_CACC_D_DATAOUT_ADDR_r(l2d_NVDLA_CACC_D_DATAOUT_ADDR_r),
    .l2d_NVDLA_CACC_D_BATCH_NUMBER_r(l2d_NVDLA_CACC_D_BATCH_NUMBER_r),
    .l2d_NVDLA_CACC_D_LINE_STRIDE_r(l2d_NVDLA_CACC_D_LINE_STRIDE_r),
    .l2d_NVDLA_CACC_D_SURF_STRIDE_r(l2d_NVDLA_CACC_D_SURF_STRIDE_r),
    .l2d_NVDLA_CACC_D_DATAOUT_MAP_r(l2d_NVDLA_CACC_D_DATAOUT_MAP_r),
    .l2d_NVDLA_CACC_D_CLIP_CFG_r(l2d_NVDLA_CACC_D_CLIP_CFG_r),
    .l2d_NVDLA_CACC_D_OUT_SATURATION_r(l2d_NVDLA_CACC_D_OUT_SATURATION_r),
    .l2d_NVDLA_CACC_D_CYA_r(l2d_NVDLA_CACC_D_CYA_r),
    .l2h_NVDLA_CACC_S_POINTER_PRODUCER_r(l2h_NVDLA_CACC_S_POINTER_PRODUCER_r),
    .l2h_NVDLA_CACC_D_OP_ENABLE_OP_EN_r(l2h_NVDLA_CACC_D_OP_ENABLE_OP_EN_r),
    .l2h_NVDLA_CACC_D_MISC_CFG_CONV_MODE_r(l2h_NVDLA_CACC_D_MISC_CFG_CONV_MODE_r),
    .l2h_NVDLA_CACC_D_MISC_CFG_PROC_PRECISION_r(l2h_NVDLA_CACC_D_MISC_CFG_PROC_PRECISION_r),
    .l2h_NVDLA_CACC_D_DATAOUT_SIZE_0_DATAOUT_WIDTH_r(l2h_NVDLA_CACC_D_DATAOUT_SIZE_0_DATAOUT_WIDTH_r),
    .l2h_NVDLA_CACC_D_DATAOUT_SIZE_0_DATAOUT_HEIGHT_r(l2h_NVDLA_CACC_D_DATAOUT_SIZE_0_DATAOUT_HEIGHT_r),
    .l2h_NVDLA_CACC_D_DATAOUT_SIZE_1_DATAOUT_CHANNEL_r(l2h_NVDLA_CACC_D_DATAOUT_SIZE_1_DATAOUT_CHANNEL_r),
    .l2h_NVDLA_CACC_D_DATAOUT_ADDR_DATAOUT_ADDR_r(l2h_NVDLA_CACC_D_DATAOUT_ADDR_DATAOUT_ADDR_r),
    .l2h_NVDLA_CACC_D_BATCH_NUMBER_BATCHES_r(l2h_NVDLA_CACC_D_BATCH_NUMBER_BATCHES_r),
    .l2h_NVDLA_CACC_D_LINE_STRIDE_LINE_STRIDE_r(l2h_NVDLA_CACC_D_LINE_STRIDE_LINE_STRIDE_r),
    .l2h_NVDLA_CACC_D_SURF_STRIDE_SURF_STRIDE_r(l2h_NVDLA_CACC_D_SURF_STRIDE_SURF_STRIDE_r),
    .l2h_NVDLA_CACC_D_DATAOUT_MAP_LINE_PACKED_r(l2h_NVDLA_CACC_D_DATAOUT_MAP_LINE_PACKED_r),
    .l2h_NVDLA_CACC_D_DATAOUT_MAP_SURF_PACKED_r(l2h_NVDLA_CACC_D_DATAOUT_MAP_SURF_PACKED_r),
    .l2h_NVDLA_CACC_D_CLIP_CFG_CLIP_TRUNCATE_r(l2h_NVDLA_CACC_D_CLIP_CFG_CLIP_TRUNCATE_r),
    .l2h_NVDLA_CACC_D_CYA_CYA_r(l2h_NVDLA_CACC_D_CYA_CYA_r) );
    
endmodule

